// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置 Mock — C 实现
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 支付管理
 * 专为单元测试设计 — 固定返回值
 */

#include "payment.h"
#include <stdlib.h>

// Mock: 支付方式
static const char* mock_type_values(void* impl_ctx) {
    (void)impl_ctx;
    return "{\"1\":\"alipay\",\"2\":\"wechat\",\"3\":\"credit_card\"}";
}

// Mock: 支付记录状态
static const char* mock_record_status_values(void* impl_ctx) {
    (void)impl_ctx;
    return "{\"0\":\"pending\",\"1\":\"success\",\"2\":\"failed\",\"3\":\"refunded\"}";
}

// Mock vtable 实例 — 返回固定值
static const payment_config_vtable_t g_payment_mock_vtable = {
    .type_values = mock_type_values,
    .record_status_values = mock_record_status_values,
};

// payment_mock_init 初始化 Mock 适配器
// 将全局 vtable 设置为 Mock 实现，业务代码随后调用外观函数即可获得固定值
void payment_mock_init(void) {
    payment_config_set_impl(&g_payment_mock_vtable, NULL);
}
