// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

package com.douyinmall.adapter.blessstar;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import com.douyinmall.ports.ConfigReader;
import com.douyinmall.ports.AuthConfig;

/**
 * 认证鉴权域配置的 BlessStar 适配器
 * 业务系统: 抖音商城 (douyin-mall)
 * 内置三阶段降级: ConfigReader实时查询 -> LastKnownGood缓存 -> 硬编码默认值
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class AuthConfigAdapter implements AuthConfig {

	private final ConfigReader reader;
	private final Map<String, Object> lastKnownCache = new ConcurrentHashMap<>();
	private final Map<String, Object> hardcodedDefaults;

	/**
	 * 创建 AuthConfigAdapter 适配器实例
	 * @param reader 配置读取器，由业务方注入（可为 CachedReader、HTTPReader 等实现）
	 */
	public AuthConfigAdapter(ConfigReader reader) {
		this.reader = reader;
		this.hardcodedDefaults = new ConcurrentHashMap<>();
		this.hardcodedDefaults.put("getJwtTokenExpirySeconds", 86400L);
		this.hardcodedDefaults.put("getPasswordBcryptCost", 10);
	}

	@Override
	public long getJwtTokenExpirySeconds() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/douyin-mall/auth/jwt/token_expiry_seconds");
			if (val != null) {
				lastKnownCache.put("getJwtTokenExpirySeconds", val);
				return ((Number) val).longValue();
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getJwtTokenExpirySeconds");
		if (cached != null) {
			return ((Number) cached).longValue();
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getJwtTokenExpirySeconds");
		return ((Number) fallback).longValue();
	}

	@Override
	public int getPasswordBcryptCost() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/douyin-mall/auth/password/bcrypt_cost");
			if (val != null) {
				lastKnownCache.put("getPasswordBcryptCost", val);
				return ((Number) val).intValue();
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getPasswordBcryptCost");
		if (cached != null) {
			return ((Number) cached).intValue();
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getPasswordBcryptCost");
		return ((Number) fallback).intValue();
	}

}
