// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

package com.douyinmall.adapter.blessstar;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import com.douyinmall.ports.ConfigReader;
import com.douyinmall.ports.UserConfig;

/**
 * 用户管理域配置的 BlessStar 适配器
 * 业务系统: 抖音商城 (douyin-mall)
 * 内置三阶段降级: ConfigReader实时查询 -> LastKnownGood缓存 -> 硬编码默认值
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class UserConfigAdapter implements UserConfig {

	private final ConfigReader reader;
	private final Map<String, Object> lastKnownCache = new ConcurrentHashMap<>();
	private final Map<String, Object> hardcodedDefaults;

	/**
	 * 创建 UserConfigAdapter 适配器实例
	 * @param reader 配置读取器，由业务方注入（可为 CachedReader、HTTPReader 等实现）
	 */
	public UserConfigAdapter(ConfigReader reader) {
		this.reader = reader;
		this.hardcodedDefaults = new ConcurrentHashMap<>();
		this.hardcodedDefaults.put("getRoleValues", "[\"user\",\"admin\"]");
		this.hardcodedDefaults.put("getStatusValues", "{\"1\":\"active\",\"0\":\"inactive\",\"-1\":\"deleted\"}");
		this.hardcodedDefaults.put("getRegistrationDefaultRole", "user");
		this.hardcodedDefaults.put("getRegistrationDefaultStatus", 1);
		this.hardcodedDefaults.put("getValidationUsernameMinLength", 3);
		this.hardcodedDefaults.put("getValidationUsernameMaxLength", 50);
		this.hardcodedDefaults.put("getValidationPasswordMinLength", 6);
		this.hardcodedDefaults.put("getValidationPasswordMaxLength", 50);
		this.hardcodedDefaults.put("getValidationEmailRequired", true);
	}

	@Override
	public String getRoleValues() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/douyin-mall/user/role/values");
			if (val != null) {
				lastKnownCache.put("getRoleValues", val);
				return (String) val;
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getRoleValues");
		if (cached != null) {
			return (String) cached;
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getRoleValues");
		return (String) fallback;
	}

	@Override
	public String getStatusValues() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/douyin-mall/user/status/values");
			if (val != null) {
				lastKnownCache.put("getStatusValues", val);
				return (String) val;
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getStatusValues");
		if (cached != null) {
			return (String) cached;
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getStatusValues");
		return (String) fallback;
	}

	@Override
	public String getRegistrationDefaultRole() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/douyin-mall/user/registration/default_role");
			if (val != null) {
				lastKnownCache.put("getRegistrationDefaultRole", val);
				return (String) val;
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getRegistrationDefaultRole");
		if (cached != null) {
			return (String) cached;
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getRegistrationDefaultRole");
		return (String) fallback;
	}

	@Override
	public int getRegistrationDefaultStatus() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/douyin-mall/user/registration/default_status");
			if (val != null) {
				lastKnownCache.put("getRegistrationDefaultStatus", val);
				return ((Number) val).intValue();
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getRegistrationDefaultStatus");
		if (cached != null) {
			return ((Number) cached).intValue();
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getRegistrationDefaultStatus");
		return ((Number) fallback).intValue();
	}

	@Override
	public int getValidationUsernameMinLength() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/douyin-mall/user/validation/username_min_length");
			if (val != null) {
				lastKnownCache.put("getValidationUsernameMinLength", val);
				return ((Number) val).intValue();
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getValidationUsernameMinLength");
		if (cached != null) {
			return ((Number) cached).intValue();
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getValidationUsernameMinLength");
		return ((Number) fallback).intValue();
	}

	@Override
	public int getValidationUsernameMaxLength() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/douyin-mall/user/validation/username_max_length");
			if (val != null) {
				lastKnownCache.put("getValidationUsernameMaxLength", val);
				return ((Number) val).intValue();
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getValidationUsernameMaxLength");
		if (cached != null) {
			return ((Number) cached).intValue();
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getValidationUsernameMaxLength");
		return ((Number) fallback).intValue();
	}

	@Override
	public int getValidationPasswordMinLength() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/douyin-mall/user/validation/password_min_length");
			if (val != null) {
				lastKnownCache.put("getValidationPasswordMinLength", val);
				return ((Number) val).intValue();
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getValidationPasswordMinLength");
		if (cached != null) {
			return ((Number) cached).intValue();
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getValidationPasswordMinLength");
		return ((Number) fallback).intValue();
	}

	@Override
	public int getValidationPasswordMaxLength() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/douyin-mall/user/validation/password_max_length");
			if (val != null) {
				lastKnownCache.put("getValidationPasswordMaxLength", val);
				return ((Number) val).intValue();
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getValidationPasswordMaxLength");
		if (cached != null) {
			return ((Number) cached).intValue();
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getValidationPasswordMaxLength");
		return ((Number) fallback).intValue();
	}

	@Override
	public boolean getValidationEmailRequired() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/douyin-mall/user/validation/email_required");
			if (val != null) {
				lastKnownCache.put("getValidationEmailRequired", val);
				return (Boolean) val;
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getValidationEmailRequired");
		if (cached != null) {
			return (Boolean) cached;
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getValidationEmailRequired");
		return (Boolean) fallback;
	}

}
