// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

// Package adapter_mock 自动生成于 BlessStar 配置 Mock
// 业务系统: 抖音商城 (douyin-mall)
// 领域: 认证鉴权
// 专为单元测试设计 — 固定返回值

package adapter_mock

import (
	"context"
	"time"
	"douyin-mall/ports"
)

// AuthConfigMock 认证鉴权 域配置的 Mock 实现（单元测试用）
type AuthConfigMock struct {
	JwtTokenExpirySecondsFunc func(ctx context.Context) (time.Duration, error)
	PasswordBcryptCostFunc func(ctx context.Context) (int32, error)
}

// NewAuthConfigMock 创建默认 Mock（返回值按 manifest 默认值设定）
func NewAuthConfigMock() ports.AuthConfig {
	return &AuthConfigMock{
		JwtTokenExpirySecondsFunc: func(ctx context.Context) (time.Duration, error) {
			return int64(86400), nil
		},
		PasswordBcryptCostFunc: func(ctx context.Context) (int32, error) {
			return int32(10), nil
		},
	}
}

func (m *AuthConfigMock) JwtTokenExpirySeconds(ctx context.Context) (time.Duration, error) {
	return m.JwtTokenExpirySecondsFunc(ctx)
}

func (m *AuthConfigMock) PasswordBcryptCost(ctx context.Context) (int32, error) {
	return m.PasswordBcryptCostFunc(ctx)
}

