// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

// Package adapter_mock 自动生成于 BlessStar 配置 Mock
// 业务系统: 抖音商城 (douyin-mall)
// 领域: 安全策略
// 专为单元测试设计 — 固定返回值

package adapter_mock

import (
	"context"
	"douyin-mall/ports"
)

// CorsConfigMock 安全策略 域配置的 Mock 实现（单元测试用）
type CorsConfigMock struct {
	AllowedOriginsFunc func(ctx context.Context) ([]string, error)
}

// NewCorsConfigMock 创建默认 Mock（返回值按 manifest 默认值设定）
func NewCorsConfigMock() ports.CorsConfig {
	return &CorsConfigMock{
		AllowedOriginsFunc: func(ctx context.Context) ([]string, error) {
			return []string{"*"}, nil
		},
	}
}

func (m *CorsConfigMock) AllowedOrigins(ctx context.Context) ([]string, error) {
	return m.AllowedOriginsFunc(ctx)
}

