// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

// Package adapter_blessstar 自动生成于 BlessStar 配置端口-适配器
// 业务系统: 抖音商城 (douyin-mall)
// 领域: 支付管理
// 请勿手动修改 — 由 blessstar-codegen 自动生成

package adapter_blessstar

import (
	"context"
	"sync"

	"douyin-mall/ports"
)

// PaymentConfigAdapter 支付管理 域配置的 BlessStar 适配器
// 内置三阶段降级: ConfigReader实时查询 → LastKnownGood缓存 → 硬编码默认值
type PaymentConfigAdapter struct {
	reader          ports.ConfigReader
	lastKnownCache  sync.Map
	hardcodedDefaults  map[string]interface{}
}

// NewPaymentConfigAdapter 创建 PaymentConfigAdapter 适配器实例
// reader 参数是配置读取器，由业务方注入（可为 CachedReader、HTTPReader 等实现）
func NewPaymentConfigAdapter(reader ports.ConfigReader) ports.PaymentConfig {
	return &PaymentConfigAdapter{
		reader: reader,
		hardcodedDefaults: map[string]interface{}{
			"TypeValues": "{\"1\":\"alipay\",\"2\":\"wechat\",\"3\":\"credit_card\"}",
			"RecordStatusValues": "{\"0\":\"pending\",\"1\":\"success\",\"2\":\"failed\",\"3\":\"refunded\"}",
		},
	}
}

func (a *PaymentConfigAdapter) TypeValues(ctx context.Context) (string, error) {
	// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
	val, err := a.reader.Get(ctx, "/config/douyin-mall/payment/type/values")
	if err == nil {
		a.lastKnownCache.Store("TypeValues", val)
		return val.(string), nil
	}

	// 第2阶段: 降级到 Last Known Good 缓存
	if cached, ok := a.lastKnownCache.Load("TypeValues"); ok {
		return cached.(string), nil
	}

	// 第3阶段: 极冷启动 — 返回硬编码默认值
	return a.hardcodedDefaults["TypeValues"].(string), nil
}

func (a *PaymentConfigAdapter) RecordStatusValues(ctx context.Context) (string, error) {
	// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
	val, err := a.reader.Get(ctx, "/config/douyin-mall/payment/record_status/values")
	if err == nil {
		a.lastKnownCache.Store("RecordStatusValues", val)
		return val.(string), nil
	}

	// 第2阶段: 降级到 Last Known Good 缓存
	if cached, ok := a.lastKnownCache.Load("RecordStatusValues"); ok {
		return cached.(string), nil
	}

	// 第3阶段: 极冷启动 — 返回硬编码默认值
	return a.hardcodedDefaults["RecordStatusValues"].(string), nil
}

