#!/usr/bin/env python3
"""
Hand-written smoke test — validates generated provider works at runtime.
This file is NOT generated by blessstar-codegen.

Instantiates all adapters with a None reader, verifying the 3-tier fallback
(ConfigReader → LastKnownGood → hardcoded defaults) does not raise when
no real config source is available.
"""

import sys
import os

# Add the parent directory so we can import the provider package
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from provider.blessstar_provider import provide_blessstar_adapters


def test_smoke_nil_reader_no_panic():
    """Should not raise with None reader (falls through to hardcoded defaults)."""
    adapters = provide_blessstar_adapters(None)
    assert adapters is not None, "provide_blessstar_adapters(None) returned None"
    print("✅ blessstar_provider: Adapters created with None reader")

    # Call one method per domain
    assert adapters.product_config.status_values() is not None
    print("✅ ProductConfig.status_values() OK")

    assert adapters.cors_config.allowed_origins() is not None
    print("✅ CorsConfig.allowed_origins() OK")

    assert adapters.payment_config.type_values() is not None
    print("✅ PaymentConfig.type_values() OK")

    assert adapters.user_config.role_values() is not None
    print("✅ UserConfig.role_values() OK")

    assert adapters.order_config.status_values() is not None
    print("✅ OrderConfig.status_values() OK")

    assert adapters.auth_config.jwt_token_expiry_seconds() is not None
    print("✅ AuthConfig.jwt_token_expiry_seconds() OK")

    assert adapters.review_config.rating_min() is not None
    print("✅ ReviewConfig.rating_min() OK")

    print("🎉 All smoke tests passed!")


if __name__ == "__main__":
    test_smoke_nil_reader_no_panic()
