// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.ports;

/**
 * 安全策略域配置接口
 * 自动生成于 BlessStar 配置端口-适配器
 * 业务系统: 音乐网站 (music-website)
 * 领域: 安全策略
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public interface CorsConfig {

	/**
	 * 跨域白名单 (cors.allowed-origins)
	 * 描述: CORS 跨域允许的前端域名来源列表
	 * 建议值: 生产环境配置具体域名，格式：["https://music.example.com","https://admin.example.com"]
	 * 类型: ARR
	 */
	java.util.List<String> getAllowed-origins() throws Exception;

}
