// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.ports;

/**
 * 密码重置域配置接口
 * 自动生成于 BlessStar 配置端口-适配器
 * 业务系统: 音乐网站 (music-website)
 * 领域: 密码重置
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public interface 密码重置Config {

	/**
	 * 验证码有效期 (password-reset.code-ttl-minutes)
	 * 描述: 密码重置验证码的有效期（分钟）
	 * 建议值: 3~30（分钟），推荐步长1。建议 5~15 分钟
	 * 类型: I32
	 */
	int getCode-ttl-minutes() throws Exception;

	/**
	 * 发送冷却 (password-reset.send-cooldown-seconds)
	 * 描述: 密码重置验证码的发送冷却间隔（秒）
	 * 建议值: 5~60（秒），推荐步长5。建议 10~30 秒
	 * 类型: I32
	 */
	int getSend-cooldown-seconds() throws Exception;

	/**
	 * Mock 模式 (password-reset.mock-without-mail)
	 * 描述: 开发环境是否开启无邮件 Mock 模式，开启后 debugCode 直接在接口返回中显示
	 * 建议值: true/false。开发/测试环境可使用 true，生产环境必须为 false
	 * 类型: BOOL
	 */
	boolean getMock-without-mail() throws Exception;

}
