// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.ports;

/**
 * 对象存储配置域配置接口
 * 自动生成于 BlessStar 配置端口-适配器
 * 业务系统: 音乐网站 (music-website)
 * 领域: 对象存储配置
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public interface 对象存储配置Config {

	/**
	 * MinIO 端点 (minio.endpoint)
	 * 描述: MinIO 对象存储服务端点地址
	 * 建议值: http://<host>:<port> 或 https://<domain> 格式
	 * 类型: STR
	 */
	String getEndpoint() throws Exception;

	/**
	 * MinIO 桶名 (minio.bucket-name)
	 * 描述: MinIO 存储音频文件的桶名称
	 * 建议值: MinIO 桶名规则：3~63字符，支持小写字母、数字、短横线
	 * 类型: STR
	 */
	String getBucket-name() throws Exception;

}
