// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.ports;

/**
 * 数据库配置域配置接口
 * 自动生成于 BlessStar 配置端口-适配器
 * 业务系统: 音乐网站 (music-website)
 * 领域: 数据库配置
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public interface 数据库配置Config {

	/**
	 * 数据库连接 (spring.datasource.url)
	 * 描述: MySQL 数据库 JDBC 连接 URL
	 * 建议值: JDBC URL 格式：jdbc:mysql://<host>:<port>/<db>?参数。生产建议开启 useSSL=true 和 serverTimezone=UTC
	 * 类型: STR
	 */
	String getDatasourceUrl() throws Exception;

}
