// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.ports;

/**
 * 文件上传配置域配置接口
 * 自动生成于 BlessStar 配置端口-适配器
 * 业务系统: 音乐网站 (music-website)
 * 领域: 文件上传配置
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public interface 文件上传配置Config {

	/**
	 * 上传大小限制 (upload.max-file-size)
	 * 描述: 文件上传最大尺寸限制
	 * 建议值: 10MB~200MB，推荐步长10MB。音频文件建议 50MB 足够
	 * 类型: STR
	 */
	String getMax-file-size() throws Exception;

}
