// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.ports;

/**
 * 服务器配置域配置接口
 * 自动生成于 BlessStar 配置端口-适配器
 * 业务系统: 音乐网站 (music-website)
 * 领域: 服务器配置
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public interface 服务器配置Config {

	/**
	 * 服务器端口 (server.port)
	 * 描述: 应用 HTTP 服务监听端口
	 * 建议值: 1024~65535，推荐步长1。建议避免使用 3306/6379/5432 等已知服务端口
	 * 类型: I32
	 */
	int getPort() throws Exception;

}
