// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.ports;

/**
 * 登录安全域配置接口
 * 自动生成于 BlessStar 配置端口-适配器
 * 业务系统: 音乐网站 (music-website)
 * 领域: 登录安全
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public interface 登录安全Config {

	/**
	 * 登录失败阈值 (login.max-failed-attempts)
	 * 描述: 登录连续失败最大次数，超过后账号临时锁定
	 * 建议值: 3~20，推荐步长1。建议 5~10 次
	 * 类型: I32
	 */
	int getMax-failed-attempts() throws Exception;

	/**
	 * 锁定时间 (login.lock-minutes)
	 * 描述: 登录失败超出阈值后的账号锁定时间（分钟）
	 * 建议值: 1~60（分钟），推荐步长5。建议 5~15 分钟
	 * 类型: I32
	 */
	int getLock-minutes() throws Exception;

}
