// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.ports;

/**
 * 缓存配置域配置接口
 * 自动生成于 BlessStar 配置端口-适配器
 * 业务系统: 音乐网站 (music-website)
 * 领域: 缓存配置
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public interface 缓存配置Config {

	/**
	 * Redis 主机 (spring.redis.host)
	 * 描述: Redis 缓存服务器主机地址
	 * 建议值: 合法的 IPv4 地址、localhost 或域名
	 * 类型: STR
	 */
	String getRedisHost() throws Exception;

	/**
	 * Redis 端口 (spring.redis.port)
	 * 描述: Redis 服务器端口
	 * 建议值: 1024~65535，推荐步长1。Redis 默认端口 6379
	 * 类型: I32
	 */
	int getRedisPort() throws Exception;

	/**
	 * Redis 超时 (spring.redis.timeout)
	 * 描述: Redis 连接超时时间（毫秒）
	 * 建议值: 1000~300000（1秒~5分钟），推荐步长1000ms。生产建议 5000~30000ms
	 * 类型: I64
	 */
	long getRedisTimeout() throws Exception;

}
