// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置适配器 — C 实现
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 认证鉴权
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 * 内置三阶段降级: ConfigReader → 缓存 → 硬编码默认值
 */

#include "auth.h"
#include "ports/config_reader.h"
#include <stdlib.h>
#include <string.h>

// auth_config_adapter_t — 认证鉴权 域配置适配器结构体
typedef struct {
    config_reader_t* reader;
    struct {
        int64_t jwt_token_expiry_seconds;
        bool jwt_token_expiry_seconds_valid;
        int32_t password_bcrypt_cost;
        bool password_bcrypt_cost_valid;
    } cache;
} auth_config_adapter_t;

// 全局 vtable 指针和上下文
static const auth_config_vtable_t* g_auth_vtable = NULL;
static void* g_auth_ctx = NULL;

/** 认证鉴权 域配置适配器 — JWT过期时间 */
static int64_t auth_adapter_jwt_token_expiry_seconds(void* impl_ctx) {
    auth_config_adapter_t* adapter = (auth_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/auth/jwt/token_expiry_seconds", &val, &val_type) == 0 && val) {
            int64_t result = *(int64_t*)val;
            free(val);
            adapter->cache.jwt_token_expiry_seconds = result;
            adapter->cache.jwt_token_expiry_seconds_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.jwt_token_expiry_seconds_valid) {
        return adapter->cache.jwt_token_expiry_seconds;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return 86400;
}

/** 认证鉴权 域配置适配器 — 密码加密强度 */
static int32_t auth_adapter_password_bcrypt_cost(void* impl_ctx) {
    auth_config_adapter_t* adapter = (auth_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/auth/password/bcrypt_cost", &val, &val_type) == 0 && val) {
            int32_t result = *(int32_t*)val;
            free(val);
            adapter->cache.password_bcrypt_cost = result;
            adapter->cache.password_bcrypt_cost_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.password_bcrypt_cost_valid) {
        return adapter->cache.password_bcrypt_cost;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return 10;
}

// Auth 域 vtable 实例
static const auth_config_vtable_t g_auth_vtable_impl = {
    .jwt_token_expiry_seconds = auth_adapter_jwt_token_expiry_seconds,
    .password_bcrypt_cost = auth_adapter_password_bcrypt_cost,
};

void auth_config_set_impl(const auth_config_vtable_t* vtable, void* impl_ctx) {
    g_auth_vtable = vtable;
    g_auth_ctx = impl_ctx;
}

// 外观函数实现 — 通过 vtable 委派实际调用
int64_t auth_config_jwt_token_expiry_seconds() {
    if (g_auth_vtable && g_auth_vtable->jwt_token_expiry_seconds) {
        return g_auth_vtable->jwt_token_expiry_seconds(g_auth_ctx);
    }
    return 86400;
}

int32_t auth_config_password_bcrypt_cost() {
    if (g_auth_vtable && g_auth_vtable->password_bcrypt_cost) {
        return g_auth_vtable->password_bcrypt_cost(g_auth_ctx);
    }
    return 10;
}

