// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置适配器 — C 实现
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 安全策略
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 * 内置三阶段降级: ConfigReader → 缓存 → 硬编码默认值
 */

#include "cors.h"
#include "ports/config_reader.h"
#include <stdlib.h>
#include <string.h>

// cors_config_adapter_t — 安全策略 域配置适配器结构体
typedef struct {
    config_reader_t* reader;
    struct {
        const char** allowed_origins;
        bool allowed_origins_valid;
        bool allowed_origins_owned;
    } cache;
} cors_config_adapter_t;

// 全局 vtable 指针和上下文
static const cors_config_vtable_t* g_cors_vtable = NULL;
static void* g_cors_ctx = NULL;

/** 安全策略 域配置适配器 — 跨域白名单 */
static const char** cors_adapter_allowed_origins(void* impl_ctx, size_t* out_len) {
    cors_config_adapter_t* adapter = (cors_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/cors/allowed_origins", &val, &val_type) == 0 && val) {
            const char** result = (const char**)val;
            if (out_len) *out_len = 0; /* caller must determine length */
            adapter->cache.allowed_origins = result;
            adapter->cache.allowed_origins_valid = true;
            adapter->cache.allowed_origins_owned = false;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.allowed_origins_valid) {
        return adapter->cache.allowed_origins;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return "[\"*\"]";
}

// Cors 域 vtable 实例
static const cors_config_vtable_t g_cors_vtable_impl = {
    .allowed_origins = cors_adapter_allowed_origins,
};

void cors_config_set_impl(const cors_config_vtable_t* vtable, void* impl_ctx) {
    g_cors_vtable = vtable;
    g_cors_ctx = impl_ctx;
}

// 外观函数实现 — 通过 vtable 委派实际调用
const char** cors_config_allowed_origins(size_t* out_len) {
    if (g_cors_vtable && g_cors_vtable->allowed_origins) {
        return g_cors_vtable->allowed_origins(g_cors_ctx, out_len);
    }
    if (out_len) *out_len = 0;
    return NULL;
}

