// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置适配器 — C 实现
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 支付管理
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 * 内置三阶段降级: ConfigReader → 缓存 → 硬编码默认值
 */

#include "payment.h"
#include "ports/config_reader.h"
#include <stdlib.h>
#include <string.h>

// payment_config_adapter_t — 支付管理 域配置适配器结构体
typedef struct {
    config_reader_t* reader;
    struct {
        const char* type_values;
        bool type_values_valid;
        bool type_values_owned;
        const char* record_status_values;
        bool record_status_values_valid;
        bool record_status_values_owned;
    } cache;
} payment_config_adapter_t;

// 全局 vtable 指针和上下文
static const payment_config_vtable_t* g_payment_vtable = NULL;
static void* g_payment_ctx = NULL;

/** 支付管理 域配置适配器 — 支付方式 */
static const char* payment_adapter_type_values(void* impl_ctx) {
    payment_config_adapter_t* adapter = (payment_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/payment/type/values", &val, &val_type) == 0 && val) {
            const char* result = (const char*)val;
            adapter->cache.type_values = result;
            adapter->cache.type_values_valid = true;
            adapter->cache.type_values_owned = false;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.type_values_valid) {
        return adapter->cache.type_values;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return "{\"1\":\"alipay\",\"2\":\"wechat\",\"3\":\"credit_card\"}";
}

/** 支付管理 域配置适配器 — 支付记录状态 */
static const char* payment_adapter_record_status_values(void* impl_ctx) {
    payment_config_adapter_t* adapter = (payment_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/payment/record_status/values", &val, &val_type) == 0 && val) {
            const char* result = (const char*)val;
            adapter->cache.record_status_values = result;
            adapter->cache.record_status_values_valid = true;
            adapter->cache.record_status_values_owned = false;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.record_status_values_valid) {
        return adapter->cache.record_status_values;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return "{\"0\":\"pending\",\"1\":\"success\",\"2\":\"failed\",\"3\":\"refunded\"}";
}

// Payment 域 vtable 实例
static const payment_config_vtable_t g_payment_vtable_impl = {
    .type_values = payment_adapter_type_values,
    .record_status_values = payment_adapter_record_status_values,
};

void payment_config_set_impl(const payment_config_vtable_t* vtable, void* impl_ctx) {
    g_payment_vtable = vtable;
    g_payment_ctx = impl_ctx;
}

// 外观函数实现 — 通过 vtable 委派实际调用
const char* payment_config_type_values() {
    if (g_payment_vtable && g_payment_vtable->type_values) {
        return g_payment_vtable->type_values(g_payment_ctx);
    }
    return "{\"1\":\"alipay\",\"2\":\"wechat\",\"3\":\"credit_card\"}";
}

const char* payment_config_record_status_values() {
    if (g_payment_vtable && g_payment_vtable->record_status_values) {
        return g_payment_vtable->record_status_values(g_payment_ctx);
    }
    return "{\"0\":\"pending\",\"1\":\"success\",\"2\":\"failed\",\"3\":\"refunded\"}";
}

