// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置适配器 — C 实现
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 评价管理
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 * 内置三阶段降级: ConfigReader → 缓存 → 硬编码默认值
 */

#include "review.h"
#include "ports/config_reader.h"
#include <stdlib.h>
#include <string.h>

// review_config_adapter_t — 评价管理 域配置适配器结构体
typedef struct {
    config_reader_t* reader;
    struct {
        int32_t rating_min;
        bool rating_min_valid;
        int32_t rating_max;
        bool rating_max_valid;
    } cache;
} review_config_adapter_t;

// 全局 vtable 指针和上下文
static const review_config_vtable_t* g_review_vtable = NULL;
static void* g_review_ctx = NULL;

/** 评价管理 域配置适配器 — 评分下限 */
static int32_t review_adapter_rating_min(void* impl_ctx) {
    review_config_adapter_t* adapter = (review_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/review/rating/min", &val, &val_type) == 0 && val) {
            int32_t result = *(int32_t*)val;
            free(val);
            adapter->cache.rating_min = result;
            adapter->cache.rating_min_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.rating_min_valid) {
        return adapter->cache.rating_min;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return 1;
}

/** 评价管理 域配置适配器 — 评分上限 */
static int32_t review_adapter_rating_max(void* impl_ctx) {
    review_config_adapter_t* adapter = (review_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/review/rating/max", &val, &val_type) == 0 && val) {
            int32_t result = *(int32_t*)val;
            free(val);
            adapter->cache.rating_max = result;
            adapter->cache.rating_max_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.rating_max_valid) {
        return adapter->cache.rating_max;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return 5;
}

// Review 域 vtable 实例
static const review_config_vtable_t g_review_vtable_impl = {
    .rating_min = review_adapter_rating_min,
    .rating_max = review_adapter_rating_max,
};

void review_config_set_impl(const review_config_vtable_t* vtable, void* impl_ctx) {
    g_review_vtable = vtable;
    g_review_ctx = impl_ctx;
}

// 外观函数实现 — 通过 vtable 委派实际调用
int32_t review_config_rating_min() {
    if (g_review_vtable && g_review_vtable->rating_min) {
        return g_review_vtable->rating_min(g_review_ctx);
    }
    return 1;
}

int32_t review_config_rating_max() {
    if (g_review_vtable && g_review_vtable->rating_max) {
        return g_review_vtable->rating_max(g_review_ctx);
    }
    return 5;
}

