// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置适配器 — C 实现
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 用户管理
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 * 内置三阶段降级: ConfigReader → 缓存 → 硬编码默认值
 */

#include "user.h"
#include "ports/config_reader.h"
#include <stdlib.h>
#include <string.h>

// user_config_adapter_t — 用户管理 域配置适配器结构体
typedef struct {
    config_reader_t* reader;
    struct {
        const char* role_values;
        bool role_values_valid;
        bool role_values_owned;
        const char* status_values;
        bool status_values_valid;
        bool status_values_owned;
        const char* registration_default_role;
        bool registration_default_role_valid;
        bool registration_default_role_owned;
        int32_t registration_default_status;
        bool registration_default_status_valid;
        int32_t validation_username_min_length;
        bool validation_username_min_length_valid;
        int32_t validation_username_max_length;
        bool validation_username_max_length_valid;
        int32_t validation_password_min_length;
        bool validation_password_min_length_valid;
        int32_t validation_password_max_length;
        bool validation_password_max_length_valid;
        bool validation_email_required;
        bool validation_email_required_valid;
    } cache;
} user_config_adapter_t;

// 全局 vtable 指针和上下文
static const user_config_vtable_t* g_user_vtable = NULL;
static void* g_user_ctx = NULL;

/** 用户管理 域配置适配器 — 用户角色 */
static const char* user_adapter_role_values(void* impl_ctx) {
    user_config_adapter_t* adapter = (user_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/user/role/values", &val, &val_type) == 0 && val) {
            const char* result = (const char*)val;
            adapter->cache.role_values = result;
            adapter->cache.role_values_valid = true;
            adapter->cache.role_values_owned = false;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.role_values_valid) {
        return adapter->cache.role_values;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return "[\"user\",\"admin\"]";
}

/** 用户管理 域配置适配器 — 用户状态 */
static const char* user_adapter_status_values(void* impl_ctx) {
    user_config_adapter_t* adapter = (user_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/user/status/values", &val, &val_type) == 0 && val) {
            const char* result = (const char*)val;
            adapter->cache.status_values = result;
            adapter->cache.status_values_valid = true;
            adapter->cache.status_values_owned = false;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.status_values_valid) {
        return adapter->cache.status_values;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return "{\"1\":\"active\",\"0\":\"inactive\",\"-1\":\"deleted\"}";
}

/** 用户管理 域配置适配器 — 默认角色 */
static const char* user_adapter_registration_default_role(void* impl_ctx) {
    user_config_adapter_t* adapter = (user_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/user/registration/default_role", &val, &val_type) == 0 && val) {
            const char* result = (const char*)val;
            adapter->cache.registration_default_role = result;
            adapter->cache.registration_default_role_valid = true;
            adapter->cache.registration_default_role_owned = false;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.registration_default_role_valid) {
        return adapter->cache.registration_default_role;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return "user";
}

/** 用户管理 域配置适配器 — 默认状态 */
static int32_t user_adapter_registration_default_status(void* impl_ctx) {
    user_config_adapter_t* adapter = (user_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/user/registration/default_status", &val, &val_type) == 0 && val) {
            int32_t result = *(int32_t*)val;
            free(val);
            adapter->cache.registration_default_status = result;
            adapter->cache.registration_default_status_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.registration_default_status_valid) {
        return adapter->cache.registration_default_status;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return 1;
}

/** 用户管理 域配置适配器 — 用户名最小长度 */
static int32_t user_adapter_validation_username_min_length(void* impl_ctx) {
    user_config_adapter_t* adapter = (user_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/user/validation/username_min_length", &val, &val_type) == 0 && val) {
            int32_t result = *(int32_t*)val;
            free(val);
            adapter->cache.validation_username_min_length = result;
            adapter->cache.validation_username_min_length_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.validation_username_min_length_valid) {
        return adapter->cache.validation_username_min_length;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return 3;
}

/** 用户管理 域配置适配器 — 用户名最大长度 */
static int32_t user_adapter_validation_username_max_length(void* impl_ctx) {
    user_config_adapter_t* adapter = (user_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/user/validation/username_max_length", &val, &val_type) == 0 && val) {
            int32_t result = *(int32_t*)val;
            free(val);
            adapter->cache.validation_username_max_length = result;
            adapter->cache.validation_username_max_length_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.validation_username_max_length_valid) {
        return adapter->cache.validation_username_max_length;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return 50;
}

/** 用户管理 域配置适配器 — 密码最小长度 */
static int32_t user_adapter_validation_password_min_length(void* impl_ctx) {
    user_config_adapter_t* adapter = (user_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/user/validation/password_min_length", &val, &val_type) == 0 && val) {
            int32_t result = *(int32_t*)val;
            free(val);
            adapter->cache.validation_password_min_length = result;
            adapter->cache.validation_password_min_length_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.validation_password_min_length_valid) {
        return adapter->cache.validation_password_min_length;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return 6;
}

/** 用户管理 域配置适配器 — 密码最大长度 */
static int32_t user_adapter_validation_password_max_length(void* impl_ctx) {
    user_config_adapter_t* adapter = (user_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/user/validation/password_max_length", &val, &val_type) == 0 && val) {
            int32_t result = *(int32_t*)val;
            free(val);
            adapter->cache.validation_password_max_length = result;
            adapter->cache.validation_password_max_length_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.validation_password_max_length_valid) {
        return adapter->cache.validation_password_max_length;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return 50;
}

/** 用户管理 域配置适配器 — 邮箱必填 */
static bool user_adapter_validation_email_required(void* impl_ctx) {
    user_config_adapter_t* adapter = (user_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/user/validation/email_required", &val, &val_type) == 0 && val) {
            bool result = *(bool*)val;
            free(val);
            adapter->cache.validation_email_required = result;
            adapter->cache.validation_email_required_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.validation_email_required_valid) {
        return adapter->cache.validation_email_required;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return true;
}

// User 域 vtable 实例
static const user_config_vtable_t g_user_vtable_impl = {
    .role_values = user_adapter_role_values,
    .status_values = user_adapter_status_values,
    .registration_default_role = user_adapter_registration_default_role,
    .registration_default_status = user_adapter_registration_default_status,
    .validation_username_min_length = user_adapter_validation_username_min_length,
    .validation_username_max_length = user_adapter_validation_username_max_length,
    .validation_password_min_length = user_adapter_validation_password_min_length,
    .validation_password_max_length = user_adapter_validation_password_max_length,
    .validation_email_required = user_adapter_validation_email_required,
};

void user_config_set_impl(const user_config_vtable_t* vtable, void* impl_ctx) {
    g_user_vtable = vtable;
    g_user_ctx = impl_ctx;
}

// 外观函数实现 — 通过 vtable 委派实际调用
const char* user_config_role_values() {
    if (g_user_vtable && g_user_vtable->role_values) {
        return g_user_vtable->role_values(g_user_ctx);
    }
    return "[\"user\",\"admin\"]";
}

const char* user_config_status_values() {
    if (g_user_vtable && g_user_vtable->status_values) {
        return g_user_vtable->status_values(g_user_ctx);
    }
    return "{\"1\":\"active\",\"0\":\"inactive\",\"-1\":\"deleted\"}";
}

const char* user_config_registration_default_role() {
    if (g_user_vtable && g_user_vtable->registration_default_role) {
        return g_user_vtable->registration_default_role(g_user_ctx);
    }
    return "user";
}

int32_t user_config_registration_default_status() {
    if (g_user_vtable && g_user_vtable->registration_default_status) {
        return g_user_vtable->registration_default_status(g_user_ctx);
    }
    return 1;
}

int32_t user_config_validation_username_min_length() {
    if (g_user_vtable && g_user_vtable->validation_username_min_length) {
        return g_user_vtable->validation_username_min_length(g_user_ctx);
    }
    return 3;
}

int32_t user_config_validation_username_max_length() {
    if (g_user_vtable && g_user_vtable->validation_username_max_length) {
        return g_user_vtable->validation_username_max_length(g_user_ctx);
    }
    return 50;
}

int32_t user_config_validation_password_min_length() {
    if (g_user_vtable && g_user_vtable->validation_password_min_length) {
        return g_user_vtable->validation_password_min_length(g_user_ctx);
    }
    return 6;
}

int32_t user_config_validation_password_max_length() {
    if (g_user_vtable && g_user_vtable->validation_password_max_length) {
        return g_user_vtable->validation_password_max_length(g_user_ctx);
    }
    return 50;
}

bool user_config_validation_email_required() {
    if (g_user_vtable && g_user_vtable->validation_email_required) {
        return g_user_vtable->validation_email_required(g_user_ctx);
    }
    return true;
}

