// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: config-schema.yaml
// Business System: livedesign (livedesign)

// Package provider 提供 BlessStar 配置的依赖注入和可选装饰器。
// 请勿手动修改 — 由 blessstar-codegen 自动生成

import { ConfigReader } from '../ports/config-reader';

/**
 * CachedReader 是对 ConfigReader 的缓存包装器（可选装饰器）。
 * 使用 setInterval 定时刷新缓存，实现秒级准实时热更新。
 * 不依赖任何外部库。
 *
 * 使用方式（由 main.ts 注入）：
 *
 *   const rawReader: ConfigReader = new HttpReader();
 *   const cachedReader = new CachedReader(rawReader, 30_000);
 *   const adapters = provideBlessStarAdapters(cachedReader);
 */
export class CachedReader implements ConfigReader {
  private inner: ConfigReader;
  private cache: Map<string, unknown> = new Map();
  private intervalId: ReturnType<typeof setInterval> | null = null;
  private refreshFn: () => Promise<void> = async () => {};

  /**
   * @param inner 底层 ConfigReader 实现
   * @param intervalMs 缓存刷新周期（毫秒）
   */
  constructor(inner: ConfigReader, intervalMs: number = 30000) {
    this.inner = inner;
    this.intervalId = setInterval(async () => {
      try {
        await this.refreshFn();
      } catch {
        // 刷新失败不影响现有缓存，仅跳过本轮
      }
    }, intervalMs);
  }

  /**
   * setRefreshFn 设置全量刷新回调函数，由业务方自定义需要缓存的配置路径。
   */
  setRefreshFn(fn: () => Promise<void>): this {
    this.refreshFn = fn;
    return this;
  }

  /**
   * 从缓存中读取配置值。若缓存命中直接返回，否则穿透到 inner ConfigReader。
   */
  async get(path: string): Promise<unknown> {
    if (this.cache.has(path)) {
      return this.cache.get(path);
    }
    const val = await this.inner.get(path);
    if (val !== undefined) {
      this.cache.set(path, val);
    }
    return val;
  }

  /**
   * 手动设置缓存值（用于预热）。
   */
  set(path: string, value: unknown): void {
    this.cache.set(path, value);
  }

  /**
   * 停止后台刷新定时器。
   */
  destroy(): void {
    if (this.intervalId !== null) {
      clearInterval(this.intervalId);
      this.intervalId = null;
    }
    this.cache.clear();
  }
}