// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

module douyin-mall

go 1.21

// 零外部依赖 — ConfigReader 由业务方自行实现
// 无外部 SDK 依赖，生成的 adapter 代码仅依赖 Go 标准库和本 module
