// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

// Package adapter_blessstar 自动生成于 BlessStar 配置端口-适配器
// 业务系统: 抖音商城 (douyin-mall)
// 领域: 安全策略
// 请勿手动修改 — 由 blessstar-codegen 自动生成

package adapter_blessstar

import (
	"context"
	"sync"

	"douyin-mall/ports"
)

// CorsConfigAdapter 安全策略 域配置的 BlessStar 适配器
// 内置三阶段降级: ConfigReader实时查询 → LastKnownGood缓存 → 硬编码默认值
type CorsConfigAdapter struct {
	reader          ports.ConfigReader
	lastKnownCache  sync.Map
	hardcodedDefaults  map[string]interface{}
}

// NewCorsConfigAdapter 创建 CorsConfigAdapter 适配器实例
// reader 参数是配置读取器，由业务方注入（可为 CachedReader、HTTPReader 等实现）
func NewCorsConfigAdapter(reader ports.ConfigReader) ports.CorsConfig {
	return &CorsConfigAdapter{
		reader: reader,
		hardcodedDefaults: map[string]interface{}{
			"AllowedOrigins": []string{"*"},
		},
	}
}

func (a *CorsConfigAdapter) AllowedOrigins(ctx context.Context) ([]string, error) {
	// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
	val, err := a.reader.Get(ctx, "/config/douyin-mall/cors/allowed_origins")
	if err == nil {
		a.lastKnownCache.Store("AllowedOrigins", val)
		return val.([]string), nil
	}

	// 第2阶段: 降级到 Last Known Good 缓存
	if cached, ok := a.lastKnownCache.Load("AllowedOrigins"); ok {
		return cached.([]string), nil
	}

	// 第3阶段: 极冷启动 — 返回硬编码默认值
	return a.hardcodedDefaults["AllowedOrigins"].([]string), nil
}

