# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: 抖音商城 (douyin-mall)

# Package adapter_blessstar — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: 抖音商城 (douyin-mall)
# 领域: 支付管理
# 请勿手动修改 — 由 blessstar-codegen 自动生成

from typing import Any, Dict
from contextlib import AbstractContextManager
from ports.config_reader import ConfigReader
from ports.payment import PaymentConfig


class PaymentConfigAdapter(PaymentConfig):
    """支付管理域配置的 BlessStar 适配器
    内置三阶段降级: ConfigReader实时查询 → 缓存 → 硬编码默认值
    """

    def __init__(self, reader: ConfigReader) -> None:
        self._reader = reader
        self._cache: Dict[str, Any] = {}
        self._defaults: Dict[str, Any] = {
            "type_values": "{\"1\":\"alipay\",\"2\":\"wechat\",\"3\":\"credit_card\"}",
            "record_status_values": "{\"0\":\"pending\",\"1\":\"success\",\"2\":\"failed\",\"3\":\"refunded\"}",
        }

    def type_values(self, ctx: AbstractContextManager) -> str:
        path = "/config/douyin-mall/payment/type/values"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["type_values"] = val
            return str(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "type_values" in self._cache:
            return str(self._cache["type_values"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return str(self._defaults["type_values"])

    def record_status_values(self, ctx: AbstractContextManager) -> str:
        path = "/config/douyin-mall/payment/record_status/values"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["record_status_values"] = val
            return str(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "record_status_values" in self._cache:
            return str(self._cache["record_status_values"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return str(self._defaults["record_status_values"])

