// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置适配器 — C 实现
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 商品管理
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 * 内置三阶段降级: ConfigReader → 缓存 → 硬编码默认值
 */

#include "product.h"
#include "ports/config_reader.h"
#include <stdlib.h>
#include <string.h>

// product_config_adapter_t — 商品管理 域配置适配器结构体
typedef struct {
    config_reader_t* reader;
    struct {
        const char* status_values;
        bool status_values_valid;
        bool status_values_owned;
    } cache;
} product_config_adapter_t;

// 全局 vtable 指针和上下文
static const product_config_vtable_t* g_product_vtable = NULL;
static void* g_product_ctx = NULL;

/** 商品管理 域配置适配器 — 商品状态 */
static const char* product_adapter_status_values(void* impl_ctx) {
    product_config_adapter_t* adapter = (product_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/douyin-mall/product/status/values", &val, &val_type) == 0 && val) {
            const char* result = (const char*)val;
            adapter->cache.status_values = result;
            adapter->cache.status_values_valid = true;
            adapter->cache.status_values_owned = false;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.status_values_valid) {
        return adapter->cache.status_values;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return "{\"1\":\"on_sale\",\"0\":\"off_sale\",\"-1\":\"deleted\"}";
}

// Product 域 vtable 实例
static const product_config_vtable_t g_product_vtable_impl = {
    .status_values = product_adapter_status_values,
};

void product_config_set_impl(const product_config_vtable_t* vtable, void* impl_ctx) {
    g_product_vtable = vtable;
    g_product_ctx = impl_ctx;
}

// 外观函数实现 — 通过 vtable 委派实际调用
const char* product_config_status_values() {
    if (g_product_vtable && g_product_vtable->status_values) {
        return g_product_vtable->status_values(g_product_ctx);
    }
    return "{\"1\":\"on_sale\",\"0\":\"off_sale\",\"-1\":\"deleted\"}";
}

