// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: config-schema.yaml
// Business System: livedesign (livedesign)

// Gate configs for config-schema.yaml contracts
// 请勿手动修改 — 由 blessstar-codegen 自动生成

/**
 * GateRule 门禁规则定义
 */
export interface GateRule {
  fieldKey: string;
  gateType: 'RANGE' | 'DEPENDENCY' | 'APPROVAL' | 'SLO_WARNING';
  params: Record<string, string>;
}

/**
 * GATE_RULES 从 config-schema.yaml contract 段自动生成的门禁规则
 */
export const GATE_RULES: GateRule[] = [
  {
    fieldKey: "assistant.tools",
    gateType: "APPROVAL",
    params: { required: "true" },
  },
  {
    fieldKey: "assistant.tools",
    gateType: "SLO_WARNING",
    params: { slo_impact: "用户数据安全与操作权限" },
  },
  {
    fieldKey: "avatar.position_x",
    gateType: "RANGE",
    params: { min: "-1920" },
  },
  {
    fieldKey: "avatar.position_x",
    gateType: "RANGE",
    params: { max: "3840" },
  },
  {
    fieldKey: "avatar.position_x",
    gateType: "SLO_WARNING",
    params: { slo_impact: "UI 定位准确性" },
  },
  {
    fieldKey: "avatar.position_y",
    gateType: "RANGE",
    params: { min: "-1080" },
  },
  {
    fieldKey: "avatar.position_y",
    gateType: "RANGE",
    params: { max: "2160" },
  },
  {
    fieldKey: "avatar.position_y",
    gateType: "SLO_WARNING",
    params: { slo_impact: "UI 定位准确性" },
  },
  {
    fieldKey: "avatar.scale",
    gateType: "SLO_WARNING",
    params: { slo_impact: "角色渲染视觉效果" },
  },
  {
    fieldKey: "chat.role_preset",
    gateType: "SLO_WARNING",
    params: { slo_impact: "对话角色一致性" },
  },
  {
    fieldKey: "chat.temperature",
    gateType: "SLO_WARNING",
    params: { slo_impact: "AI 回复质量与一致性" },
  },
  {
    fieldKey: "plugin.enabled",
    gateType: "APPROVAL",
    params: { required: "true" },
  },
  {
    fieldKey: "plugin.enabled",
    gateType: "SLO_WARNING",
    params: { slo_impact: "系统安全与功能扩展" },
  },
  {
    fieldKey: "ui.theme",
    gateType: "SLO_WARNING",
    params: { slo_impact: "用户视觉体验" },
  },
  {
    fieldKey: "ui.transparency",
    gateType: "SLO_WARNING",
    params: { slo_impact: "悬浮球视觉效果" },
  },
];
