# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: 抖音商城 (douyin-mall)

# Package adapters.mock — Mock 适配器实现（单元测试用）
# 请勿手动修改 — 由 blessstar-codegen 自动生成

from .product_mock import ProductConfigMock
from .cors_mock import CorsConfigMock
from .payment_mock import PaymentConfigMock
from .user_mock import UserConfigMock
from .order_mock import OrderConfigMock
from .auth_mock import AuthConfigMock
from .review_mock import ReviewConfigMock
