# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: 抖音商城 (douyin-mall)

# Package adapter_mock — 自动生成于 BlessStar 配置 Mock
# 业务系统: 抖音商城 (douyin-mall)
# 领域: 订单管理
# 专为单元测试设计 — 固定返回值

from typing import Callable
from contextlib import AbstractContextManager
from ports.order import OrderConfig


class OrderConfigMock(OrderConfig):
    """订单管理域配置的 Mock 实现（单元测试用）"""

    def __init__(self) -> None:
        self.status_values_func: Callable[[AbstractContextManager], str] = lambda ctx: "{\"0\":\"pending_payment\",\"1\":\"paid\",\"2\":\"shipped\",\"3\":\"delivered\",\"4\":\"completed\",\"-1\":\"cancelled\"}"

    @classmethod
    def create_default(cls) -> OrderConfig:
        """创建默认 Mock 实例（返回值按 manifest 默认值设定）"""
        return cls()

    def status_values(self, ctx: AbstractContextManager) -> str:
        return self.status_values_func(ctx)

