# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: 抖音商城 (douyin-mall)

# Package adapter_mock — 自动生成于 BlessStar 配置 Mock
# 业务系统: 抖音商城 (douyin-mall)
# 领域: 支付管理
# 专为单元测试设计 — 固定返回值

from typing import Callable
from contextlib import AbstractContextManager
from ports.payment import PaymentConfig


class PaymentConfigMock(PaymentConfig):
    """支付管理域配置的 Mock 实现（单元测试用）"""

    def __init__(self) -> None:
        self.type_values_func: Callable[[AbstractContextManager], str] = lambda ctx: "{\"1\":\"alipay\",\"2\":\"wechat\",\"3\":\"credit_card\"}"
        self.record_status_values_func: Callable[[AbstractContextManager], str] = lambda ctx: "{\"0\":\"pending\",\"1\":\"success\",\"2\":\"failed\",\"3\":\"refunded\"}"

    @classmethod
    def create_default(cls) -> PaymentConfig:
        """创建默认 Mock 实例（返回值按 manifest 默认值设定）"""
        return cls()

    def type_values(self, ctx: AbstractContextManager) -> str:
        return self.type_values_func(ctx)

    def record_status_values(self, ctx: AbstractContextManager) -> str:
        return self.record_status_values_func(ctx)

