# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: 抖音商城 (douyin-mall)

# Package adapter_mock — 自动生成于 BlessStar 配置 Mock
# 业务系统: 抖音商城 (douyin-mall)
# 领域: 评价管理
# 专为单元测试设计 — 固定返回值

from typing import Callable
from contextlib import AbstractContextManager
from ports.review import ReviewConfig


class ReviewConfigMock(ReviewConfig):
    """评价管理域配置的 Mock 实现（单元测试用）"""

    def __init__(self) -> None:
        self.rating_min_func: Callable[[AbstractContextManager], int] = lambda ctx: 1
        self.rating_max_func: Callable[[AbstractContextManager], int] = lambda ctx: 5

    @classmethod
    def create_default(cls) -> ReviewConfig:
        """创建默认 Mock 实例（返回值按 manifest 默认值设定）"""
        return cls()

    def rating_min(self, ctx: AbstractContextManager) -> int:
        return self.rating_min_func(ctx)

    def rating_max(self, ctx: AbstractContextManager) -> int:
        return self.rating_max_func(ctx)

