# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: 抖音商城 (douyin-mall)

# Package adapter_mock — 自动生成于 BlessStar 配置 Mock
# 业务系统: 抖音商城 (douyin-mall)
# 领域: 用户管理
# 专为单元测试设计 — 固定返回值

from typing import Callable
from contextlib import AbstractContextManager
from ports.user import UserConfig


class UserConfigMock(UserConfig):
    """用户管理域配置的 Mock 实现（单元测试用）"""

    def __init__(self) -> None:
        self.role_values_func: Callable[[AbstractContextManager], str] = lambda ctx: "[\"user\",\"admin\"]"
        self.status_values_func: Callable[[AbstractContextManager], str] = lambda ctx: "{\"1\":\"active\",\"0\":\"inactive\",\"-1\":\"deleted\"}"
        self.registration_default_role_func: Callable[[AbstractContextManager], str] = lambda ctx: "user"
        self.registration_default_status_func: Callable[[AbstractContextManager], int] = lambda ctx: 1
        self.validation_username_min_length_func: Callable[[AbstractContextManager], int] = lambda ctx: 3
        self.validation_username_max_length_func: Callable[[AbstractContextManager], int] = lambda ctx: 50
        self.validation_password_min_length_func: Callable[[AbstractContextManager], int] = lambda ctx: 6
        self.validation_password_max_length_func: Callable[[AbstractContextManager], int] = lambda ctx: 50
        self.validation_email_required_func: Callable[[AbstractContextManager], bool] = lambda ctx: True

    @classmethod
    def create_default(cls) -> UserConfig:
        """创建默认 Mock 实例（返回值按 manifest 默认值设定）"""
        return cls()

    def role_values(self, ctx: AbstractContextManager) -> str:
        return self.role_values_func(ctx)

    def status_values(self, ctx: AbstractContextManager) -> str:
        return self.status_values_func(ctx)

    def registration_default_role(self, ctx: AbstractContextManager) -> str:
        return self.registration_default_role_func(ctx)

    def registration_default_status(self, ctx: AbstractContextManager) -> int:
        return self.registration_default_status_func(ctx)

    def validation_username_min_length(self, ctx: AbstractContextManager) -> int:
        return self.validation_username_min_length_func(ctx)

    def validation_username_max_length(self, ctx: AbstractContextManager) -> int:
        return self.validation_username_max_length_func(ctx)

    def validation_password_min_length(self, ctx: AbstractContextManager) -> int:
        return self.validation_password_min_length_func(ctx)

    def validation_password_max_length(self, ctx: AbstractContextManager) -> int:
        return self.validation_password_max_length_func(ctx)

    def validation_email_required(self, ctx: AbstractContextManager) -> bool:
        return self.validation_email_required_func(ctx)

