/*
 * Hand-written smoke test — validates generated provider works at runtime.
 * This file is NOT generated by blessstar-codegen.
 *
 * Instantiates all adapters with a NULL reader, verifying the 3-tier fallback
 * (ConfigReader -> LastKnownGood -> hardcoded defaults) does not crash when
 * no real config source is available.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

#include "ports/config_reader.h"
#include "ports/product.h"
#include "ports/cors.h"
#include "ports/payment.h"
#include "ports/user.h"
#include "ports/order.h"
#include "ports/auth.h"
#include "ports/review.h"

// blessstar_provider.c does not have a separate header;
// declare the init function here.
extern void douyin_mall_provide_adapters(config_reader_t* reader);

// Dummy reader vtable — always returns error to force hardcoded fallback
static int dummy_get(void* ctx, const char* path, void** out_val, const char** out_type) {
    (void)ctx;
    (void)path;
    (void)out_val;
    (void)out_type;
    return -1; /* always fail — force fallback to hardcoded defaults */
}

static const config_reader_vtable_t dummy_vtable = {
    .impl_ctx = NULL,
    .get = dummy_get,
};

int main(void) {
    config_reader_t dummy_reader;
    dummy_reader.vtable = &dummy_vtable;

    /* Init all adapters with the dummy reader */
    douyin_mall_provide_adapters(&dummy_reader);
    printf("✅ douyin_mall_provide_adapters() OK\n");

    /* Call one function per domain — should all return hardcoded defaults */
    const char* status = product_config_status_values();
    assert(status != NULL);
    assert(strlen(status) > 0);
    printf("✅ product_config_status_values() = %s\n", status);

    const char* origins = cors_config_allowed_origins();
    assert(origins != NULL);
    printf("✅ cors_config_allowed_origins() = %s\n", origins);

    const char* pay_types = payment_config_type_values();
    assert(pay_types != NULL);
    printf("✅ payment_config_type_values() = %s\n", pay_types);

    const char* roles = user_config_role_values();
    assert(roles != NULL);
    printf("✅ user_config_role_values() = %s\n", roles);

    const char* order_status = order_config_status_values();
    assert(order_status != NULL);
    printf("✅ order_config_status_values() = %s\n", order_status);

    int64_t expiry = auth_config_jwt_token_expiry_seconds();
    printf("✅ auth_config_jwt_token_expiry_seconds() = %lld\n", (long long)expiry);

    int64_t min_rating = review_config_rating_min();
    printf("✅ review_config_rating_min() = %lld\n", (long long)min_rating);

    printf("🎉 All C smoke tests passed!\n");
    return 0;
}
