// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: Mongoose IoT (mongoose)

/**
 * 自动生成于 BlessStar 配置依赖注入 — C 实现
 * 业务系统: Mongoose IoT (mongoose)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */

#include "ports/config_reader.h"
#include "ports/协议功能.h"
#include "ports/存储适配.h"
#include "ports/系统适配.h"
#include "ports/缓冲区配置.h"
#include "ports/网络参数.h"
#include "ports/网络栈选择.h"

/**
 * blessstar_provide_adapters 一行初始化所有域配置适配器。
 * 由业务方在启动时调用，传入 ConfigReader 实例。
 * reader 为 NULL 时仅加载硬编码默认值（极冷启动降级）。
 */
void mongoose_provide_adapters(config_reader_t* reader) {
    (void)reader;

    // 协议功能 域 — 创建适配器并注册
    static 协议功能_config_adapter_t 协议功能_adapter_inst;
    协议功能_adapter_inst.reader = reader;
    协议功能_adapter_inst.cache.MG_MAX_HTTP_HEADERS_valid = false;
    协议功能_adapter_inst.cache.MG_ENABLE_IPV6_valid = false;
    协议功能_adapter_inst.cache.MG_ENABLE_MD5_valid = false;
    协议功能_adapter_inst.cache.MG_ENABLE_DIRLIST_valid = false;
    协议功能_adapter_inst.cache.MG_ENABLE_CHACHA20_valid = false;
    协议功能_config_set_impl(&g_协议功能_vtable_impl, &协议功能_adapter_inst);

    // 存储适配 域 — 创建适配器并注册
    static 存储适配_config_adapter_t 存储适配_adapter_inst;
    存储适配_adapter_inst.reader = reader;
    存储适配_adapter_inst.cache.MG_ENABLE_FATFS_valid = false;
    存储适配_adapter_inst.cache.MG_ENABLE_LFS_valid = false;
    存储适配_config_set_impl(&g_存储适配_vtable_impl, &存储适配_adapter_inst);

    // 系统适配 域 — 创建适配器并注册
    static 系统适配_config_adapter_t 系统适配_adapter_inst;
    系统适配_adapter_inst.reader = reader;
    系统适配_adapter_inst.cache.MG_ENABLE_LOG_valid = false;
    系统适配_adapter_inst.cache.MG_ENABLE_FREERTOS_valid = false;
    系统适配_adapter_inst.cache.MG_ENABLE_EPOLL_valid = false;
    系统适配_config_set_impl(&g_系统适配_vtable_impl, &系统适配_adapter_inst);

    // 缓冲区配置 域 — 创建适配器并注册
    static 缓冲区配置_config_adapter_t 缓冲区配置_adapter_inst;
    缓冲区配置_adapter_inst.reader = reader;
    缓冲区配置_adapter_inst.cache.MG_IO_SIZE_valid = false;
    缓冲区配置_adapter_inst.cache.MG_MAX_RECV_SIZE_valid = false;
    缓冲区配置_config_set_impl(&g_缓冲区配置_vtable_impl, &缓冲区配置_adapter_inst);

    // 网络参数 域 — 创建适配器并注册
    static 网络参数_config_adapter_t 网络参数_adapter_inst;
    网络参数_adapter_inst.reader = reader;
    网络参数_adapter_inst.cache.MG_SOCK_LISTEN_BACKLOG_SIZE_valid = false;
    网络参数_config_set_impl(&g_网络参数_vtable_impl, &网络参数_adapter_inst);

    // 网络栈选择 域 — 创建适配器并注册
    static 网络栈选择_config_adapter_t 网络栈选择_adapter_inst;
    网络栈选择_adapter_inst.reader = reader;
    网络栈选择_adapter_inst.cache.MG_ENABLE_TCPIP_valid = false;
    网络栈选择_adapter_inst.cache.MG_ENABLE_LWIP_valid = false;
    网络栈选择_config_set_impl(&g_网络栈选择_vtable_impl, &网络栈选择_adapter_inst);
}
