// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: Mongoose IoT (mongoose)

/**
 * 自动生成于 BlessStar 配置适配器 — C 实现
 * 业务系统: Mongoose IoT (mongoose)
 * 领域: 协议功能
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 * 内置三阶段降级: ConfigReader → 缓存 → 硬编码默认值
 */

#include "协议功能.h"
#include "ports/config_reader.h"
#include <stdlib.h>
#include <string.h>

// 协议功能_config_adapter_t — 协议功能 域配置适配器结构体
typedef struct {
    config_reader_t* reader;
    struct {
        int32_t MG_MAX_HTTP_HEADERS;
        bool MG_MAX_HTTP_HEADERS_valid;
        bool MG_ENABLE_IPV6;
        bool MG_ENABLE_IPV6_valid;
        bool MG_ENABLE_MD5;
        bool MG_ENABLE_MD5_valid;
        bool MG_ENABLE_DIRLIST;
        bool MG_ENABLE_DIRLIST_valid;
        bool MG_ENABLE_CHACHA20;
        bool MG_ENABLE_CHACHA20_valid;
    } cache;
} 协议功能_config_adapter_t;

// 全局 vtable 指针和上下文
static const 协议功能_config_vtable_t* g_协议功能_vtable = NULL;
static void* g_协议功能_ctx = NULL;

/** 协议功能 域配置适配器 — 最大 HTTP 头数 */
static int32_t 协议功能_adapter_MG_MAX_HTTP_HEADERS(void* impl_ctx) {
    协议功能_config_adapter_t* adapter = (协议功能_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/mongoose/protocol/max_http_headers", &val, &val_type) == 0 && val) {
            int32_t result = *(int32_t*)val;
            free(val);
            adapter->cache.MG_MAX_HTTP_HEADERS = result;
            adapter->cache.MG_MAX_HTTP_HEADERS_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.MG_MAX_HTTP_HEADERS_valid) {
        return adapter->cache.MG_MAX_HTTP_HEADERS;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return 30;
}

/** 协议功能 域配置适配器 — IPv6 支持 */
static bool 协议功能_adapter_MG_ENABLE_IPV6(void* impl_ctx) {
    协议功能_config_adapter_t* adapter = (协议功能_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/mongoose/protocol/ipv6", &val, &val_type) == 0 && val) {
            bool result = *(bool*)val;
            free(val);
            adapter->cache.MG_ENABLE_IPV6 = result;
            adapter->cache.MG_ENABLE_IPV6_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.MG_ENABLE_IPV6_valid) {
        return adapter->cache.MG_ENABLE_IPV6;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return false;
}

/** 协议功能 域配置适配器 — MD5 支持 */
static bool 协议功能_adapter_MG_ENABLE_MD5(void* impl_ctx) {
    协议功能_config_adapter_t* adapter = (协议功能_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/mongoose/protocol/md5", &val, &val_type) == 0 && val) {
            bool result = *(bool*)val;
            free(val);
            adapter->cache.MG_ENABLE_MD5 = result;
            adapter->cache.MG_ENABLE_MD5_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.MG_ENABLE_MD5_valid) {
        return adapter->cache.MG_ENABLE_MD5;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return true;
}

/** 协议功能 域配置适配器 — HTTP 目录列表 */
static bool 协议功能_adapter_MG_ENABLE_DIRLIST(void* impl_ctx) {
    协议功能_config_adapter_t* adapter = (协议功能_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/mongoose/protocol/dirlist", &val, &val_type) == 0 && val) {
            bool result = *(bool*)val;
            free(val);
            adapter->cache.MG_ENABLE_DIRLIST = result;
            adapter->cache.MG_ENABLE_DIRLIST_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.MG_ENABLE_DIRLIST_valid) {
        return adapter->cache.MG_ENABLE_DIRLIST;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return false;
}

/** 协议功能 域配置适配器 — ChaCha20 加密 */
static bool 协议功能_adapter_MG_ENABLE_CHACHA20(void* impl_ctx) {
    协议功能_config_adapter_t* adapter = (协议功能_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/mongoose/protocol/chacha20", &val, &val_type) == 0 && val) {
            bool result = *(bool*)val;
            free(val);
            adapter->cache.MG_ENABLE_CHACHA20 = result;
            adapter->cache.MG_ENABLE_CHACHA20_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.MG_ENABLE_CHACHA20_valid) {
        return adapter->cache.MG_ENABLE_CHACHA20;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return true;
}

// 协议功能 域 vtable 实例
static const 协议功能_config_vtable_t g_协议功能_vtable_impl = {
    .MG_MAX_HTTP_HEADERS = 协议功能_adapter_MG_MAX_HTTP_HEADERS,
    .MG_ENABLE_IPV6 = 协议功能_adapter_MG_ENABLE_IPV6,
    .MG_ENABLE_MD5 = 协议功能_adapter_MG_ENABLE_MD5,
    .MG_ENABLE_DIRLIST = 协议功能_adapter_MG_ENABLE_DIRLIST,
    .MG_ENABLE_CHACHA20 = 协议功能_adapter_MG_ENABLE_CHACHA20,
};

void 协议功能_config_set_impl(const 协议功能_config_vtable_t* vtable, void* impl_ctx) {
    g_协议功能_vtable = vtable;
    g_协议功能_ctx = impl_ctx;
}

// 外观函数实现 — 通过 vtable 委派实际调用
int32_t 协议功能_config_MG_MAX_HTTP_HEADERS() {
    if (g_协议功能_vtable && g_协议功能_vtable->MG_MAX_HTTP_HEADERS) {
        return g_协议功能_vtable->MG_MAX_HTTP_HEADERS(g_协议功能_ctx);
    }
    return 30;
}

bool 协议功能_config_MG_ENABLE_IPV6() {
    if (g_协议功能_vtable && g_协议功能_vtable->MG_ENABLE_IPV6) {
        return g_协议功能_vtable->MG_ENABLE_IPV6(g_协议功能_ctx);
    }
    return false;
}

bool 协议功能_config_MG_ENABLE_MD5() {
    if (g_协议功能_vtable && g_协议功能_vtable->MG_ENABLE_MD5) {
        return g_协议功能_vtable->MG_ENABLE_MD5(g_协议功能_ctx);
    }
    return true;
}

bool 协议功能_config_MG_ENABLE_DIRLIST() {
    if (g_协议功能_vtable && g_协议功能_vtable->MG_ENABLE_DIRLIST) {
        return g_协议功能_vtable->MG_ENABLE_DIRLIST(g_协议功能_ctx);
    }
    return false;
}

bool 协议功能_config_MG_ENABLE_CHACHA20() {
    if (g_协议功能_vtable && g_协议功能_vtable->MG_ENABLE_CHACHA20) {
        return g_协议功能_vtable->MG_ENABLE_CHACHA20(g_协议功能_ctx);
    }
    return true;
}

