// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: Mongoose IoT (mongoose)

/**
 * 自动生成于 BlessStar 配置适配器 — C 实现
 * 业务系统: Mongoose IoT (mongoose)
 * 领域: 存储适配
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 * 内置三阶段降级: ConfigReader → 缓存 → 硬编码默认值
 */

#include "存储适配.h"
#include "ports/config_reader.h"
#include <stdlib.h>
#include <string.h>

// 存储适配_config_adapter_t — 存储适配 域配置适配器结构体
typedef struct {
    config_reader_t* reader;
    struct {
        bool MG_ENABLE_FATFS;
        bool MG_ENABLE_FATFS_valid;
        bool MG_ENABLE_LFS;
        bool MG_ENABLE_LFS_valid;
    } cache;
} 存储适配_config_adapter_t;

// 全局 vtable 指针和上下文
static const 存储适配_config_vtable_t* g_存储适配_vtable = NULL;
static void* g_存储适配_ctx = NULL;

/** 存储适配 域配置适配器 — FATFS 支持 */
static bool 存储适配_adapter_MG_ENABLE_FATFS(void* impl_ctx) {
    存储适配_config_adapter_t* adapter = (存储适配_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/mongoose/storage/fatfs", &val, &val_type) == 0 && val) {
            bool result = *(bool*)val;
            free(val);
            adapter->cache.MG_ENABLE_FATFS = result;
            adapter->cache.MG_ENABLE_FATFS_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.MG_ENABLE_FATFS_valid) {
        return adapter->cache.MG_ENABLE_FATFS;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return false;
}

/** 存储适配 域配置适配器 — LittleFS 支持 */
static bool 存储适配_adapter_MG_ENABLE_LFS(void* impl_ctx) {
    存储适配_config_adapter_t* adapter = (存储适配_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/mongoose/storage/lfs", &val, &val_type) == 0 && val) {
            bool result = *(bool*)val;
            free(val);
            adapter->cache.MG_ENABLE_LFS = result;
            adapter->cache.MG_ENABLE_LFS_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.MG_ENABLE_LFS_valid) {
        return adapter->cache.MG_ENABLE_LFS;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return false;
}

// 存储适配 域 vtable 实例
static const 存储适配_config_vtable_t g_存储适配_vtable_impl = {
    .MG_ENABLE_FATFS = 存储适配_adapter_MG_ENABLE_FATFS,
    .MG_ENABLE_LFS = 存储适配_adapter_MG_ENABLE_LFS,
};

void 存储适配_config_set_impl(const 存储适配_config_vtable_t* vtable, void* impl_ctx) {
    g_存储适配_vtable = vtable;
    g_存储适配_ctx = impl_ctx;
}

// 外观函数实现 — 通过 vtable 委派实际调用
bool 存储适配_config_MG_ENABLE_FATFS() {
    if (g_存储适配_vtable && g_存储适配_vtable->MG_ENABLE_FATFS) {
        return g_存储适配_vtable->MG_ENABLE_FATFS(g_存储适配_ctx);
    }
    return false;
}

bool 存储适配_config_MG_ENABLE_LFS() {
    if (g_存储适配_vtable && g_存储适配_vtable->MG_ENABLE_LFS) {
        return g_存储适配_vtable->MG_ENABLE_LFS(g_存储适配_ctx);
    }
    return false;
}

