// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: Mongoose IoT (mongoose)

/**
 * 自动生成于 BlessStar 配置适配器 — C 实现
 * 业务系统: Mongoose IoT (mongoose)
 * 领域: 系统适配
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 * 内置三阶段降级: ConfigReader → 缓存 → 硬编码默认值
 */

#include "系统适配.h"
#include "ports/config_reader.h"
#include <stdlib.h>
#include <string.h>

// 系统适配_config_adapter_t — 系统适配 域配置适配器结构体
typedef struct {
    config_reader_t* reader;
    struct {
        bool MG_ENABLE_LOG;
        bool MG_ENABLE_LOG_valid;
        bool MG_ENABLE_FREERTOS;
        bool MG_ENABLE_FREERTOS_valid;
        bool MG_ENABLE_EPOLL;
        bool MG_ENABLE_EPOLL_valid;
    } cache;
} 系统适配_config_adapter_t;

// 全局 vtable 指针和上下文
static const 系统适配_config_vtable_t* g_系统适配_vtable = NULL;
static void* g_系统适配_ctx = NULL;

/** 系统适配 域配置适配器 — 日志开关 */
static bool 系统适配_adapter_MG_ENABLE_LOG(void* impl_ctx) {
    系统适配_config_adapter_t* adapter = (系统适配_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/mongoose/system/enable_log", &val, &val_type) == 0 && val) {
            bool result = *(bool*)val;
            free(val);
            adapter->cache.MG_ENABLE_LOG = result;
            adapter->cache.MG_ENABLE_LOG_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.MG_ENABLE_LOG_valid) {
        return adapter->cache.MG_ENABLE_LOG;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return true;
}

/** 系统适配 域配置适配器 — FreeRTOS 支持 */
static bool 系统适配_adapter_MG_ENABLE_FREERTOS(void* impl_ctx) {
    系统适配_config_adapter_t* adapter = (系统适配_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/mongoose/system/freertos", &val, &val_type) == 0 && val) {
            bool result = *(bool*)val;
            free(val);
            adapter->cache.MG_ENABLE_FREERTOS = result;
            adapter->cache.MG_ENABLE_FREERTOS_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.MG_ENABLE_FREERTOS_valid) {
        return adapter->cache.MG_ENABLE_FREERTOS;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return false;
}

/** 系统适配 域配置适配器 — epoll 支持 */
static bool 系统适配_adapter_MG_ENABLE_EPOLL(void* impl_ctx) {
    系统适配_config_adapter_t* adapter = (系统适配_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/mongoose/system/epoll", &val, &val_type) == 0 && val) {
            bool result = *(bool*)val;
            free(val);
            adapter->cache.MG_ENABLE_EPOLL = result;
            adapter->cache.MG_ENABLE_EPOLL_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.MG_ENABLE_EPOLL_valid) {
        return adapter->cache.MG_ENABLE_EPOLL;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return false;
}

// 系统适配 域 vtable 实例
static const 系统适配_config_vtable_t g_系统适配_vtable_impl = {
    .MG_ENABLE_LOG = 系统适配_adapter_MG_ENABLE_LOG,
    .MG_ENABLE_FREERTOS = 系统适配_adapter_MG_ENABLE_FREERTOS,
    .MG_ENABLE_EPOLL = 系统适配_adapter_MG_ENABLE_EPOLL,
};

void 系统适配_config_set_impl(const 系统适配_config_vtable_t* vtable, void* impl_ctx) {
    g_系统适配_vtable = vtable;
    g_系统适配_ctx = impl_ctx;
}

// 外观函数实现 — 通过 vtable 委派实际调用
bool 系统适配_config_MG_ENABLE_LOG() {
    if (g_系统适配_vtable && g_系统适配_vtable->MG_ENABLE_LOG) {
        return g_系统适配_vtable->MG_ENABLE_LOG(g_系统适配_ctx);
    }
    return true;
}

bool 系统适配_config_MG_ENABLE_FREERTOS() {
    if (g_系统适配_vtable && g_系统适配_vtable->MG_ENABLE_FREERTOS) {
        return g_系统适配_vtable->MG_ENABLE_FREERTOS(g_系统适配_ctx);
    }
    return false;
}

bool 系统适配_config_MG_ENABLE_EPOLL() {
    if (g_系统适配_vtable && g_系统适配_vtable->MG_ENABLE_EPOLL) {
        return g_系统适配_vtable->MG_ENABLE_EPOLL(g_系统适配_ctx);
    }
    return false;
}

