// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: Mongoose IoT (mongoose)

/**
 * 自动生成于 BlessStar 配置适配器 — C 实现
 * 业务系统: Mongoose IoT (mongoose)
 * 领域: 缓冲区配置
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 * 内置三阶段降级: ConfigReader → 缓存 → 硬编码默认值
 */

#include "缓冲区配置.h"
#include "ports/config_reader.h"
#include <stdlib.h>
#include <string.h>

// 缓冲区配置_config_adapter_t — 缓冲区配置 域配置适配器结构体
typedef struct {
    config_reader_t* reader;
    struct {
        int32_t MG_IO_SIZE;
        bool MG_IO_SIZE_valid;
        int64_t MG_MAX_RECV_SIZE;
        bool MG_MAX_RECV_SIZE_valid;
    } cache;
} 缓冲区配置_config_adapter_t;

// 全局 vtable 指针和上下文
static const 缓冲区配置_config_vtable_t* g_缓冲区配置_vtable = NULL;
static void* g_缓冲区配置_ctx = NULL;

/** 缓冲区配置 域配置适配器 — IO 缓冲粒度 */
static int32_t 缓冲区配置_adapter_MG_IO_SIZE(void* impl_ctx) {
    缓冲区配置_config_adapter_t* adapter = (缓冲区配置_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/mongoose/buffer/io_size", &val, &val_type) == 0 && val) {
            int32_t result = *(int32_t*)val;
            free(val);
            adapter->cache.MG_IO_SIZE = result;
            adapter->cache.MG_IO_SIZE_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.MG_IO_SIZE_valid) {
        return adapter->cache.MG_IO_SIZE;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return 512;
}

/** 缓冲区配置 域配置适配器 — 最大接收缓冲 */
static int64_t 缓冲区配置_adapter_MG_MAX_RECV_SIZE(void* impl_ctx) {
    缓冲区配置_config_adapter_t* adapter = (缓冲区配置_config_adapter_t*)impl_ctx;

    // 第1阶段: ConfigReader 实时查询
    if (adapter->reader) {
        void* val = NULL;
        const char* val_type = NULL;
        if (adapter->reader->get(adapter->reader->impl_ctx, "/config/mongoose/buffer/max_recv_size", &val, &val_type) == 0 && val) {
            int64_t result = *(int64_t*)val;
            free(val);
            adapter->cache.MG_MAX_RECV_SIZE = result;
            adapter->cache.MG_MAX_RECV_SIZE_valid = true;
            return result;
        }
    }

    // 第2阶段: 降级到缓存
    if (adapter->cache.MG_MAX_RECV_SIZE_valid) {
        return adapter->cache.MG_MAX_RECV_SIZE;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return 3145728;
}

// 缓冲区配置 域 vtable 实例
static const 缓冲区配置_config_vtable_t g_缓冲区配置_vtable_impl = {
    .MG_IO_SIZE = 缓冲区配置_adapter_MG_IO_SIZE,
    .MG_MAX_RECV_SIZE = 缓冲区配置_adapter_MG_MAX_RECV_SIZE,
};

void 缓冲区配置_config_set_impl(const 缓冲区配置_config_vtable_t* vtable, void* impl_ctx) {
    g_缓冲区配置_vtable = vtable;
    g_缓冲区配置_ctx = impl_ctx;
}

// 外观函数实现 — 通过 vtable 委派实际调用
int32_t 缓冲区配置_config_MG_IO_SIZE() {
    if (g_缓冲区配置_vtable && g_缓冲区配置_vtable->MG_IO_SIZE) {
        return g_缓冲区配置_vtable->MG_IO_SIZE(g_缓冲区配置_ctx);
    }
    return 512;
}

int64_t 缓冲区配置_config_MG_MAX_RECV_SIZE() {
    if (g_缓冲区配置_vtable && g_缓冲区配置_vtable->MG_MAX_RECV_SIZE) {
        return g_缓冲区配置_vtable->MG_MAX_RECV_SIZE(g_缓冲区配置_ctx);
    }
    return 3145728;
}

