// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: Mongoose IoT (mongoose)

/**
 * 自动生成于 BlessStar 配置 — ConfigReader C 头文件
 * 业务系统: Mongoose IoT (mongoose)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */

#ifndef PORTS_CONFIG_READER_H
#define PORTS_CONFIG_READER_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * config_reader_t — 配置读取器接口
 * 通过 vtable + impl_ctx 实现多态
 * 内置实现包括: CachedReader（秒级轮询缓存）、EnvReader（环境变量）、FileReader（本地文件）等。
 *
 * get: 读取一个配置值。
 *   @param ctx    实现上下文指针
 *   @param path   配置的完整注册路径 (如 "/config/mongoose/auth/jwt/token_expiry_seconds")
 *   @param out_val 输出配置值 (需要 free 释放)
 *   @param out_type 输出类型字符串 (如 "int64_t", "bool", "const char*")
 *   @return 0 成功, 非0 失败
 */
typedef struct {
    void* impl_ctx;
    int (*get)(void* ctx, const char* path, void** out_val, const char** out_type);
} config_reader_vtable_t;

// config_reader_t 结构体 — 业务方使用的读取器句柄
typedef struct {
    const config_reader_vtable_t* vtable;
} config_reader_t;

// 全局 ConfigReader 实例
extern config_reader_t* g_config_reader;

// 设置全局 ConfigReader
void config_reader_set_impl(const config_reader_vtable_t* vtable);

#ifdef __cplusplus
}
#endif

#endif /* PORTS_CONFIG_READER_H */
