// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: Mongoose IoT (mongoose)

/**
 * 自动生成于 BlessStar 配置端口 — C 头文件
 * 业务系统: Mongoose IoT (mongoose)
 * 领域: 协议功能
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */

#ifndef MONGOOSE_PORTS_协议功能_H
#define MONGOOSE_PORTS_协议功能_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * 协议功能 域配置接口
 * 通过 vtable + setter 模式注入具体实现
 * 业务代码通过外观函数访问配置，无需关心底层实现
 */

// 协议功能Config — 函数指针表
typedef struct {
    int32_t (*MG_MAX_HTTP_HEADERS)(void* impl_ctx);
    bool (*MG_ENABLE_IPV6)(void* impl_ctx);
    bool (*MG_ENABLE_MD5)(void* impl_ctx);
    bool (*MG_ENABLE_DIRLIST)(void* impl_ctx);
    bool (*MG_ENABLE_CHACHA20)(void* impl_ctx);
} 协议功能_config_vtable_t;

// 全局 setter — 由 adapter 层在初始化时调用
void 协议功能_config_set_impl(const 协议功能_config_vtable_t* vtable, void* impl_ctx);

// 业务代码调用的外观函数
/**
 * 最大 HTTP 头数 (MG_MAX_HTTP_HEADERS)
 * 描述: HTTP 解析时支持的最大头部数量
 * 建议值: 10~100，推荐步长5。默认 30 适合大多数场景
 * 类型: I32
 */
int32_t 协议功能_config_MG_MAX_HTTP_HEADERS();
/**
 * IPv6 支持 (MG_ENABLE_IPV6)
 * 描述: 启用 IPv6 协议栈支持
 * 建议值: 0（禁用）/ 1（启用，需网络环境支持）
 * 类型: BOOL
 */
bool 协议功能_config_MG_ENABLE_IPV6();
/**
 * MD5 支持 (MG_ENABLE_MD5)
 * 描述: 启用 MD5 哈希算法支持
 * 建议值: 0（禁用）/ 1（启用）
 * 类型: BOOL
 */
bool 协议功能_config_MG_ENABLE_MD5();
/**
 * HTTP 目录列表 (MG_ENABLE_DIRLIST)
 * 描述: 启用 HTTP 目录列表功能
 * 建议值: 0（禁用）/ 1（启用，仅开发/内部使用）
 * 类型: BOOL
 */
bool 协议功能_config_MG_ENABLE_DIRLIST();
/**
 * ChaCha20 加密 (MG_ENABLE_CHACHA20)
 * 描述: 启用 ChaCha20 加密算法（为 0 时使用 GCM，基于 MG_TLS_BUILTIN）
 * 建议值: 0（GCM 模式）/ 1（ChaCha20 模式，默认）
 * 类型: BOOL
 */
bool 协议功能_config_MG_ENABLE_CHACHA20();

#ifdef __cplusplus
}
#endif

#endif /* MONGOOSE_PORTS_协议功能_H */
