// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: Mongoose IoT (mongoose)

/**
 * 自动生成于 BlessStar 配置端口 — C 头文件
 * 业务系统: Mongoose IoT (mongoose)
 * 领域: 存储适配
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */

#ifndef MONGOOSE_PORTS_存储适配_H
#define MONGOOSE_PORTS_存储适配_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * 存储适配 域配置接口
 * 通过 vtable + setter 模式注入具体实现
 * 业务代码通过外观函数访问配置，无需关心底层实现
 */

// 存储适配Config — 函数指针表
typedef struct {
    bool (*MG_ENABLE_FATFS)(void* impl_ctx);
    bool (*MG_ENABLE_LFS)(void* impl_ctx);
} 存储适配_config_vtable_t;

// 全局 setter — 由 adapter 层在初始化时调用
void 存储适配_config_set_impl(const 存储适配_config_vtable_t* vtable, void* impl_ctx);

// 业务代码调用的外观函数
/**
 * FATFS 支持 (MG_ENABLE_FATFS)
 * 描述: 启用 FATFS 文件系统支持
 * 建议值: 0（禁用）/ 1（启用，与 LFS 互斥）
 * 类型: BOOL
 */
bool 存储适配_config_MG_ENABLE_FATFS();
/**
 * LittleFS 支持 (MG_ENABLE_LFS)
 * 描述: 启用 LittleFS 文件系统支持（轻量级嵌入式 FS）
 * 建议值: 0（禁用）/ 1（启用，与 FATFS 互斥）
 * 类型: BOOL
 */
bool 存储适配_config_MG_ENABLE_LFS();

#ifdef __cplusplus
}
#endif

#endif /* MONGOOSE_PORTS_存储适配_H */
