// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: Mongoose IoT (mongoose)

/**
 * 自动生成于 BlessStar 配置端口 — C 头文件
 * 业务系统: Mongoose IoT (mongoose)
 * 领域: 系统适配
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */

#ifndef MONGOOSE_PORTS_系统适配_H
#define MONGOOSE_PORTS_系统适配_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * 系统适配 域配置接口
 * 通过 vtable + setter 模式注入具体实现
 * 业务代码通过外观函数访问配置，无需关心底层实现
 */

// 系统适配Config — 函数指针表
typedef struct {
    bool (*MG_ENABLE_LOG)(void* impl_ctx);
    bool (*MG_ENABLE_FREERTOS)(void* impl_ctx);
    bool (*MG_ENABLE_EPOLL)(void* impl_ctx);
} 系统适配_config_vtable_t;

// 全局 setter — 由 adapter 层在初始化时调用
void 系统适配_config_set_impl(const 系统适配_config_vtable_t* vtable, void* impl_ctx);

// 业务代码调用的外观函数
/**
 * 日志开关 (MG_ENABLE_LOG)
 * 描述: 启用 Mongoose 内置日志输出
 * 建议值: 0（关闭）/ 1（启用）
 * 类型: BOOL
 */
bool 系统适配_config_MG_ENABLE_LOG();
/**
 * FreeRTOS 支持 (MG_ENABLE_FREERTOS)
 * 描述: 启用 FreeRTOS 实时操作系统支持
 * 建议值: 0（禁用）/ 1（启用，仅 FreeRTOS 平台）
 * 类型: BOOL
 */
bool 系统适配_config_MG_ENABLE_FREERTOS();
/**
 * epoll 支持 (MG_ENABLE_EPOLL)
 * 描述: 启用 Linux epoll IO 多路复用
 * 建议值: 0（禁用）/ 1（启用，仅 Linux 平台）
 * 类型: BOOL
 */
bool 系统适配_config_MG_ENABLE_EPOLL();

#ifdef __cplusplus
}
#endif

#endif /* MONGOOSE_PORTS_系统适配_H */
