// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: Mongoose IoT (mongoose)

/**
 * 自动生成于 BlessStar 配置端口 — C 头文件
 * 业务系统: Mongoose IoT (mongoose)
 * 领域: 缓冲区配置
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */

#ifndef MONGOOSE_PORTS_缓冲区配置_H
#define MONGOOSE_PORTS_缓冲区配置_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * 缓冲区配置 域配置接口
 * 通过 vtable + setter 模式注入具体实现
 * 业务代码通过外观函数访问配置，无需关心底层实现
 */

// 缓冲区配置Config — 函数指针表
typedef struct {
    int32_t (*MG_IO_SIZE)(void* impl_ctx);
    int64_t (*MG_MAX_RECV_SIZE)(void* impl_ctx);
} 缓冲区配置_config_vtable_t;

// 全局 setter — 由 adapter 层在初始化时调用
void 缓冲区配置_config_set_impl(const 缓冲区配置_config_vtable_t* vtable, void* impl_ctx);

// 业务代码调用的外观函数
/**
 * IO 缓冲粒度 (MG_IO_SIZE)
 * 描述: 发送/接收 IO 缓冲区的增长粒度（字节）
 * 建议值: 128~4096（字节），推荐步长128。MCU 建议 256~512，Linux 建议 512~2048
 * 类型: I32
 */
int32_t 缓冲区配置_config_MG_IO_SIZE();
/**
 * 最大接收缓冲 (MG_MAX_RECV_SIZE)
 * 描述: 最大接收 IO 缓冲区大小（字节，默认 3MB）
 * 建议值: MCU 平台 8192~65536（8KB~64KB），Linux 平台 1048576~16777216（1MB~16MB）
 * 类型: I64
 */
int64_t 缓冲区配置_config_MG_MAX_RECV_SIZE();

#ifdef __cplusplus
}
#endif

#endif /* MONGOOSE_PORTS_缓冲区配置_H */
