// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: Mongoose IoT (mongoose)

/**
 * 自动生成于 BlessStar 配置端口 — C 头文件
 * 业务系统: Mongoose IoT (mongoose)
 * 领域: 网络参数
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */

#ifndef MONGOOSE_PORTS_网络参数_H
#define MONGOOSE_PORTS_网络参数_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * 网络参数 域配置接口
 * 通过 vtable + setter 模式注入具体实现
 * 业务代码通过外观函数访问配置，无需关心底层实现
 */

// 网络参数Config — 函数指针表
typedef struct {
    int32_t (*MG_SOCK_LISTEN_BACKLOG_SIZE)(void* impl_ctx);
} 网络参数_config_vtable_t;

// 全局 setter — 由 adapter 层在初始化时调用
void 网络参数_config_set_impl(const 网络参数_config_vtable_t* vtable, void* impl_ctx);

// 业务代码调用的外观函数
/**
 * 监听背压队列 (MG_SOCK_LISTEN_BACKLOG_SIZE)
 * 描述: TCP listen 背压队列大小
 * 建议值: 16~512，推荐步长16。默认 128 适合多数场景
 * 类型: I32
 */
int32_t 网络参数_config_MG_SOCK_LISTEN_BACKLOG_SIZE();

#ifdef __cplusplus
}
#endif

#endif /* MONGOOSE_PORTS_网络参数_H */
