// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: Mongoose IoT (mongoose)

/**
 * 自动生成于 BlessStar 配置端口 — C 头文件
 * 业务系统: Mongoose IoT (mongoose)
 * 领域: 网络栈选择
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */

#ifndef MONGOOSE_PORTS_网络栈选择_H
#define MONGOOSE_PORTS_网络栈选择_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * 网络栈选择 域配置接口
 * 通过 vtable + setter 模式注入具体实现
 * 业务代码通过外观函数访问配置，无需关心底层实现
 */

// 网络栈选择Config — 函数指针表
typedef struct {
    bool (*MG_ENABLE_TCPIP)(void* impl_ctx);
    bool (*MG_ENABLE_LWIP)(void* impl_ctx);
} 网络栈选择_config_vtable_t;

// 全局 setter — 由 adapter 层在初始化时调用
void 网络栈选择_config_set_impl(const 网络栈选择_config_vtable_t* vtable, void* impl_ctx);

// 业务代码调用的外观函数
/**
 * 内置 TCP/IP (MG_ENABLE_TCPIP)
 * 描述: 启用 Mongoose 内置 TCP/IP 网络栈（无外部栈时使用）
 * 建议值: 0（禁用，使用外部栈）/ 1（启用内置栈）
 * 类型: BOOL
 */
bool 网络栈选择_config_MG_ENABLE_TCPIP();
/**
 * lwIP 支持 (MG_ENABLE_LWIP)
 * 描述: 启用 lwIP 网络栈支持（常见于 MCU/RTOS 场景）
 * 建议值: 0（禁用）/ 1（启用）
 * 类型: BOOL
 */
bool 网络栈选择_config_MG_ENABLE_LWIP();

#ifdef __cplusplus
}
#endif

#endif /* MONGOOSE_PORTS_网络栈选择_H */
