// Hand-written smoke test — validates generated provider works at runtime.
// This file is NOT generated by blessstar-codegen.
//
// Instantiates all adapters with a null reader, verifying the 3-tier fallback
// (ConfigReader → LastKnownGood → hardcoded defaults) does not throw when
// no real config source is available.

import com.douyinmall.provider.BlessstarProvider;
import com.douyinmall.ports.ConfigReader;

public class SmokeTest {
    public static void main(String[] args) {
        // With null reader, adapters fall through to hardcoded defaults
        BlessstarProvider.Adapters adapters = BlessstarProvider.provideAdapters(null);
        assert adapters != null : "provideAdapters(null) returned null";
        System.out.println("✅ BlessstarProvider: Adapters created with null reader");

        // Call one getter per domain — should not throw
        assert adapters.getProductConfig() != null;
        System.out.println("✅ ProductConfig OK");

        assert adapters.getCorsConfig() != null;
        System.out.println("✅ CorsConfig OK");

        assert adapters.getPaymentConfig() != null;
        System.out.println("✅ PaymentConfig OK");

        assert adapters.getUserConfig() != null;
        System.out.println("✅ UserConfig OK");

        assert adapters.getOrderConfig() != null;
        System.out.println("✅ OrderConfig OK");

        assert adapters.getAuthConfig() != null;
        System.out.println("✅ AuthConfig OK");

        assert adapters.getReviewConfig() != null;
        System.out.println("✅ ReviewConfig OK");

        System.out.println("🎉 All smoke tests passed!");
    }
}
