// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

// Package ports 自动生成于 BlessStar 配置端口-适配器
// 业务系统: 抖音商城 (douyin-mall)
// 领域: 评价管理
// 请勿手动修改 — 由 blessstar-codegen 自动生成
// Source: manifest.json

package ports

import (
	"context"
)

// ReviewConfig 评价管理 域配置接口
// 对应 domain: "评价管理"
// 禁止直接 import BlessStar SDK — 请通过此接口访问配置
type ReviewConfig interface {

	// // 评分下限 (review.rating.min)
// 描述: 商品评论评分的最低分值。
// 建议值: 1~5，推荐与max配合使用确保min<max
// 类型: I32
	// Returns: int32
	RatingMin(ctx context.Context) (int32, error)

	// // 评分上限 (review.rating.max)
// 描述: 商品评论评分的最高分值。
// 建议值: 1~10，推荐与min配合使用。当前为五星制(5)，如需更多粒度可改为10分制
// 类型: I32
	// Returns: int32
	RatingMax(ctx context.Context) (int32, error)
}
