#!/usr/bin/env python3
"""
Factory sync tool for BlessStar.
Performs incremental copy from local source cache to factory directory.
"""

import argparse
import hashlib
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path


def compute_file_hash(filepath: Path) -> str:
    h = hashlib.sha256()
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def sync_directory(source: Path, dest: Path, dry_run: bool = False) -> dict:
    results = {
        "copied": [],
        "skipped": [],
        "created": [],
        "errors": [],
    }

    if not source.exists():
        results["errors"].append(f"Source not found: {source}")
        return results

    if not dest.exists():
        if not dry_run:
            dest.mkdir(parents=True, exist_ok=True)
        results["created"].append(str(dest))

    for src_path in source.rglob("*"):
        rel_path = src_path.relative_to(source)
        dst_path = dest / rel_path

        if src_path.is_dir():
            if not dst_path.exists():
                if not dry_run:
                    dst_path.mkdir(parents=True, exist_ok=True)
                results["created"].append(str(dst_path))
            continue

        if dst_path.exists():
            src_hash = compute_file_hash(src_path)
            dst_hash = compute_file_hash(dst_path)
            if src_hash == dst_hash:
                results["skipped"].append(str(rel_path))
                continue

        if not dry_run:
            dst_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_path, dst_path)
        results["copied"].append(str(rel_path))

    return results


def update_manifest(factory_path: Path, source_version: str, cache_path: Path):
    manifest_path = factory_path / "manifest.yaml"
    stamp = datetime.now(timezone.utc).isoformat()
    manifest_content = f"""# BlessStar Factory Manifest
# Auto-generated by tools/factory/sync.py

source_version: {source_version}
source_cache_path: {cache_path}
sync_timestamp: {stamp}

kernel_files:
"""

    kernel_path = factory_path / "kernel"
    if kernel_path.exists():
        for filepath in sorted(kernel_path.rglob("*")):
            if filepath.is_file():
                rel_path = filepath.relative_to(factory_path)
                file_hash = compute_file_hash(filepath)
                manifest_content += f"  {rel_path}: {file_hash}\n"

    with open(manifest_path, "w") as f:
        f.write(manifest_content)


def main():
    parser = argparse.ArgumentParser(description="BlessStar Factory Sync")
    parser.add_argument("--source", required=True, help="Source directory")
    parser.add_argument("--dest", required=True, help="Destination directory")
    parser.add_argument("--version", required=True, help="Source version tag")
    parser.add_argument("--dry-run", action="store_true", help="Dry run mode")
    parser.add_argument("--update-manifest", action="store_true", help="Update manifest")
    args = parser.parse_args()

    source = Path(args.source)
    dest = Path(args.dest)
    version = args.version

    print(f"Syncing version {version}")
    print(f"   Source: {source}")
    print(f"   Dest:   {dest}")

    if args.dry_run:
        print("   [DRY RUN MODE]")

    results = sync_directory(source, dest, args.dry_run)

    print("\nSync Summary:")
    if results["created"]:
        print(f"   Created {len(results['created'])} directories")
    if results["copied"]:
        print(f"   Copied {len(results['copied'])} files")
    if results["skipped"]:
        print(f"   Skipped {len(results['skipped'])} unchanged files")
    if results["errors"]:
        print(f"   Errors: {len(results['errors'])}")
        for error in results["errors"]:
            print(f"      {error}")
        sys.exit(1)

    if args.update_manifest and not args.dry_run:
        print("\nUpdating manifest...")
        update_manifest(dest, version, source)
        print("   Manifest updated")

    print("\nSync completed successfully")


if __name__ == "__main__":
    main()
