# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package ports — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: API 配置
# 请勿手动修改 — 由 blessstar-codegen 自动生成
# Source: manifest.json

from typing import Protocol
from contextlib import AbstractContextManager


class API配置Config(Protocol):
    """API 配置域配置接口"""

    def API_V1_STR(self, ctx: AbstractContextManager) -> str:
        """API 前缀 (API_V1_STR)
        描述: API 版本前缀路径
        建议值: 推荐格式：/api/v{数字}，如 /api/v1、/api/v2
        类型: STR
        """
        ...

