# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package ports — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 认证鉴权
# 请勿手动修改 — 由 blessstar-codegen 自动生成
# Source: manifest.json

from typing import Protocol
from contextlib import AbstractContextManager


class AuthConfig(Protocol):
    """认证鉴权域配置接口"""

    def ACCESS_TOKEN_EXPIRE_MINUTES(self, ctx: AbstractContextManager) -> int:
        """Token 过期时间 (ACCESS_TOKEN_EXPIRE_MINUTES)
        描述: JWT 访问令牌过期时间（分钟），默认 8 天
        建议值: 60~43200（1小时~30天），推荐步长60分钟。生产建议 60~1440 分钟
        类型: I32
        """
        ...

