# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package ports — 提供业务系统的配置读取接口。
# 所有 Port 接口定义在此包中，业务代码仅依赖此包。
# 请勿手动修改 — 由 blessstar-codegen 自动生成

from typing import Protocol
from contextlib import AbstractContextManager


class ConfigReader(Protocol):
    """配置读取接口，业务方自行选择实现方式。

    内置实现包括：CachedReader（秒级轮询缓存）、EnvReader（环境变量）、FileReader（本地文件）等。

    实现类通过环境变量 BLESSSTAR_ENDPOINT 获取 Electron 地址（HTTPReader 场景）。
    初始化失败时不得阻塞进程，由 adapter 的三阶段降级兜底。

    get 返回任意类型以便 adapter 进行类型转换（与三阶段降级兼容）。
    常见返回类型：int, bool, str, list[str]。
    """

    def get(self, ctx: AbstractContextManager, path: str):
        """读取一个配置值。

        Args:
            ctx: 上下文管理器（业务上下文）。
            path: 配置的完整注册路径（如 "/config/full-stack-fastapi/auth/jwt/token_expiry_seconds"）。

        Returns:
            配置值（可直接用于类型转换）或抛出异常。
        """
        ...
