# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package ports — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 安全策略
# 请勿手动修改 — 由 blessstar-codegen 自动生成
# Source: manifest.json

from typing import Protocol
from contextlib import AbstractContextManager


class CorsConfig(Protocol):
    """安全策略域配置接口"""

    def BACKEND_CORS_ORIGINS(self, ctx: AbstractContextManager) -> list[str]:
        """跨域白名单 (BACKEND_CORS_ORIGINS)
        描述: CORS 跨域允许的前端来源域名列表
        建议值: 生产环境配置具体域名，格式：["https://dashboard.example.com"]
        类型: ARR
        """
        ...
    def FRONTEND_HOST(self, ctx: AbstractContextManager) -> str:
        """前端地址 (FRONTEND_HOST)
        描述: 前端应用主机地址，用于邮件中生成链接
        建议值: 合法的 URL 地址，如 http://localhost:5173 或 https://dashboard.example.com
        类型: STR
        """
        ...

