# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package ports — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 用户管理
# 请勿手动修改 — 由 blessstar-codegen 自动生成
# Source: manifest.json

from typing import Protocol
from contextlib import AbstractContextManager


class UserConfig(Protocol):
    """用户管理域配置接口"""

    def FIRST_SUPERUSER(self, ctx: AbstractContextManager) -> str:
        """初始管理员 (FIRST_SUPERUSER)
        描述: 初始超级管理员邮箱地址，首次启动时自动创建
        建议值: 合法的邮箱地址
        类型: STR
        """
        ...

