# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package ports — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 数据库配置
# 请勿手动修改 — 由 blessstar-codegen 自动生成
# Source: manifest.json

from typing import Protocol
from contextlib import AbstractContextManager


class 数据库配置Config(Protocol):
    """数据库配置域配置接口"""

    def POSTGRES_SERVER(self, ctx: AbstractContextManager) -> str:
        """数据库主机 (POSTGRES_SERVER)
        描述: PostgreSQL 数据库主机地址
        建议值: 合法的 IP 地址或域名
        类型: STR
        """
        ...
    def POSTGRES_PORT(self, ctx: AbstractContextManager) -> int:
        """数据库端口 (POSTGRES_PORT)
        描述: PostgreSQL 数据库端口
        建议值: 1024~65535。PostgreSQL 默认 5432
        类型: I32
        """
        ...
    def POSTGRES_DB(self, ctx: AbstractContextManager) -> str:
        """数据库名 (POSTGRES_DB)
        描述: PostgreSQL 数据库名称
        建议值: 合法的 PostgreSQL 数据库名称
        类型: STR
        """
        ...
    def POSTGRES_USER(self, ctx: AbstractContextManager) -> str:
        """数据库用户 (POSTGRES_USER)
        描述: PostgreSQL 数据库用户名
        建议值: PostgreSQL 数据库用户名
        类型: STR
        """
        ...

