# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package ports — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 环境配置
# 请勿手动修改 — 由 blessstar-codegen 自动生成
# Source: manifest.json

from typing import Protocol
from contextlib import AbstractContextManager


class 环境配置Config(Protocol):
    """环境配置域配置接口"""

    def ENVIRONMENT(self, ctx: AbstractContextManager) -> str:
        """部署环境 (ENVIRONMENT)
        描述: 部署环境标识：local/staging/production
        建议值: local / staging / production
        类型: ENUM
        """
        ...

