# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package ports — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 监控配置
# 请勿手动修改 — 由 blessstar-codegen 自动生成
# Source: manifest.json

from typing import Protocol
from contextlib import AbstractContextManager


class 监控配置Config(Protocol):
    """监控配置域配置接口"""

    def SENTRY_DSN(self, ctx: AbstractContextManager) -> str:
        """Sentry DSN (SENTRY_DSN)
        描述: Sentry 错误监控 DSN，为空则不启用 Sentry
        建议值: https://<key>@<org>.ingest.sentry.io/<project_id> 或空字符串
        类型: STR
        """
        ...

