# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package ports — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 通用配置
# 请勿手动修改 — 由 blessstar-codegen 自动生成
# Source: manifest.json

from typing import Protocol
from contextlib import AbstractContextManager


class 通用配置Config(Protocol):
    """通用配置域配置接口"""

    def PROJECT_NAME(self, ctx: AbstractContextManager) -> str:
        """项目名称 (PROJECT_NAME)
        描述: 项目名称，用于邮件发件人名称等展示
        建议值: 描述性的项目名称字符串
        类型: STR
        """
        ...

