# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package ports — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 邮件服务
# 请勿手动修改 — 由 blessstar-codegen 自动生成
# Source: manifest.json

from typing import Protocol
from contextlib import AbstractContextManager


class 邮件服务Config(Protocol):
    """邮件服务域配置接口"""

    def SMTP_HOST(self, ctx: AbstractContextManager) -> str:
        """SMTP 主机 (SMTP_HOST)
        描述: SMTP 邮件服务器主机地址
        建议值: 合法的 SMTP 服务器地址，如 smtp.gmail.com
        类型: STR
        """
        ...
    def SMTP_PORT(self, ctx: AbstractContextManager) -> int:
        """SMTP 端口 (SMTP_PORT)
        描述: SMTP 邮件服务器端口
        建议值: 587（TLS）、465（SSL）、25（明文，不推荐）
        类型: I32
        """
        ...
    def SMTP_TLS(self, ctx: AbstractContextManager) -> bool:
        """SMTP TLS (SMTP_TLS)
        描述: SMTP 是否启用 TLS 加密
        建议值: true（TLS）/ false（非 TLS 或不使用）
        类型: BOOL
        """
        ...
    def EMAILS_FROM_EMAIL(self, ctx: AbstractContextManager) -> str:
        """发件地址 (EMAILS_FROM_EMAIL)
        描述: 邮件发送者地址
        建议值: 合法的邮箱地址，如 noreply@example.com
        类型: STR
        """
        ...
    def EMAIL_RESET_TOKEN_EXPIRE_HOURS(self, ctx: AbstractContextManager) -> int:
        """重置令牌过期 (EMAIL_RESET_TOKEN_EXPIRE_HOURS)
        描述: 密码重置令牌过期时间（小时）
        建议值: 1~72（小时），推荐步长1。建议 24~48 小时
        类型: I32
        """
        ...

