// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.provider;

import com.musicwebsite.ports.ConfigReader;
import com.musicwebsite.ports.CorsConfig;
import com.musicwebsite.ports.密码重置Config;
import com.musicwebsite.ports.对象存储配置Config;
import com.musicwebsite.ports.数据库配置Config;
import com.musicwebsite.ports.文件上传配置Config;
import com.musicwebsite.ports.服务器配置Config;
import com.musicwebsite.ports.登录安全Config;
import com.musicwebsite.ports.缓存配置Config;

/**
 * BlessStar 配置依赖注入。
 * 业务系统: 音乐网站 (music-website)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class BlessstarProvider {

	/**
	 * 持有所有域的配置适配器。
	 */
	public static class Adapters {
		private final CorsConfig corsConfig;
		private final 密码重置Config ��码重置Config;
		private final 对象存储配置Config ��象存储配置Config;
		private final 数据库配置Config ��据库配置Config;
		private final 文件上传配置Config ��件上传配置Config;
		private final 服务器配置Config ��务器配置Config;
		private final 登录安全Config ��录安全Config;
		private final 缓存配置Config ��存配置Config;

		public Adapters(
			CorsConfig corsConfig
			, 密码重置Config ��码重置Config
			, 对象存储配置Config ��象存储配置Config
			, 数据库配置Config ��据库配置Config
			, 文件上传配置Config ��件上传配置Config
			, 服务器配置Config ��务器配置Config
			, 登录安全Config ��录安全Config
			, 缓存配置Config ��存配置Config
		) {
			this.corsConfig = corsConfig;
			this.��码重置Config = ��码重置Config;
			this.��象存储配置Config = ��象存储配置Config;
			this.��据库配置Config = ��据库配置Config;
			this.��件上传配置Config = ��件上传配置Config;
			this.��务器配置Config = ��务器配置Config;
			this.��录安全Config = ��录安全Config;
			this.��存配置Config = ��存配置Config;
		}

		public CorsConfig getCorsConfig() {
			return corsConfig;
		}
		public 密码重置Config get密码重置Config() {
			return ��码重置Config;
		}
		public 对象存储配置Config get对象存储配置Config() {
			return ��象存储配置Config;
		}
		public 数据库配置Config get数据库配置Config() {
			return ��据库配置Config;
		}
		public 文件上传配置Config get文件上传配置Config() {
			return ��件上传配置Config;
		}
		public 服务器配置Config get服务器配置Config() {
			return ��务器配置Config;
		}
		public 登录安全Config get登录安全Config() {
			return ��录安全Config;
		}
		public 缓存配置Config get缓存配置Config() {
			return ��存配置Config;
		}
	}

	/**
	 * 一行实例化所有域配置适配器。
	 * @param reader ConfigReader 实现（如 CachedReader、HTTPReader）
	 * @return 包含所有域 Adapter 的 Adapters 实例
	 */
	public static Adapters provideAdapters(ConfigReader reader) {
		return new Adapters(
			new com.musicwebsite.adapter.blessstar.CorsConfigAdapter(reader)
			, new com.musicwebsite.adapter.blessstar.密码重置ConfigAdapter(reader)
			, new com.musicwebsite.adapter.blessstar.对象存储配置ConfigAdapter(reader)
			, new com.musicwebsite.adapter.blessstar.数据库配置ConfigAdapter(reader)
			, new com.musicwebsite.adapter.blessstar.文件上传配置ConfigAdapter(reader)
			, new com.musicwebsite.adapter.blessstar.服务器配置ConfigAdapter(reader)
			, new com.musicwebsite.adapter.blessstar.登录安全ConfigAdapter(reader)
			, new com.musicwebsite.adapter.blessstar.缓存配置ConfigAdapter(reader)
		);
	}
}
