// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.provider;

import java.util.Map;
import java.util.concurrent.*;
import java.util.function.Function;

import com.musicwebsite.ports.ConfigReader;

/**
 * 对 ConfigReader 的缓存包装器（可选装饰器）。
 * 后台线程使用 ScheduledExecutorService 定时刷新缓存，实现秒级准实时热更新。
 * 不依赖任何外部库，仅使用 JDK 标准库。
 *
 * 使用方式（由 main 注入）：
 * <pre>
 *     ConfigReader rawReader = new HttpReader();  // 从环境变量 BLESSSTAR_ENDPOINT 读取地址
 *     CachedReader cachedReader = new CachedReader(rawReader, 30, TimeUnit.SECONDS);
 *     Adapters adapters = BlessstarProvider.provideAdapters(cachedReader);
 * </pre>
 */
public class CachedReader implements ConfigReader {
    private final ConfigReader inner;
    private final Map<String, Object> cache = new ConcurrentHashMap<>();
    private final ScheduledExecutorService scheduler = Executors.newSingleThreadScheduledExecutor();
    private Runnable refreshFunc = () -> {};

    /**
     * 创建 CachedReader 实例。
     * @param inner     底层 ConfigReader 实现
     * @param interval  缓存刷新周期
     * @param unit      时间单位
     */
    public CachedReader(ConfigReader inner, long interval, TimeUnit unit) {
        this.inner = inner;
        scheduler.scheduleAtFixedRate(this::refreshLoop, interval, interval, unit);
    }

    /**
     * 设置全量刷新回调函数，由业务方自定义需要缓存的配置路径。
     * @param fn 刷新回调
     * @return 当前 CachedReader 实例
     */
    public CachedReader withRefreshFunc(Runnable fn) {
        this.refreshFunc = fn;
        return this;
    }

    @Override
    public Object get(String path) {
        Object val = cache.get(path);
        if (val != null) {
            return val;
        }
        return inner.get(path);
    }

    private void refreshLoop() {
        try {
            refreshFunc.run();
        } catch (Exception e) {
            // 刷新失败不影响现有缓存，仅跳过本轮
        }
    }

    /**
     * 停止后台刷新线程。
     */
    public void shutdown() {
        scheduler.shutdown();
    }
}
