/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Parse a BlessStar schema JSON into UIDL JSON, grouped by domain. */
export declare function schemaToUidl(schemaJson: string): string
/**
 * 获取已注册的 Schema JSON 字符串。
 * 内部调用 bs_config_declare_get_schema_json() C ABI。
 * 返回的 JSON 包含所有已注册字段的 key、type、default、description。
 * 如果尚无 Schema 注册，返回错误。
 */
export declare function getRegisteredSchemaJson(): string
/**
 * 从 BlessStar 运行时值存储读取单个配置值。
 * 内部调用 bs_config_read() C ABI，返回字符串值。
 * 如果 key 不存在或值为空，返回 None。
 */
export declare function readBlessStarConfig(key: string): string | null
/**
 * 写入单个配置值到 BlessStar 运行时值存储。
 * 内部调用 bs_config_write() C ABI。
 * key 必须已通过 register_schema_field_ffi() 声明，否则返回错误。
 */
export declare function writeBlessStarConfig(key: string, value: string): void
/* ══════════════════════════════════════════════════════════════════
 * Editor Bridge FFI — Normalizer Plugin
 * ══════════════════════════════════════════════════════════════════ */

/** normalizer_normalize_ffi — 通过 NormalizerRegistry 调用已注册的归一化器 */
export declare function normalizerNormalizeFfi(vendorId: string, inputJson: string, extraJson?: string): string | null

/** app_session_create_ffi — 创建 AppSession，返回 opaque handle */
export declare function appSessionCreateFfi(manifestPath?: string): number | null

/** app_session_destroy_ffi — 销毁 AppSession */
export declare function appSessionDestroyFfi(handle: number): void

/** app_session_get_ctx_ffi — 获取 AttachContext* handle */
export declare function appSessionGetCtxFfi(handle: number): number

/** app_session_is_ok_ffi — 检查 AppSession 是否就绪 */
export declare function appSessionIsOkFfi(handle: number): boolean

/** config_commit_batch_ffi — 批量提交配置变更，返回 Report JSON */
export declare function configCommitBatchFfi(ctxHandle: number, entriesJson: string): string | null

/** agent_index_export_ffi — 导出 Agent 索引文件到指定目录 */
export declare function agentIndexExportFfi(schemaJson: string, outputDir: string, businessName: string): boolean

/** register_schema_field_ffi — 专题五 A4: 注册单个 Schema 字段（真实 C ABI） */
export declare function registerSchemaFieldFfi(key: string, fieldType: number, defaultStr?: string, description?: string, required?: boolean): void

/* ══════════════════════════════════════════════════════════════════
 * 专题十二：单文件持久化存储 FFI
 * ══════════════════════════════════════════════════════════════════ */

/** config_persist_write_ffi — 持久化写入：将 runtime_values 写入 configs.json */
export declare function configPersistWriteFfi(manifestPath: string): boolean

/** config_persist_load_ffi — 持久化加载：从 configs.json 读取并加载到 runtime_values */
export declare function configPersistLoadFfi(manifestPath: string): boolean
