// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.adapter.mock;

import com.musicwebsite.ports.CorsConfig;

/**
 * 安全策略域配置的 Mock 实现（单元测试用）
 * 业务系统: 音乐网站 (music-website)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class CorsConfigMock implements CorsConfig {

	private java.util.List<String> etAllowed-origins = java.util.List.of("http://localhost:3000", "http://127.0.0.1:3000", "http://localhost:8080", "http://127.0.0.1:8080", "http://localhost:8081", "http://127.0.0.1:8081");

	/**
	 * 创建默认 Mock（返回值按 manifest 默认值设定）
	 */
	public CorsConfigMock() {
	}

	/**
	 * 创建默认 Mock 实例
	 */
	public static CorsConfigMock create() {
		return new CorsConfigMock();
	}

	/**
	 * 设置 跨域白名单
	 * @param value 跨域白名单 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public CorsConfigMock withAllowed-origins(java.util.List<String> value) {
		this.etAllowed-origins = value;
		return this;
	}

	@Override
	public java.util.List<String> getAllowed-origins() throws Exception {
		return this.etAllowed-origins;
	}

}
