// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.adapter.mock;

import com.musicwebsite.ports.密码重置Config;

/**
 * 密码重置域配置的 Mock 实现（单元测试用）
 * 业务系统: 音乐网站 (music-website)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class 密码重置ConfigMock implements 密码重置Config {

	private int etCode-ttl-minutes = 10;
	private int etSend-cooldown-seconds = 15;
	private boolean etMock-without-mail = true;

	/**
	 * 创建默认 Mock（返回值按 manifest 默认值设定）
	 */
	public 密码重置ConfigMock() {
	}

	/**
	 * 创建默认 Mock 实例
	 */
	public static 密码重置ConfigMock create() {
		return new 密码重置ConfigMock();
	}

	/**
	 * 设置 验证码有效期
	 * @param value 验证码有效期 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public 密码重置ConfigMock withCode-ttl-minutes(int value) {
		this.etCode-ttl-minutes = value;
		return this;
	}

	/**
	 * 设置 发送冷却
	 * @param value 发送冷却 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public 密码重置ConfigMock withSend-cooldown-seconds(int value) {
		this.etSend-cooldown-seconds = value;
		return this;
	}

	/**
	 * 设置 Mock 模式
	 * @param value Mock 模式 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public 密码重置ConfigMock withMock-without-mail(boolean value) {
		this.etMock-without-mail = value;
		return this;
	}

	@Override
	public int getCode-ttl-minutes() throws Exception {
		return this.etCode-ttl-minutes;
	}

	@Override
	public int getSend-cooldown-seconds() throws Exception {
		return this.etSend-cooldown-seconds;
	}

	@Override
	public boolean getMock-without-mail() throws Exception {
		return this.etMock-without-mail;
	}

}
