// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.adapter.mock;

import com.musicwebsite.ports.对象存储配置Config;

/**
 * 对象存储配置域配置的 Mock 实现（单元测试用）
 * 业务系统: 音乐网站 (music-website)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class 对象存储配置ConfigMock implements 对象存储配置Config {

	private String etEndpoint = "http://localhost:9000";
	private String etBucket-name = "user01";

	/**
	 * 创建默认 Mock（返回值按 manifest 默认值设定）
	 */
	public 对象存储配置ConfigMock() {
	}

	/**
	 * 创建默认 Mock 实例
	 */
	public static 对象存储配置ConfigMock create() {
		return new 对象存储配置ConfigMock();
	}

	/**
	 * 设置 MinIO 端点
	 * @param value MinIO 端点 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public 对象存储配置ConfigMock withEndpoint(String value) {
		this.etEndpoint = value;
		return this;
	}

	/**
	 * 设置 MinIO 桶名
	 * @param value MinIO 桶名 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public 对象存储配置ConfigMock withBucket-name(String value) {
		this.etBucket-name = value;
		return this;
	}

	@Override
	public String getEndpoint() throws Exception {
		return this.etEndpoint;
	}

	@Override
	public String getBucket-name() throws Exception {
		return this.etBucket-name;
	}

}
