// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.adapter.mock;

import com.musicwebsite.ports.数据库配置Config;

/**
 * 数据库配置域配置的 Mock 实现（单元测试用）
 * 业务系统: 音乐网站 (music-website)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class 数据库配置ConfigMock implements 数据库配置Config {

	private String etDatasourceUrl = "jdbc:mysql://localhost:3306/yin_music?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8";

	/**
	 * 创建默认 Mock（返回值按 manifest 默认值设定）
	 */
	public 数据库配置ConfigMock() {
	}

	/**
	 * 创建默认 Mock 实例
	 */
	public static 数据库配置ConfigMock create() {
		return new 数据库配置ConfigMock();
	}

	/**
	 * 设置 数据库连接
	 * @param value 数据库连接 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public 数据库配置ConfigMock withDatasourceUrl(String value) {
		this.etDatasourceUrl = value;
		return this;
	}

	@Override
	public String getDatasourceUrl() throws Exception {
		return this.etDatasourceUrl;
	}

}
