// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.adapter.mock;

import com.musicwebsite.ports.文件上传配置Config;

/**
 * 文件上传配置域配置的 Mock 实现（单元测试用）
 * 业务系统: 音乐网站 (music-website)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class 文件上传配置ConfigMock implements 文件上传配置Config {

	private String etMax-file-size = "50MB";

	/**
	 * 创建默认 Mock（返回值按 manifest 默认值设定）
	 */
	public 文件上传配置ConfigMock() {
	}

	/**
	 * 创建默认 Mock 实例
	 */
	public static 文件上传配置ConfigMock create() {
		return new 文件上传配置ConfigMock();
	}

	/**
	 * 设置 上传大小限制
	 * @param value 上传大小限制 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public 文件上传配置ConfigMock withMax-file-size(String value) {
		this.etMax-file-size = value;
		return this;
	}

	@Override
	public String getMax-file-size() throws Exception {
		return this.etMax-file-size;
	}

}
