// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.adapter.mock;

import com.musicwebsite.ports.服务器配置Config;

/**
 * 服务器配置域配置的 Mock 实现（单元测试用）
 * 业务系统: 音乐网站 (music-website)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class 服务器配置ConfigMock implements 服务器配置Config {

	private int etPort = 8888;

	/**
	 * 创建默认 Mock（返回值按 manifest 默认值设定）
	 */
	public 服务器配置ConfigMock() {
	}

	/**
	 * 创建默认 Mock 实例
	 */
	public static 服务器配置ConfigMock create() {
		return new 服务器配置ConfigMock();
	}

	/**
	 * 设置 服务器端口
	 * @param value 服务器端口 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public 服务器配置ConfigMock withPort(int value) {
		this.etPort = value;
		return this;
	}

	@Override
	public int getPort() throws Exception {
		return this.etPort;
	}

}
