// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.adapter.mock;

import com.musicwebsite.ports.登录安全Config;

/**
 * 登录安全域配置的 Mock 实现（单元测试用）
 * 业务系统: 音乐网站 (music-website)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class 登录安全ConfigMock implements 登录安全Config {

	private int etMax-failed-attempts = 5;
	private int etLock-minutes = 10;

	/**
	 * 创建默认 Mock（返回值按 manifest 默认值设定）
	 */
	public 登录安全ConfigMock() {
	}

	/**
	 * 创建默认 Mock 实例
	 */
	public static 登录安全ConfigMock create() {
		return new 登录安全ConfigMock();
	}

	/**
	 * 设置 登录失败阈值
	 * @param value 登录失败阈值 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public 登录安全ConfigMock withMax-failed-attempts(int value) {
		this.etMax-failed-attempts = value;
		return this;
	}

	/**
	 * 设置 锁定时间
	 * @param value 锁定时间 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public 登录安全ConfigMock withLock-minutes(int value) {
		this.etLock-minutes = value;
		return this;
	}

	@Override
	public int getMax-failed-attempts() throws Exception {
		return this.etMax-failed-attempts;
	}

	@Override
	public int getLock-minutes() throws Exception {
		return this.etLock-minutes;
	}

}
