// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.adapter.mock;

import com.musicwebsite.ports.缓存配置Config;

/**
 * 缓存配置域配置的 Mock 实现（单元测试用）
 * 业务系统: 音乐网站 (music-website)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class 缓存配置ConfigMock implements 缓存配置Config {

	private String etRedisHost = "127.0.0.1";
	private int etRedisPort = 6379;
	private long etRedisTimeout = 1800000L;

	/**
	 * 创建默认 Mock（返回值按 manifest 默认值设定）
	 */
	public 缓存配置ConfigMock() {
	}

	/**
	 * 创建默认 Mock 实例
	 */
	public static 缓存配置ConfigMock create() {
		return new 缓存配置ConfigMock();
	}

	/**
	 * 设置 Redis 主机
	 * @param value Redis 主机 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public 缓存配置ConfigMock withRedisHost(String value) {
		this.etRedisHost = value;
		return this;
	}

	/**
	 * 设置 Redis 端口
	 * @param value Redis 端口 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public 缓存配置ConfigMock withRedisPort(int value) {
		this.etRedisPort = value;
		return this;
	}

	/**
	 * 设置 Redis 超时
	 * @param value Redis 超时 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public 缓存配置ConfigMock withRedisTimeout(long value) {
		this.etRedisTimeout = value;
		return this;
	}

	@Override
	public String getRedisHost() throws Exception {
		return this.etRedisHost;
	}

	@Override
	public int getRedisPort() throws Exception {
		return this.etRedisPort;
	}

	@Override
	public long getRedisTimeout() throws Exception {
		return this.etRedisTimeout;
	}

}
