// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: config-schema.yaml
// Business System: livedesign (livedesign)

// Package provider 自动生成于 BlessStar 配置依赖注入
// 业务系统: livedesign (livedesign)
// 请勿手动修改 — 由 blessstar-codegen 自动生成

import { ConfigReader } from '../ports/config-reader';
import { LiveDesignConfig } from '../ports/livedesign';
import { LiveDesignConfigAdapter } from '../adapters/blessstar/livedesign-adapter';

/**
 * Adapters 持有所有域的配置适配器
 */
export class Adapters {
  readonly liveDesignConfig: LiveDesignConfig;

  constructor(reader: ConfigReader) {
    this.liveDesignConfig = new LiveDesignConfigAdapter(reader);
  }
}

/**
 * provideBlessStarAdapters 一行实例化所有域配置适配器
 * 注入 ConfigReader 后返回所有域的 Port 实现
 * reader 由业务方提供（可为 CachedReader、HTTPReader、EnvReader 等实现）
 */
export function provideBlessStarAdapters(reader: ConfigReader): Adapters {
  return new Adapters(reader);
}
