# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package full_stack_fastapi — 自动生成于 BlessStar 配置依赖注入
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 请勿手动修改 — 由 blessstar-codegen 自动生成

from dataclasses import dataclass
from ports.config_reader import ConfigReader
from adapters import blessstar as adapter_blessstar
from ports.api配置 import API配置Config
from ports.cors import CorsConfig
from ports.数据库配置 import 数据库配置Config
from ports.环境配置 import 环境配置Config
from ports.user import UserConfig
from ports.监控配置 import 监控配置Config
from ports.auth import AuthConfig
from ports.通用配置 import 通用配置Config
from ports.邮件服务 import 邮件服务Config


@dataclass
class Adapters:
    """持有所有域的配置适配器"""
    a_p_i配置_config: API配置Config
    cors_config: CorsConfig
    数据库配置_config: 数据库配置Config
    环境配置_config: 环境配置Config
    user_config: UserConfig
    监控配置_config: 监控配置Config
    auth_config: AuthConfig
    通用配置_config: 通用配置Config
    邮件服务_config: 邮件服务Config

def provide_blessstar_adapters(reader: ConfigReader) -> Adapters:
    """一行实例化所有域配置适配器

    注入 ConfigReader 后返回所有域的 Port 实现
    reader 由业务方提供（可为 CachedReader、HTTPReader、EnvReader 等实现）
    """
    return Adapters(
        a_p_i配置_config=adapter_blessstar.API配置ConfigAdapter(reader),
        cors_config=adapter_blessstar.CorsConfigAdapter(reader),
        数据库配置_config=adapter_blessstar.数据库配置ConfigAdapter(reader),
        环境配置_config=adapter_blessstar.环境配置ConfigAdapter(reader),
        user_config=adapter_blessstar.UserConfigAdapter(reader),
        监控配置_config=adapter_blessstar.监控配置ConfigAdapter(reader),
        auth_config=adapter_blessstar.AuthConfigAdapter(reader),
        通用配置_config=adapter_blessstar.通用配置ConfigAdapter(reader),
        邮件服务_config=adapter_blessstar.邮件服务ConfigAdapter(reader),
    )
