# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package full-stack-fastapi — 提供 BlessStar 配置的依赖注入和可选装饰器。
# 请勿手动修改 — 由 blessstar-codegen 自动生成

import threading
import time
from typing import Any, Dict
from contextlib import AbstractContextManager
from ports.config_reader import ConfigReader


class CachedReader:
    """对 ConfigReader 的缓存包装器（可选装饰器）。

    后台线程定时刷新缓存，实现秒级准实时热更新。
    不依赖任何外部库，仅使用 Python 标准库。

    使用方式（由 main 入口注入）:

        raw_reader = HttpReader()                           # 从环境变量 BLESSSTAR_ENDPOINT 读取地址
        cached_reader = CachedReader(raw_reader, interval=30)
        adapters = provide_blessstar_adapters(cached_reader)
    """

    def __init__(self, inner: ConfigReader, interval: float = 30.0) -> None:
        """创建 CachedReader 实例。

        Args:
            inner: 底层 ConfigReader 实现。
            interval: 缓存刷新周期（秒），默认 30 秒。
        """
        self._inner = inner
        self._cache: Dict[str, Any] = {}
        self._interval = interval
        self._refresh_func = lambda ctx: None  # type: ignore
        self._stop_event = threading.Event()
        self._thread = threading.Thread(target=self._refresh_loop, daemon=True)
        self._thread.start()

    def set_refresh_func(self, fn) -> "CachedReader":
        """设置全量刷新回调函数，由业务方自定义需要缓存的配置路径。"""
        self._refresh_func = fn
        return self

    def get(self, ctx: AbstractContextManager, path: str):
        """从缓存中读取配置值。若缓存命中直接返回，否则穿透到底层 ConfigReader。"""
        if path in self._cache:
            return self._cache[path]
        return self._inner.get(ctx, path)

    def _refresh_loop(self) -> None:
        """后台线程，定时执行全量刷新。"""
        while not self._stop_event.is_set():
            time.sleep(self._interval)
            try:
                self._refresh_func(None)
            except Exception:
                # 刷新失败不影响现有缓存，仅跳过本轮
                pass

    def close(self) -> None:
        """停止后台刷新线程。"""
        self._stop_event.set()
        self._thread.join(timeout=5)
