# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package adapter_mock — 自动生成于 BlessStar 配置 Mock
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 认证鉴权
# 专为单元测试设计 — 固定返回值

from typing import Callable
from contextlib import AbstractContextManager
from ports.auth import AuthConfig


class AuthConfigMock(AuthConfig):
    """认证鉴权域配置的 Mock 实现（单元测试用）"""

    def __init__(self) -> None:
        self.ACCESS_TOKEN_EXPIRE_MINUTES_func: Callable[[AbstractContextManager], int] = lambda ctx: 11520

    @classmethod
    def create_default(cls) -> AuthConfig:
        """创建默认 Mock 实例（返回值按 manifest 默认值设定）"""
        return cls()

    def ACCESS_TOKEN_EXPIRE_MINUTES(self, ctx: AbstractContextManager) -> int:
        return self.ACCESS_TOKEN_EXPIRE_MINUTES_func(ctx)

