# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package adapter_mock — 自动生成于 BlessStar 配置 Mock
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 安全策略
# 专为单元测试设计 — 固定返回值

from typing import Callable
from contextlib import AbstractContextManager
from ports.cors import CorsConfig


class CorsConfigMock(CorsConfig):
    """安全策略域配置的 Mock 实现（单元测试用）"""

    def __init__(self) -> None:
        self.BACKEND_CORS_ORIGINS_func: Callable[[AbstractContextManager], list[str]] = lambda ctx: ["http://localhost", "http://localhost:5173", "https://localhost", "https://localhost:5173", "http://localhost.tiangolo.com"]
        self.FRONTEND_HOST_func: Callable[[AbstractContextManager], str] = lambda ctx: "http://localhost:5173"

    @classmethod
    def create_default(cls) -> CorsConfig:
        """创建默认 Mock 实例（返回值按 manifest 默认值设定）"""
        return cls()

    def BACKEND_CORS_ORIGINS(self, ctx: AbstractContextManager) -> list[str]:
        return self.BACKEND_CORS_ORIGINS_func(ctx)

    def FRONTEND_HOST(self, ctx: AbstractContextManager) -> str:
        return self.FRONTEND_HOST_func(ctx)

