# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package adapter_mock — 自动生成于 BlessStar 配置 Mock
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 数据库配置
# 专为单元测试设计 — 固定返回值

from typing import Callable
from contextlib import AbstractContextManager
from ports.数据库配置 import 数据库配置Config


class 数据库配置ConfigMock(数据库配置Config):
    """数据库配置域配置的 Mock 实现（单元测试用）"""

    def __init__(self) -> None:
        self.POSTGRES_SERVER_func: Callable[[AbstractContextManager], str] = lambda ctx: "localhost"
        self.POSTGRES_PORT_func: Callable[[AbstractContextManager], int] = lambda ctx: 5432
        self.POSTGRES_DB_func: Callable[[AbstractContextManager], str] = lambda ctx: "app"
        self.POSTGRES_USER_func: Callable[[AbstractContextManager], str] = lambda ctx: "postgres"

    @classmethod
    def create_default(cls) -> 数据库配置Config:
        """创建默认 Mock 实例（返回值按 manifest 默认值设定）"""
        return cls()

    def POSTGRES_SERVER(self, ctx: AbstractContextManager) -> str:
        return self.POSTGRES_SERVER_func(ctx)

    def POSTGRES_PORT(self, ctx: AbstractContextManager) -> int:
        return self.POSTGRES_PORT_func(ctx)

    def POSTGRES_DB(self, ctx: AbstractContextManager) -> str:
        return self.POSTGRES_DB_func(ctx)

    def POSTGRES_USER(self, ctx: AbstractContextManager) -> str:
        return self.POSTGRES_USER_func(ctx)

