# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package adapter_mock — 自动生成于 BlessStar 配置 Mock
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 环境配置
# 专为单元测试设计 — 固定返回值

from typing import Callable
from contextlib import AbstractContextManager
from ports.环境配置 import 环境配置Config


class 环境配置ConfigMock(环境配置Config):
    """环境配置域配置的 Mock 实现（单元测试用）"""

    def __init__(self) -> None:
        self.ENVIRONMENT_func: Callable[[AbstractContextManager], str] = lambda ctx: "local"

    @classmethod
    def create_default(cls) -> 环境配置Config:
        """创建默认 Mock 实例（返回值按 manifest 默认值设定）"""
        return cls()

    def ENVIRONMENT(self, ctx: AbstractContextManager) -> str:
        return self.ENVIRONMENT_func(ctx)

