# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package adapter_mock — 自动生成于 BlessStar 配置 Mock
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 邮件服务
# 专为单元测试设计 — 固定返回值

from typing import Callable
from contextlib import AbstractContextManager
from ports.邮件服务 import 邮件服务Config


class 邮件服务ConfigMock(邮件服务Config):
    """邮件服务域配置的 Mock 实现（单元测试用）"""

    def __init__(self) -> None:
        self.SMTP_HOST_func: Callable[[AbstractContextManager], str] = lambda ctx: "\"\""
        self.SMTP_PORT_func: Callable[[AbstractContextManager], int] = lambda ctx: 587
        self.SMTP_TLS_func: Callable[[AbstractContextManager], bool] = lambda ctx: True
        self.EMAILS_FROM_EMAIL_func: Callable[[AbstractContextManager], str] = lambda ctx: "info@example.com"
        self.EMAIL_RESET_TOKEN_EXPIRE_HOURS_func: Callable[[AbstractContextManager], int] = lambda ctx: 48

    @classmethod
    def create_default(cls) -> 邮件服务Config:
        """创建默认 Mock 实例（返回值按 manifest 默认值设定）"""
        return cls()

    def SMTP_HOST(self, ctx: AbstractContextManager) -> str:
        return self.SMTP_HOST_func(ctx)

    def SMTP_PORT(self, ctx: AbstractContextManager) -> int:
        return self.SMTP_PORT_func(ctx)

    def SMTP_TLS(self, ctx: AbstractContextManager) -> bool:
        return self.SMTP_TLS_func(ctx)

    def EMAILS_FROM_EMAIL(self, ctx: AbstractContextManager) -> str:
        return self.EMAILS_FROM_EMAIL_func(ctx)

    def EMAIL_RESET_TOKEN_EXPIRE_HOURS(self, ctx: AbstractContextManager) -> int:
        return self.EMAIL_RESET_TOKEN_EXPIRE_HOURS_func(ctx)

