// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: Mongoose IoT (mongoose)

/**
 * 自动生成于 BlessStar 配置 Mock — C 实现
 * 业务系统: Mongoose IoT (mongoose)
 * 领域: 协议功能
 * 专为单元测试设计 — 固定返回值
 */

#include "协议功能.h"
#include <stdlib.h>

// Mock: 最大 HTTP 头数
static int32_t mock_MG_MAX_HTTP_HEADERS(void* impl_ctx) {
    (void)impl_ctx;
    return 30;
}

// Mock: IPv6 支持
static bool mock_MG_ENABLE_IPV6(void* impl_ctx) {
    (void)impl_ctx;
    return false;
}

// Mock: MD5 支持
static bool mock_MG_ENABLE_MD5(void* impl_ctx) {
    (void)impl_ctx;
    return true;
}

// Mock: HTTP 目录列表
static bool mock_MG_ENABLE_DIRLIST(void* impl_ctx) {
    (void)impl_ctx;
    return false;
}

// Mock: ChaCha20 加密
static bool mock_MG_ENABLE_CHACHA20(void* impl_ctx) {
    (void)impl_ctx;
    return true;
}

// Mock vtable 实例 — 返回固定值
static const 协议功能_config_vtable_t g_协议功能_mock_vtable = {
    .MG_MAX_HTTP_HEADERS = mock_MG_MAX_HTTP_HEADERS,
    .MG_ENABLE_IPV6 = mock_MG_ENABLE_IPV6,
    .MG_ENABLE_MD5 = mock_MG_ENABLE_MD5,
    .MG_ENABLE_DIRLIST = mock_MG_ENABLE_DIRLIST,
    .MG_ENABLE_CHACHA20 = mock_MG_ENABLE_CHACHA20,
};

// 协议功能_mock_init 初始化 Mock 适配器
// 将全局 vtable 设置为 Mock 实现，业务代码随后调用外观函数即可获得固定值
void 协议功能_mock_init(void) {
    协议功能_config_set_impl(&g_协议功能_mock_vtable, NULL);
}
