// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: Mongoose IoT (mongoose)

/**
 * 自动生成于 BlessStar 配置 Mock — C 实现
 * 业务系统: Mongoose IoT (mongoose)
 * 领域: 存储适配
 * 专为单元测试设计 — 固定返回值
 */

#include "存储适配.h"
#include <stdlib.h>

// Mock: FATFS 支持
static bool mock_MG_ENABLE_FATFS(void* impl_ctx) {
    (void)impl_ctx;
    return false;
}

// Mock: LittleFS 支持
static bool mock_MG_ENABLE_LFS(void* impl_ctx) {
    (void)impl_ctx;
    return false;
}

// Mock vtable 实例 — 返回固定值
static const 存储适配_config_vtable_t g_存储适配_mock_vtable = {
    .MG_ENABLE_FATFS = mock_MG_ENABLE_FATFS,
    .MG_ENABLE_LFS = mock_MG_ENABLE_LFS,
};

// 存储适配_mock_init 初始化 Mock 适配器
// 将全局 vtable 设置为 Mock 实现，业务代码随后调用外观函数即可获得固定值
void 存储适配_mock_init(void) {
    存储适配_config_set_impl(&g_存储适配_mock_vtable, NULL);
}
