// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: Mongoose IoT (mongoose)

/**
 * 自动生成于 BlessStar 配置 Mock — C 实现
 * 业务系统: Mongoose IoT (mongoose)
 * 领域: 缓冲区配置
 * 专为单元测试设计 — 固定返回值
 */

#include "缓冲区配置.h"
#include <stdlib.h>

// Mock: IO 缓冲粒度
static int32_t mock_MG_IO_SIZE(void* impl_ctx) {
    (void)impl_ctx;
    return 512;
}

// Mock: 最大接收缓冲
static int64_t mock_MG_MAX_RECV_SIZE(void* impl_ctx) {
    (void)impl_ctx;
    return 3145728;
}

// Mock vtable 实例 — 返回固定值
static const 缓冲区配置_config_vtable_t g_缓冲区配置_mock_vtable = {
    .MG_IO_SIZE = mock_MG_IO_SIZE,
    .MG_MAX_RECV_SIZE = mock_MG_MAX_RECV_SIZE,
};

// 缓冲区配置_mock_init 初始化 Mock 适配器
// 将全局 vtable 设置为 Mock 实现，业务代码随后调用外观函数即可获得固定值
void 缓冲区配置_mock_init(void) {
    缓冲区配置_config_set_impl(&g_缓冲区配置_mock_vtable, NULL);
}
