// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: Mongoose IoT (mongoose)

/**
 * 自动生成于 BlessStar 配置 Mock — C 实现
 * 业务系统: Mongoose IoT (mongoose)
 * 领域: 网络参数
 * 专为单元测试设计 — 固定返回值
 */

#include "网络参数.h"
#include <stdlib.h>

// Mock: 监听背压队列
static int32_t mock_MG_SOCK_LISTEN_BACKLOG_SIZE(void* impl_ctx) {
    (void)impl_ctx;
    return 128;
}

// Mock vtable 实例 — 返回固定值
static const 网络参数_config_vtable_t g_网络参数_mock_vtable = {
    .MG_SOCK_LISTEN_BACKLOG_SIZE = mock_MG_SOCK_LISTEN_BACKLOG_SIZE,
};

// 网络参数_mock_init 初始化 Mock 适配器
// 将全局 vtable 设置为 Mock 实现，业务代码随后调用外观函数即可获得固定值
void 网络参数_mock_init(void) {
    网络参数_config_set_impl(&g_网络参数_mock_vtable, NULL);
}
