// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: config-schema.yaml
// Business System: livedesign (livedesign)

// Package adapters/blessstar 自动生成于 BlessStar 配置端口-适配器
// 业务系统: livedesign (livedesign)
// 领域: livedesign
// 请勿手动修改 — 由 blessstar-codegen 自动生成

import { ConfigReader } from '../../ports/config-reader';
import { LiveDesignConfig } from '../../ports/livedesign';

/**
 * LiveDesignConfigAdapter livedesign 域配置的 BlessStar 适配器
 * 内置三阶段降级: ConfigReader实时查询 → LastKnownGood缓存 → 硬编码默认值
 */
export class LiveDesignConfigAdapter implements LiveDesignConfig {
  private reader: ConfigReader;
  private lastKnownCache: Map<string, unknown> = new Map();
  private hardcodedDefaults: Record<string, unknown>;

  /**
   * @param reader 配置读取器，由业务方注入（可为 CachedReader、HTTPReader 等实现）
   */
  constructor(reader: ConfigReader) {
    this.reader = reader;
    this.hardcodedDefaults = {
      avatarPositionX: 0,
      avatarPositionY: 0,
      avatarScale: 1.0,
      chatRolePreset: "assistant",
      chatTemperature: 0.7,
      assistantTools: ["code_edit", "file_browse", "web_search"],
      uiTheme: "light",
      uiTransparency: 0.9,
      pluginEnabled: [],
    };
  }

  /**
 * 悬浮球初始 X 坐标，用户拖拽后实时持久化到本地存储 (avatar.position_x)
 * 描述: 控制悬浮球在屏幕上的水平位置，范围 -1920~3840 像素。用户拖拽后自动保存，无需手动修改。
 * 建议值: -1920~3840
 * 类型: I32
   */
  async avatarPositionX(): Promise<number> {
    // 第1阶段: ConfigReader 实时查询
    try {
      const val = await this.reader.get("/config/livedesign/avatar/position_x");
      if (val !== undefined && val !== null) {
        this.lastKnownCache.set("avatarPositionX", val);
        return val as number;
      }
    } catch {
      // 降级到下一阶段
    }

    // 第2阶段: 降级到 Last Known Good 缓存
    if (this.lastKnownCache.has("avatarPositionX")) {
      return this.lastKnownCache.get("avatarPositionX") as number;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return this.hardcodedDefaults["avatarPositionX"] as number;
  }

  /**
 * 悬浮球初始 Y 坐标，用户拖拽后实时持久化到本地存储 (avatar.position_y)
 * 描述: 控制悬浮球在屏幕上的垂直位置，范围 -1080~2160 像素。用户拖拽后自动保存，无需手动修改。
 * 建议值: -1080~2160
 * 类型: I32
   */
  async avatarPositionY(): Promise<number> {
    // 第1阶段: ConfigReader 实时查询
    try {
      const val = await this.reader.get("/config/livedesign/avatar/position_y");
      if (val !== undefined && val !== null) {
        this.lastKnownCache.set("avatarPositionY", val);
        return val as number;
      }
    } catch {
      // 降级到下一阶段
    }

    // 第2阶段: 降级到 Last Known Good 缓存
    if (this.lastKnownCache.has("avatarPositionY")) {
      return this.lastKnownCache.get("avatarPositionY") as number;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return this.hardcodedDefaults["avatarPositionY"] as number;
  }

  /**
 * 虚拟角色（Live2D 模型）的缩放比例，影响角色在屏幕上的显示大小 (avatar.scale)
 * 描述: 控制 Live2D 虚拟角色的显示大小，范围 0.5~2.0 倍。默认 1.0 为原始大小，增大可让角色在屏幕上更醒目。
 * 类型: F64
   */
  async avatarScale(): Promise<number> {
    // 第1阶段: ConfigReader 实时查询
    try {
      const val = await this.reader.get("/config/livedesign/avatar/scale");
      if (val !== undefined && val !== null) {
        this.lastKnownCache.set("avatarScale", val);
        return val as number;
      }
    } catch {
      // 降级到下一阶段
    }

    // 第2阶段: 降级到 Last Known Good 缓存
    if (this.lastKnownCache.has("avatarScale")) {
      return this.lastKnownCache.get("avatarScale") as number;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return this.hardcodedDefaults["avatarScale"] as number;
  }

  /**
 * 当前激活的角色设定标识，对应角色卡文件的 ID。切换角色时 LLM Service 会清空对话上下文并重载角色卡 (chat.role_preset)
 * 描述: 指定当前对话使用的角色预设。切换角色时系统会自动清空对话历史并加载对应角色卡（人格、说话风格、Live2D 模型等）。默认 assistant 为标准助手模式，其他值为角色扮演模式。
 * 类型: STR
   */
  async chatRolePreset(): Promise<string> {
    // 第1阶段: ConfigReader 实时查询
    try {
      const val = await this.reader.get("/config/livedesign/chat/role_preset");
      if (val !== undefined && val !== null) {
        this.lastKnownCache.set("chatRolePreset", val);
        return val as string;
      }
    } catch {
      // 降级到下一阶段
    }

    // 第2阶段: 降级到 Last Known Good 缓存
    if (this.lastKnownCache.has("chatRolePreset")) {
      return this.lastKnownCache.get("chatRolePreset") as string;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return this.hardcodedDefaults["chatRolePreset"] as string;
  }

  /**
 * AI 回复的随机性/创造性参数。值越高回复越随机多样，值越低回复越确定保守 (chat.temperature)
 * 描述: 控制 AI 回复的随机性。0.1~0.5 适合事实性问答（稳定准确），0.6~1.0 适合创意对话（丰富多样），1.1~2.0 适合头脑风暴（高度随机）。角色扮演推荐 0.7~0.9。
 * 类型: F64
   */
  async chatTemperature(): Promise<number> {
    // 第1阶段: ConfigReader 实时查询
    try {
      const val = await this.reader.get("/config/livedesign/chat/temperature");
      if (val !== undefined && val !== null) {
        this.lastKnownCache.set("chatTemperature", val);
        return val as number;
      }
    } catch {
      // 降级到下一阶段
    }

    // 第2阶段: 降级到 Last Known Good 缓存
    if (this.lastKnownCache.has("chatTemperature")) {
      return this.lastKnownCache.get("chatTemperature") as number;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return this.hardcodedDefaults["chatTemperature"] as number;
  }

  /**
 * 助手模式下 AI 可调用的工具列表。每次工具调用前需经过用户动作审批确认 (assistant.tools)
 * 描述: 配置助手模式可调用的工具列表。涉及代码编辑、文件读取、网络请求等敏感操作，每次调用都需要用户确认审批。建议仅开启需要的工具以减少审批打扰。
 * 类型: ARR
   */
  async assistantTools(): Promise<string[]> {
    // 第1阶段: ConfigReader 实时查询
    try {
      const val = await this.reader.get("/config/livedesign/assistant/tools");
      if (val !== undefined && val !== null) {
        this.lastKnownCache.set("assistantTools", val);
        return val as string[];
      }
    } catch {
      // 降级到下一阶段
    }

    // 第2阶段: 降级到 Last Known Good 缓存
    if (this.lastKnownCache.has("assistantTools")) {
      return this.lastKnownCache.get("assistantTools") as string[];
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return this.hardcodedDefaults["assistantTools"] as string[];
  }

  /**
 * 界面主题配色方案，影响所有 UI 组件的颜色风格 (ui.theme)
 * 描述: 切换应用界面的主题配色。light 为浅色主题，dark 为深色主题，system 跟随系统设置。主题切换实时生效，无需重启。
 * 类型: STR
   */
  async uiTheme(): Promise<string> {
    // 第1阶段: ConfigReader 实时查询
    try {
      const val = await this.reader.get("/config/livedesign/ui/theme");
      if (val !== undefined && val !== null) {
        this.lastKnownCache.set("uiTheme", val);
        return val as string;
      }
    } catch {
      // 降级到下一阶段
    }

    // 第2阶段: 降级到 Last Known Good 缓存
    if (this.lastKnownCache.has("uiTheme")) {
      return this.lastKnownCache.get("uiTheme") as string;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return this.hardcodedDefaults["uiTheme"] as string;
  }

  /**
 * 悬浮球窗口的透明度级别，影响悬浮球在桌面的视觉融合度 (ui.transparency)
 * 描述: 调节悬浮球窗口的透明度。1.0 为完全不透明，0.1 为几乎透明。调低透明度可让悬浮球更融入桌面背景，减少视觉干扰。
 * 类型: F64
   */
  async uiTransparency(): Promise<number> {
    // 第1阶段: ConfigReader 实时查询
    try {
      const val = await this.reader.get("/config/livedesign/ui/transparency");
      if (val !== undefined && val !== null) {
        this.lastKnownCache.set("uiTransparency", val);
        return val as number;
      }
    } catch {
      // 降级到下一阶段
    }

    // 第2阶段: 降级到 Last Known Good 缓存
    if (this.lastKnownCache.has("uiTransparency")) {
      return this.lastKnownCache.get("uiTransparency") as number;
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return this.hardcodedDefaults["uiTransparency"] as number;
  }

  /**
 * 当前已启用的插件 ID 列表，仅启用列表中的插件会被加载到 Plugin Host 沙箱中执行 (plugin.enabled)
 * 描述: 管理已安装插件的启用状态。插件运行在独立的 Plugin Host 沙箱进程中，但仍可能请求文件系统或网络能力。启用新插件时需要用户确认审批。修改后需重启插件宿主进程生效。
 * 类型: ARR
   */
  async pluginEnabled(): Promise<string[]> {
    // 第1阶段: ConfigReader 实时查询
    try {
      const val = await this.reader.get("/config/livedesign/plugin/enabled");
      if (val !== undefined && val !== null) {
        this.lastKnownCache.set("pluginEnabled", val);
        return val as string[];
      }
    } catch {
      // 降级到下一阶段
    }

    // 第2阶段: 降级到 Last Known Good 缓存
    if (this.lastKnownCache.has("pluginEnabled")) {
      return this.lastKnownCache.get("pluginEnabled") as string[];
    }

    // 第3阶段: 极冷启动 — 返回硬编码默认值
    return this.hardcodedDefaults["pluginEnabled"] as string[];
  }

}
