# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: 抖音商城 (douyin-mall)

# Package adapters.blessstar — BlessStar 适配器实现
# 请勿手动修改 — 由 blessstar-codegen 自动生成

from .product_adapter import ProductConfigAdapter
from .cors_adapter import CorsConfigAdapter
from .payment_adapter import PaymentConfigAdapter
from .user_adapter import UserConfigAdapter
from .order_adapter import OrderConfigAdapter
from .auth_adapter import AuthConfigAdapter
from .review_adapter import ReviewConfigAdapter
