# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: 抖音商城 (douyin-mall)

# Package adapter_blessstar — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: 抖音商城 (douyin-mall)
# 领域: 认证鉴权
# 请勿手动修改 — 由 blessstar-codegen 自动生成

from typing import Any, Dict
from contextlib import AbstractContextManager
from ports.config_reader import ConfigReader
from ports.auth import AuthConfig


class AuthConfigAdapter(AuthConfig):
    """认证鉴权域配置的 BlessStar 适配器
    内置三阶段降级: ConfigReader实时查询 → 缓存 → 硬编码默认值
    """

    def __init__(self, reader: ConfigReader) -> None:
        self._reader = reader
        self._cache: Dict[str, Any] = {}
        self._defaults: Dict[str, Any] = {
            "jwt_token_expiry_seconds": 86400,
            "password_bcrypt_cost": 10,
        }

    def jwt_token_expiry_seconds(self, ctx: AbstractContextManager) -> int:
        path = "/config/douyin-mall/auth/jwt/token_expiry_seconds"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["jwt_token_expiry_seconds"] = val
            return int(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "jwt_token_expiry_seconds" in self._cache:
            return int(self._cache["jwt_token_expiry_seconds"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return int(self._defaults["jwt_token_expiry_seconds"])

    def password_bcrypt_cost(self, ctx: AbstractContextManager) -> int:
        path = "/config/douyin-mall/auth/password/bcrypt_cost"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["password_bcrypt_cost"] = val
            return int(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "password_bcrypt_cost" in self._cache:
            return int(self._cache["password_bcrypt_cost"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return int(self._defaults["password_bcrypt_cost"])

