# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: 抖音商城 (douyin-mall)

# Package adapter_blessstar — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: 抖音商城 (douyin-mall)
# 领域: 评价管理
# 请勿手动修改 — 由 blessstar-codegen 自动生成

from typing import Any, Dict
from contextlib import AbstractContextManager
from ports.config_reader import ConfigReader
from ports.review import ReviewConfig


class ReviewConfigAdapter(ReviewConfig):
    """评价管理域配置的 BlessStar 适配器
    内置三阶段降级: ConfigReader实时查询 → 缓存 → 硬编码默认值
    """

    def __init__(self, reader: ConfigReader) -> None:
        self._reader = reader
        self._cache: Dict[str, Any] = {}
        self._defaults: Dict[str, Any] = {
            "rating_min": 1,
            "rating_max": 5,
        }

    def rating_min(self, ctx: AbstractContextManager) -> int:
        path = "/config/douyin-mall/review/rating/min"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["rating_min"] = val
            return int(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "rating_min" in self._cache:
            return int(self._cache["rating_min"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return int(self._defaults["rating_min"])

    def rating_max(self, ctx: AbstractContextManager) -> int:
        path = "/config/douyin-mall/review/rating/max"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["rating_max"] = val
            return int(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "rating_max" in self._cache:
            return int(self._cache["rating_max"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return int(self._defaults["rating_max"])

