# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: 抖音商城 (douyin-mall)

# Package adapter_blessstar — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: 抖音商城 (douyin-mall)
# 领域: 用户管理
# 请勿手动修改 — 由 blessstar-codegen 自动生成

from typing import Any, Dict
from contextlib import AbstractContextManager
from ports.config_reader import ConfigReader
from ports.user import UserConfig


class UserConfigAdapter(UserConfig):
    """用户管理域配置的 BlessStar 适配器
    内置三阶段降级: ConfigReader实时查询 → 缓存 → 硬编码默认值
    """

    def __init__(self, reader: ConfigReader) -> None:
        self._reader = reader
        self._cache: Dict[str, Any] = {}
        self._defaults: Dict[str, Any] = {
            "role_values": "[\"user\",\"admin\"]",
            "status_values": "{\"1\":\"active\",\"0\":\"inactive\",\"-1\":\"deleted\"}",
            "registration_default_role": "user",
            "registration_default_status": 1,
            "validation_username_min_length": 3,
            "validation_username_max_length": 50,
            "validation_password_min_length": 6,
            "validation_password_max_length": 50,
            "validation_email_required": True,
        }

    def role_values(self, ctx: AbstractContextManager) -> str:
        path = "/config/douyin-mall/user/role/values"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["role_values"] = val
            return str(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "role_values" in self._cache:
            return str(self._cache["role_values"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return str(self._defaults["role_values"])

    def status_values(self, ctx: AbstractContextManager) -> str:
        path = "/config/douyin-mall/user/status/values"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["status_values"] = val
            return str(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "status_values" in self._cache:
            return str(self._cache["status_values"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return str(self._defaults["status_values"])

    def registration_default_role(self, ctx: AbstractContextManager) -> str:
        path = "/config/douyin-mall/user/registration/default_role"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["registration_default_role"] = val
            return str(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "registration_default_role" in self._cache:
            return str(self._cache["registration_default_role"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return str(self._defaults["registration_default_role"])

    def registration_default_status(self, ctx: AbstractContextManager) -> int:
        path = "/config/douyin-mall/user/registration/default_status"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["registration_default_status"] = val
            return int(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "registration_default_status" in self._cache:
            return int(self._cache["registration_default_status"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return int(self._defaults["registration_default_status"])

    def validation_username_min_length(self, ctx: AbstractContextManager) -> int:
        path = "/config/douyin-mall/user/validation/username_min_length"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["validation_username_min_length"] = val
            return int(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "validation_username_min_length" in self._cache:
            return int(self._cache["validation_username_min_length"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return int(self._defaults["validation_username_min_length"])

    def validation_username_max_length(self, ctx: AbstractContextManager) -> int:
        path = "/config/douyin-mall/user/validation/username_max_length"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["validation_username_max_length"] = val
            return int(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "validation_username_max_length" in self._cache:
            return int(self._cache["validation_username_max_length"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return int(self._defaults["validation_username_max_length"])

    def validation_password_min_length(self, ctx: AbstractContextManager) -> int:
        path = "/config/douyin-mall/user/validation/password_min_length"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["validation_password_min_length"] = val
            return int(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "validation_password_min_length" in self._cache:
            return int(self._cache["validation_password_min_length"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return int(self._defaults["validation_password_min_length"])

    def validation_password_max_length(self, ctx: AbstractContextManager) -> int:
        path = "/config/douyin-mall/user/validation/password_max_length"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["validation_password_max_length"] = val
            return int(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "validation_password_max_length" in self._cache:
            return int(self._cache["validation_password_max_length"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return int(self._defaults["validation_password_max_length"])

    def validation_email_required(self, ctx: AbstractContextManager) -> bool:
        path = "/config/douyin-mall/user/validation/email_required"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["validation_email_required"] = val
            return bool(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "validation_email_required" in self._cache:
            return bool(self._cache["validation_email_required"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return bool(self._defaults["validation_email_required"])

