// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

package com.douyinmall.adapter.blessstar;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import com.douyinmall.ports.ConfigReader;
import com.douyinmall.ports.PaymentConfig;

/**
 * 支付管理域配置的 BlessStar 适配器
 * 业务系统: 抖音商城 (douyin-mall)
 * 内置三阶段降级: ConfigReader实时查询 -> LastKnownGood缓存 -> 硬编码默认值
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class PaymentConfigAdapter implements PaymentConfig {

	private final ConfigReader reader;
	private final Map<String, Object> lastKnownCache = new ConcurrentHashMap<>();
	private final Map<String, Object> hardcodedDefaults;

	/**
	 * 创建 PaymentConfigAdapter 适配器实例
	 * @param reader 配置读取器，由业务方注入（可为 CachedReader、HTTPReader 等实现）
	 */
	public PaymentConfigAdapter(ConfigReader reader) {
		this.reader = reader;
		this.hardcodedDefaults = new ConcurrentHashMap<>();
		this.hardcodedDefaults.put("getTypeValues", "{\"1\":\"alipay\",\"2\":\"wechat\",\"3\":\"credit_card\"}");
		this.hardcodedDefaults.put("getRecordStatusValues", "{\"0\":\"pending\",\"1\":\"success\",\"2\":\"failed\",\"3\":\"refunded\"}");
	}

	@Override
	public String getTypeValues() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/douyin-mall/payment/type/values");
			if (val != null) {
				lastKnownCache.put("getTypeValues", val);
				return (String) val;
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getTypeValues");
		if (cached != null) {
			return (String) cached;
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getTypeValues");
		return (String) fallback;
	}

	@Override
	public String getRecordStatusValues() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/douyin-mall/payment/record_status/values");
			if (val != null) {
				lastKnownCache.put("getRecordStatusValues", val);
				return (String) val;
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getRecordStatusValues");
		if (cached != null) {
			return (String) cached;
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getRecordStatusValues");
		return (String) fallback;
	}

}
