// Hand-written smoke test — validates generated provider works at runtime.
// This file is NOT generated by blessstar-codegen.
//
// It instantiates all adapters with a minimal reader that always returns errors,
// verifying that the 3-tier fallback (ConfigReader → LastKnownGood →
// hardcoded defaults) works correctly.

package douyin_mall_test

import (
	"context"
	"errors"
	"testing"

	"douyin-mall/ports"
	provider "douyin-mall/provider"
)

// errReader always returns an error, forcing fallback to hardcoded defaults.
type errReader struct{}

func (r errReader) Get(ctx context.Context, path string) (interface{}, error) {
	return nil, errors.New("no config source available")
}

func TestSmoke_FallbackToHardcodedDefaults(t *testing.T) {
	adapters := provider.ProvideBlessStarAdapters(errReader{})
	if adapters == nil {
		t.Fatal("ProvideBlessStarAdapters returned nil")
	}

	ctx := context.Background()

	t.Run("ProductConfig_StatusValues", func(t *testing.T) {
		v, err := adapters.ProductConfig.StatusValues(ctx)
		if err != nil {
			t.Fatalf("ProductConfig.StatusValues failed: %v", err)
		}
		if v == "" {
			t.Fatal("ProductConfig.StatusValues returned empty")
		}
		t.Logf("StatusValues = %s", v)
	})

	t.Run("CorsConfig_AllowedOrigins", func(t *testing.T) {
		v, err := adapters.CorsConfig.AllowedOrigins(ctx)
		if err != nil {
			t.Fatalf("CorsConfig.AllowedOrigins failed: %v", err)
		}
		if len(v) == 0 {
			t.Fatal("CorsConfig.AllowedOrigins returned empty")
		}
		t.Logf("AllowedOrigins = %v", v)
	})

	t.Run("PaymentConfig_TypeValues", func(t *testing.T) {
		v, err := adapters.PaymentConfig.TypeValues(ctx)
		if err != nil {
			t.Fatalf("PaymentConfig.TypeValues failed: %v", err)
		}
		if v == "" {
			t.Fatal("PaymentConfig.TypeValues returned empty")
		}
		t.Logf("TypeValues = %s", v)
	})

	t.Run("UserConfig_RoleValues", func(t *testing.T) {
		v, err := adapters.UserConfig.RoleValues(ctx)
		if err != nil {
			t.Fatalf("UserConfig.RoleValues failed: %v", err)
		}
		if v == "" {
			t.Fatal("UserConfig.RoleValues returned empty")
		}
		t.Logf("RoleValues = %s", v)
	})

	t.Run("OrderConfig_StatusValues", func(t *testing.T) {
		v, err := adapters.OrderConfig.StatusValues(ctx)
		if err != nil {
			t.Fatalf("OrderConfig.StatusValues failed: %v", err)
		}
		if v == "" {
			t.Fatal("OrderConfig.StatusValues returned empty")
		}
		t.Logf("StatusValues = %s", v)
	})

	t.Run("AuthConfig_JwtTokenExpirySeconds", func(t *testing.T) {
		v, err := adapters.AuthConfig.JwtTokenExpirySeconds(ctx)
		if err != nil {
			t.Fatalf("AuthConfig.JwtTokenExpirySeconds failed: %v", err)
		}
		if v <= 0 {
			t.Fatal("AuthConfig.JwtTokenExpirySeconds <= 0")
		}
		t.Logf("JwtTokenExpirySeconds = %v", v)
	})

	t.Run("ReviewConfig_RatingMin", func(t *testing.T) {
		v, err := adapters.ReviewConfig.RatingMin(ctx)
		if err != nil {
			t.Fatalf("ReviewConfig.RatingMin failed: %v", err)
		}
		if v == 0 {
			t.Fatal("ReviewConfig.RatingMin == 0, expected non-zero default")
		}
		t.Logf("RatingMin = %d", v)
	})
}

// Ensure all port interface types are importable.
var _ ports.ProductConfig = (*struct{ ports.ProductConfig })(nil)
var _ ports.CorsConfig = (*struct{ ports.CorsConfig })(nil)
var _ ports.PaymentConfig = (*struct{ ports.PaymentConfig })(nil)
var _ ports.UserConfig = (*struct{ ports.UserConfig })(nil)
var _ ports.OrderConfig = (*struct{ ports.OrderConfig })(nil)
var _ ports.AuthConfig = (*struct{ ports.AuthConfig })(nil)
var _ ports.ReviewConfig = (*struct{ ports.ReviewConfig })(nil)
