// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

package com.douyinmall.adapter.mock;

import com.douyinmall.ports.OrderConfig;

/**
 * 订单管理域配置的 Mock 实现（单元测试用）
 * 业务系统: 抖音商城 (douyin-mall)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class OrderConfigMock implements OrderConfig {

	private String etStatusValues = "{\"0\":\"pending_payment\",\"1\":\"paid\",\"2\":\"shipped\",\"3\":\"delivered\",\"4\":\"completed\",\"-1\":\"cancelled\"}";

	/**
	 * 创建默认 Mock（返回值按 manifest 默认值设定）
	 */
	public OrderConfigMock() {
	}

	/**
	 * 创建默认 Mock 实例
	 */
	public static OrderConfigMock create() {
		return new OrderConfigMock();
	}

	/**
	 * 设置 订单状态
	 * @param value 订单状态 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public OrderConfigMock withStatusValues(String value) {
		this.etStatusValues = value;
		return this;
	}

	@Override
	public String getStatusValues() throws Exception {
		return this.etStatusValues;
	}

}
