// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

package com.douyinmall.adapter.mock;

import com.douyinmall.ports.PaymentConfig;

/**
 * 支付管理域配置的 Mock 实现（单元测试用）
 * 业务系统: 抖音商城 (douyin-mall)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class PaymentConfigMock implements PaymentConfig {

	private String etTypeValues = "{\"1\":\"alipay\",\"2\":\"wechat\",\"3\":\"credit_card\"}";
	private String etRecordStatusValues = "{\"0\":\"pending\",\"1\":\"success\",\"2\":\"failed\",\"3\":\"refunded\"}";

	/**
	 * 创建默认 Mock（返回值按 manifest 默认值设定）
	 */
	public PaymentConfigMock() {
	}

	/**
	 * 创建默认 Mock 实例
	 */
	public static PaymentConfigMock create() {
		return new PaymentConfigMock();
	}

	/**
	 * 设置 支付方式
	 * @param value 支付方式 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public PaymentConfigMock withTypeValues(String value) {
		this.etTypeValues = value;
		return this;
	}

	/**
	 * 设置 支付记录状态
	 * @param value 支付记录状态 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public PaymentConfigMock withRecordStatusValues(String value) {
		this.etRecordStatusValues = value;
		return this;
	}

	@Override
	public String getTypeValues() throws Exception {
		return this.etTypeValues;
	}

	@Override
	public String getRecordStatusValues() throws Exception {
		return this.etRecordStatusValues;
	}

}
