// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

package com.douyinmall.adapter.mock;

import com.douyinmall.ports.ProductConfig;

/**
 * 商品管理域配置的 Mock 实现（单元测试用）
 * 业务系统: 抖音商城 (douyin-mall)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class ProductConfigMock implements ProductConfig {

	private String etStatusValues = "{\"1\":\"on_sale\",\"0\":\"off_sale\",\"-1\":\"deleted\"}";

	/**
	 * 创建默认 Mock（返回值按 manifest 默认值设定）
	 */
	public ProductConfigMock() {
	}

	/**
	 * 创建默认 Mock 实例
	 */
	public static ProductConfigMock create() {
		return new ProductConfigMock();
	}

	/**
	 * 设置 商品状态
	 * @param value 商品状态 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public ProductConfigMock withStatusValues(String value) {
		this.etStatusValues = value;
		return this;
	}

	@Override
	public String getStatusValues() throws Exception {
		return this.etStatusValues;
	}

}
