// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

package com.douyinmall.ports;

/**
 * 认证鉴权域配置接口
 * 自动生成于 BlessStar 配置端口-适配器
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 认证鉴权
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public interface AuthConfig {

	/**
	 * JWT过期时间 (auth.jwt.token_expiry_seconds)
	 * 描述: JWT登录令牌的有效期时长（秒），过期后用户需重新登录。
	 * 建议值: 3600~604800（1小时~7天），推荐步长3600秒
	 * 类型: I64
	 */
	long getJwtTokenExpirySeconds() throws Exception;

	/**
	 * 密码加密强度 (auth.password.bcrypt_cost)
	 * 描述: 密码哈希计算成本因子，控制密码加密强度。
	 * 建议值: 4~14，推荐步长1。生产建议10~12
	 * 类型: I32
	 */
	int getPasswordBcryptCost() throws Exception;

}
