// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

package com.douyinmall.ports;

/**
 * 支付管理域配置接口
 * 自动生成于 BlessStar 配置端口-适配器
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 支付管理
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public interface PaymentConfig {

	/**
	 * 支付方式 (payment.type.values)
	 * 描述: 平台支持的支付方式枚举。
	 * 建议值: 当前支持：1=支付宝，2=微信支付，3=信用卡。新增需评估支付通道成本和技术对接周期
	 * 类型: ENUM
	 */
	String getTypeValues() throws Exception;

	/**
	 * 支付记录状态 (payment.record_status.values)
	 * 描述: 支付记录处理状态枚举。
	 * 建议值: 当前支持：0=待处理→1=成功/2=失败，3=已退款（从成功状态转入）
	 * 类型: ENUM
	 */
	String getRecordStatusValues() throws Exception;

}
