package backend

import (
	"strings"

	"github.com/blessstar/blessstar-codegen/types"
)

// File represents a generated source file
type File struct {
	Path    string
	Content string
}

// LanguageBackend defines the interface for code generation backends
type LanguageBackend interface {
	// Name returns the language name (e.g., "go", "java", "python")
	Name() string

	// FileExtension returns the file extension (e.g., ".go", ".java", ".py")
	FileExtension() string

	// CommentPrefix returns the single-line comment prefix for the language (e.g., "//", "#")
	CommentPrefix() string

	// GenerateBlessStarAdapter generates the BlessStar adapter implementation for a domain
	GenerateBlessStarAdapter(biz *types.BizSystem, domain string, configs []types.ConfigField) (*File, error)

	// GenerateMockAdapter generates the mock adapter implementation for a domain
	GenerateMockAdapter(biz *types.BizSystem, domain string, configs []types.ConfigField) (*File, error)

	// GenerateProvider generates the dependency injection provider
	GenerateProvider(biz *types.BizSystem) (*File, error)

	// GenerateGoMod generates go.mod if applicable
	GenerateGoMod(biz *types.BizSystem) (*File, error)

	// GenerateConfigReaderFile generates the ConfigReader interface and optional
	// CachedReader decorator into the output directory.
	// Returns multiple files (ports/config_reader.go, provider/cached_reader.go),
	// or nil if not applicable.
	GenerateConfigReaderFile(biz *types.BizSystem) ([]*File, error)

	// GenerateInitFiles generates language-specific package init files (e.g.
	// Python's __init__.py). Returns nil if not applicable.
	GenerateInitFiles(biz *types.BizSystem) ([]*File, error)

	// ─── 可选扩展方法（Schema-First 模式使用） ───

	// GenerateGateConfigs 生成门禁配置文件（如 gate_configs.h）。
	// 仅在 Schema-First 模式下调用，gateConfigs 由 ExtractGateConfigs 产出。
	GenerateGateConfigs(biz *types.BizSystem, gateConfigs []types.GateConfig) (*File, error)

	// GenerateTestCases 生成边界测试文件。
	// 仅在 Schema-First 模式下调用，testCases 由 GenerateTestCases 产出。
	GenerateTestCases(biz *types.BizSystem, testCases []string) (*File, error)

	// GenerateObservability 生成可观测性规则文件（如 Prometheus 告警规则）。
	// 仅在 Schema-First 模式下调用，rules 由 ExtractObservabilityRules 产出。
	GenerateObservability(biz *types.BizSystem, rules []string) (*File, error)
}

// PackageNameFromBiz derives a Go package name from biz_id
func PackageNameFromBiz(bizID string) string {
	return bizID
}

// CodegenHeader returns the standardized "DO NOT EDIT" header for generated files.
// It uses the language-appropriate comment prefix based on file extension.
func CodegenHeader(path string) string {
	prefix := CommentPrefixForFile(path)
	return prefix + " Code generated by blessstar-codegen. DO NOT EDIT.\n"
}

// HeaderForBiz returns the full header block including biz metadata.
func HeaderForBiz(path, bizID, displayName string) string {
	return HeaderForBizWithSource(path, bizID, displayName, "manifest.json")
}

// HeaderForBizWithSource returns the full header with a custom source label.
func HeaderForBizWithSource(path, bizID, displayName, source string) string {
	prefix := CommentPrefixForFile(path)
	var b strings.Builder
	b.WriteString(prefix + " Code generated by blessstar-codegen. DO NOT EDIT.\n")
	b.WriteString(prefix + " Source: " + source + "\n")
	b.WriteString(prefix + " Business System: " + displayName + " (" + bizID + ")\n")
	return b.String()
}

// CommentPrefixForFile returns the single-line comment prefix for a given file path.
func CommentPrefixForFile(path string) string {
	if strings.HasSuffix(path, ".py") {
		return "#"
	}
	return "//"
}
