// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

package com.douyinmall.adapter.mock;

import com.douyinmall.ports.AuthConfig;

/**
 * 认证鉴权域配置的 Mock 实现（单元测试用）
 * 业务系统: 抖音商城 (douyin-mall)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class AuthConfigMock implements AuthConfig {

	private long etJwtTokenExpirySeconds = 86400L;
	private int etPasswordBcryptCost = 10;

	/**
	 * 创建默认 Mock（返回值按 manifest 默认值设定）
	 */
	public AuthConfigMock() {
	}

	/**
	 * 创建默认 Mock 实例
	 */
	public static AuthConfigMock create() {
		return new AuthConfigMock();
	}

	/**
	 * 设置 JWT过期时间
	 * @param value JWT过期时间 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public AuthConfigMock withJwtTokenExpirySeconds(long value) {
		this.etJwtTokenExpirySeconds = value;
		return this;
	}

	/**
	 * 设置 密码加密强度
	 * @param value 密码加密强度 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public AuthConfigMock withPasswordBcryptCost(int value) {
		this.etPasswordBcryptCost = value;
		return this;
	}

	@Override
	public long getJwtTokenExpirySeconds() throws Exception {
		return this.etJwtTokenExpirySeconds;
	}

	@Override
	public int getPasswordBcryptCost() throws Exception {
		return this.etPasswordBcryptCost;
	}

}
