// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

package com.douyinmall.adapter.mock;

import com.douyinmall.ports.CorsConfig;

/**
 * 安全策略域配置的 Mock 实现（单元测试用）
 * 业务系统: 抖音商城 (douyin-mall)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class CorsConfigMock implements CorsConfig {

	private java.util.List<String> etAllowedOrigins = java.util.List.of("*");

	/**
	 * 创建默认 Mock（返回值按 manifest 默认值设定）
	 */
	public CorsConfigMock() {
	}

	/**
	 * 创建默认 Mock 实例
	 */
	public static CorsConfigMock create() {
		return new CorsConfigMock();
	}

	/**
	 * 设置 跨域白名单
	 * @param value 跨域白名单 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public CorsConfigMock withAllowedOrigins(java.util.List<String> value) {
		this.etAllowedOrigins = value;
		return this;
	}

	@Override
	public java.util.List<String> getAllowedOrigins() throws Exception {
		return this.etAllowedOrigins;
	}

}
