// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

package com.douyinmall.adapter.mock;

import com.douyinmall.ports.ReviewConfig;

/**
 * 评价管理域配置的 Mock 实现（单元测试用）
 * 业务系统: 抖音商城 (douyin-mall)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class ReviewConfigMock implements ReviewConfig {

	private int etRatingMin = 1;
	private int etRatingMax = 5;

	/**
	 * 创建默认 Mock（返回值按 manifest 默认值设定）
	 */
	public ReviewConfigMock() {
	}

	/**
	 * 创建默认 Mock 实例
	 */
	public static ReviewConfigMock create() {
		return new ReviewConfigMock();
	}

	/**
	 * 设置 评分下限
	 * @param value 评分下限 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public ReviewConfigMock withRatingMin(int value) {
		this.etRatingMin = value;
		return this;
	}

	/**
	 * 设置 评分上限
	 * @param value 评分上限 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public ReviewConfigMock withRatingMax(int value) {
		this.etRatingMax = value;
		return this;
	}

	@Override
	public int getRatingMin() throws Exception {
		return this.etRatingMin;
	}

	@Override
	public int getRatingMax() throws Exception {
		return this.etRatingMax;
	}

}
