// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

package com.douyinmall.adapter.mock;

import com.douyinmall.ports.UserConfig;

/**
 * 用户管理域配置的 Mock 实现（单元测试用）
 * 业务系统: 抖音商城 (douyin-mall)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class UserConfigMock implements UserConfig {

	private String etRoleValues = "[\"user\",\"admin\"]";
	private String etStatusValues = "{\"1\":\"active\",\"0\":\"inactive\",\"-1\":\"deleted\"}";
	private String etRegistrationDefaultRole = "user";
	private int etRegistrationDefaultStatus = 1;
	private int etValidationUsernameMinLength = 3;
	private int etValidationUsernameMaxLength = 50;
	private int etValidationPasswordMinLength = 6;
	private int etValidationPasswordMaxLength = 50;
	private boolean etValidationEmailRequired = true;

	/**
	 * 创建默认 Mock（返回值按 manifest 默认值设定）
	 */
	public UserConfigMock() {
	}

	/**
	 * 创建默认 Mock 实例
	 */
	public static UserConfigMock create() {
		return new UserConfigMock();
	}

	/**
	 * 设置 用户角色
	 * @param value 用户角色 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public UserConfigMock withRoleValues(String value) {
		this.etRoleValues = value;
		return this;
	}

	/**
	 * 设置 用户状态
	 * @param value 用户状态 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public UserConfigMock withStatusValues(String value) {
		this.etStatusValues = value;
		return this;
	}

	/**
	 * 设置 默认角色
	 * @param value 默认角色 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public UserConfigMock withRegistrationDefaultRole(String value) {
		this.etRegistrationDefaultRole = value;
		return this;
	}

	/**
	 * 设置 默认状态
	 * @param value 默认状态 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public UserConfigMock withRegistrationDefaultStatus(int value) {
		this.etRegistrationDefaultStatus = value;
		return this;
	}

	/**
	 * 设置 用户名最小长度
	 * @param value 用户名最小长度 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public UserConfigMock withValidationUsernameMinLength(int value) {
		this.etValidationUsernameMinLength = value;
		return this;
	}

	/**
	 * 设置 用户名最大长度
	 * @param value 用户名最大长度 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public UserConfigMock withValidationUsernameMaxLength(int value) {
		this.etValidationUsernameMaxLength = value;
		return this;
	}

	/**
	 * 设置 密码最小长度
	 * @param value 密码最小长度 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public UserConfigMock withValidationPasswordMinLength(int value) {
		this.etValidationPasswordMinLength = value;
		return this;
	}

	/**
	 * 设置 密码最大长度
	 * @param value 密码最大长度 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public UserConfigMock withValidationPasswordMaxLength(int value) {
		this.etValidationPasswordMaxLength = value;
		return this;
	}

	/**
	 * 设置 邮箱必填
	 * @param value 邮箱必填 值
	 * @return 当前 Mock 实例（支持链式调用）
	 */
	public UserConfigMock withValidationEmailRequired(boolean value) {
		this.etValidationEmailRequired = value;
		return this;
	}

	@Override
	public String getRoleValues() throws Exception {
		return this.etRoleValues;
	}

	@Override
	public String getStatusValues() throws Exception {
		return this.etStatusValues;
	}

	@Override
	public String getRegistrationDefaultRole() throws Exception {
		return this.etRegistrationDefaultRole;
	}

	@Override
	public int getRegistrationDefaultStatus() throws Exception {
		return this.etRegistrationDefaultStatus;
	}

	@Override
	public int getValidationUsernameMinLength() throws Exception {
		return this.etValidationUsernameMinLength;
	}

	@Override
	public int getValidationUsernameMaxLength() throws Exception {
		return this.etValidationUsernameMaxLength;
	}

	@Override
	public int getValidationPasswordMinLength() throws Exception {
		return this.etValidationPasswordMinLength;
	}

	@Override
	public int getValidationPasswordMaxLength() throws Exception {
		return this.etValidationPasswordMaxLength;
	}

	@Override
	public boolean getValidationEmailRequired() throws Exception {
		return this.etValidationEmailRequired;
	}

}
