# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: 抖音商城 (douyin-mall)

# Package adapter_mock — 自动生成于 BlessStar 配置 Mock
# 业务系统: 抖音商城 (douyin-mall)
# 领域: 认证鉴权
# 专为单元测试设计 — 固定返回值

from typing import Callable
from contextlib import AbstractContextManager
from ports.auth import AuthConfig


class AuthConfigMock(AuthConfig):
    """认证鉴权域配置的 Mock 实现（单元测试用）"""

    def __init__(self) -> None:
        self.jwt_token_expiry_seconds_func: Callable[[AbstractContextManager], int] = lambda ctx: 86400
        self.password_bcrypt_cost_func: Callable[[AbstractContextManager], int] = lambda ctx: 10

    @classmethod
    def create_default(cls) -> AuthConfig:
        """创建默认 Mock 实例（返回值按 manifest 默认值设定）"""
        return cls()

    def jwt_token_expiry_seconds(self, ctx: AbstractContextManager) -> int:
        return self.jwt_token_expiry_seconds_func(ctx)

    def password_bcrypt_cost(self, ctx: AbstractContextManager) -> int:
        return self.password_bcrypt_cost_func(ctx)

