// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置 Mock — C 实现
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 认证鉴权
 * 专为单元测试设计 — 固定返回值
 */

#include "auth.h"
#include <stdlib.h>

// Mock: JWT过期时间
static int64_t mock_jwt_token_expiry_seconds(void* impl_ctx) {
    (void)impl_ctx;
    return 86400;
}

// Mock: 密码加密强度
static int32_t mock_password_bcrypt_cost(void* impl_ctx) {
    (void)impl_ctx;
    return 10;
}

// Mock vtable 实例 — 返回固定值
static const auth_config_vtable_t g_auth_mock_vtable = {
    .jwt_token_expiry_seconds = mock_jwt_token_expiry_seconds,
    .password_bcrypt_cost = mock_password_bcrypt_cost,
};

// auth_mock_init 初始化 Mock 适配器
// 将全局 vtable 设置为 Mock 实现，业务代码随后调用外观函数即可获得固定值
void auth_mock_init(void) {
    auth_config_set_impl(&g_auth_mock_vtable, NULL);
}
