// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置 Mock — C 实现
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 安全策略
 * 专为单元测试设计 — 固定返回值
 */

#include "cors.h"
#include <stdlib.h>

// Mock: 跨域白名单
static const char** mock_allowed_origins(void* impl_ctx, size_t* out_len) {
    (void)impl_ctx;
    if (out_len) *out_len = 0;
    return "[\"*\"]";
}

// Mock vtable 实例 — 返回固定值
static const cors_config_vtable_t g_cors_mock_vtable = {
    .allowed_origins = mock_allowed_origins,
};

// cors_mock_init 初始化 Mock 适配器
// 将全局 vtable 设置为 Mock 实现，业务代码随后调用外观函数即可获得固定值
void cors_mock_init(void) {
    cors_config_set_impl(&g_cors_mock_vtable, NULL);
}
