# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: 抖音商城 (douyin-mall)

# Package adapter_mock — 自动生成于 BlessStar 配置 Mock
# 业务系统: 抖音商城 (douyin-mall)
# 领域: 安全策略
# 专为单元测试设计 — 固定返回值

from typing import Callable
from contextlib import AbstractContextManager
from ports.cors import CorsConfig


class CorsConfigMock(CorsConfig):
    """安全策略域配置的 Mock 实现（单元测试用）"""

    def __init__(self) -> None:
        self.allowed_origins_func: Callable[[AbstractContextManager], list[str]] = lambda ctx: ["*"]

    @classmethod
    def create_default(cls) -> CorsConfig:
        """创建默认 Mock 实例（返回值按 manifest 默认值设定）"""
        return cls()

    def allowed_origins(self, ctx: AbstractContextManager) -> list[str]:
        return self.allowed_origins_func(ctx)

