// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置 Mock — C 实现
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 订单管理
 * 专为单元测试设计 — 固定返回值
 */

#include "order.h"
#include <stdlib.h>

// Mock: 订单状态
static const char* mock_status_values(void* impl_ctx) {
    (void)impl_ctx;
    return "{\"0\":\"pending_payment\",\"1\":\"paid\",\"2\":\"shipped\",\"3\":\"delivered\",\"4\":\"completed\",\"-1\":\"cancelled\"}";
}

// Mock vtable 实例 — 返回固定值
static const order_config_vtable_t g_order_mock_vtable = {
    .status_values = mock_status_values,
};

// order_mock_init 初始化 Mock 适配器
// 将全局 vtable 设置为 Mock 实现，业务代码随后调用外观函数即可获得固定值
void order_mock_init(void) {
    order_config_set_impl(&g_order_mock_vtable, NULL);
}
