// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

// Package adapter_mock 自动生成于 BlessStar 配置 Mock
// 业务系统: 抖音商城 (douyin-mall)
// 领域: 评价管理
// 专为单元测试设计 — 固定返回值

package adapter_mock

import (
	"context"
	"douyin-mall/ports"
)

// ReviewConfigMock 评价管理 域配置的 Mock 实现（单元测试用）
type ReviewConfigMock struct {
	RatingMinFunc func(ctx context.Context) (int32, error)
	RatingMaxFunc func(ctx context.Context) (int32, error)
}

// NewReviewConfigMock 创建默认 Mock（返回值按 manifest 默认值设定）
func NewReviewConfigMock() ports.ReviewConfig {
	return &ReviewConfigMock{
		RatingMinFunc: func(ctx context.Context) (int32, error) {
			return 1, nil
		},
		RatingMaxFunc: func(ctx context.Context) (int32, error) {
			return 5, nil
		},
	}
}

func (m *ReviewConfigMock) RatingMin(ctx context.Context) (int32, error) {
	return m.RatingMinFunc(ctx)
}

func (m *ReviewConfigMock) RatingMax(ctx context.Context) (int32, error) {
	return m.RatingMaxFunc(ctx)
}

