// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置 Mock — C 实现
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 评价管理
 * 专为单元测试设计 — 固定返回值
 */

#include "review.h"
#include <stdlib.h>

// Mock: 评分下限
static int32_t mock_rating_min(void* impl_ctx) {
    (void)impl_ctx;
    return 1;
}

// Mock: 评分上限
static int32_t mock_rating_max(void* impl_ctx) {
    (void)impl_ctx;
    return 5;
}

// Mock vtable 实例 — 返回固定值
static const review_config_vtable_t g_review_mock_vtable = {
    .rating_min = mock_rating_min,
    .rating_max = mock_rating_max,
};

// review_mock_init 初始化 Mock 适配器
// 将全局 vtable 设置为 Mock 实现，业务代码随后调用外观函数即可获得固定值
void review_mock_init(void) {
    review_config_set_impl(&g_review_mock_vtable, NULL);
}
