// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置 Mock — C 实现
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 用户管理
 * 专为单元测试设计 — 固定返回值
 */

#include "user.h"
#include <stdlib.h>

// Mock: 用户角色
static const char* mock_role_values(void* impl_ctx) {
    (void)impl_ctx;
    return "[\"user\",\"admin\"]";
}

// Mock: 用户状态
static const char* mock_status_values(void* impl_ctx) {
    (void)impl_ctx;
    return "{\"1\":\"active\",\"0\":\"inactive\",\"-1\":\"deleted\"}";
}

// Mock: 默认角色
static const char* mock_registration_default_role(void* impl_ctx) {
    (void)impl_ctx;
    return "user";
}

// Mock: 默认状态
static int32_t mock_registration_default_status(void* impl_ctx) {
    (void)impl_ctx;
    return 1;
}

// Mock: 用户名最小长度
static int32_t mock_validation_username_min_length(void* impl_ctx) {
    (void)impl_ctx;
    return 3;
}

// Mock: 用户名最大长度
static int32_t mock_validation_username_max_length(void* impl_ctx) {
    (void)impl_ctx;
    return 50;
}

// Mock: 密码最小长度
static int32_t mock_validation_password_min_length(void* impl_ctx) {
    (void)impl_ctx;
    return 6;
}

// Mock: 密码最大长度
static int32_t mock_validation_password_max_length(void* impl_ctx) {
    (void)impl_ctx;
    return 50;
}

// Mock: 邮箱必填
static bool mock_validation_email_required(void* impl_ctx) {
    (void)impl_ctx;
    return true;
}

// Mock vtable 实例 — 返回固定值
static const user_config_vtable_t g_user_mock_vtable = {
    .role_values = mock_role_values,
    .status_values = mock_status_values,
    .registration_default_role = mock_registration_default_role,
    .registration_default_status = mock_registration_default_status,
    .validation_username_min_length = mock_validation_username_min_length,
    .validation_username_max_length = mock_validation_username_max_length,
    .validation_password_min_length = mock_validation_password_min_length,
    .validation_password_max_length = mock_validation_password_max_length,
    .validation_email_required = mock_validation_email_required,
};

// user_mock_init 初始化 Mock 适配器
// 将全局 vtable 设置为 Mock 实现，业务代码随后调用外观函数即可获得固定值
void user_mock_init(void) {
    user_config_set_impl(&g_user_mock_vtable, NULL);
}
