# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: 抖音商城 (douyin-mall)

# Package douyin_mall — 自动生成于 BlessStar 配置依赖注入
# 业务系统: 抖音商城 (douyin-mall)
# 请勿手动修改 — 由 blessstar-codegen 自动生成

from dataclasses import dataclass
from ports.config_reader import ConfigReader
from ports.product import ProductConfig
from ports.cors import CorsConfig
from ports.payment import PaymentConfig
from ports.user import UserConfig
from ports.order import OrderConfig
from ports.auth import AuthConfig
from ports.review import ReviewConfig


@dataclass
class Adapters:
    """持有所有域的配置适配器"""
    product_config: ProductConfig
    cors_config: CorsConfig
    payment_config: PaymentConfig
    user_config: UserConfig
    order_config: OrderConfig
    auth_config: AuthConfig
    review_config: ReviewConfig

def provide_blessstar_adapters(reader: ConfigReader) -> Adapters:
    """一行实例化所有域配置适配器

    注入 ConfigReader 后返回所有域的 Port 实现
    reader 由业务方提供（可为 CachedReader、HTTPReader、EnvReader 等实现）
    """
    return Adapters(
        product_config=adapter_blessstar.ProductConfigAdapter(reader),
        cors_config=adapter_blessstar.CorsConfigAdapter(reader),
        payment_config=adapter_blessstar.PaymentConfigAdapter(reader),
        user_config=adapter_blessstar.UserConfigAdapter(reader),
        order_config=adapter_blessstar.OrderConfigAdapter(reader),
        auth_config=adapter_blessstar.AuthConfigAdapter(reader),
        review_config=adapter_blessstar.ReviewConfigAdapter(reader),
    )
