// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置 — CachedReader C 实现
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */

#include "ports/config_reader.h"
#include <stdlib.h>
#include <string.h>

// 简单的缓存条目
typedef struct cache_entry {
    char* path;
    void* value;
    char* type;
    struct cache_entry* next;
} cache_entry_t;

// CachedReader 结构体
typedef struct {
    config_reader_vtable_t vtable;
    config_reader_vtable_t* inner;  // 内部读取器的 vtable
    cache_entry_t* head;
} cached_reader_t;

// 内部 get 实现
static int cached_reader_get(void* ctx, const char* path, void** out_val, const char** out_type) {
    cached_reader_t* cr = (cached_reader_t*)ctx;
    
    // 先查缓存
    cache_entry_t* entry = cr->head;
    while (entry) {
        if (strcmp(entry->path, path) == 0) {
            if (entry->value) {
                // 返回缓存值的拷贝
                // NOTE: 简化实现，实际场景需要根据 type 做深拷贝
                *out_val = entry->value;
                *out_type = entry->type;
                return 0;
            }
            break;
        }
        entry = entry->next;
    }
    
    // 穿透到内部读取器
    if (cr->inner && cr->inner->get) {
        int ret = cr->inner->get(cr->inner->impl_ctx, path, out_val, out_type);
        if (ret == 0 && *out_val) {
            // 写入缓存
            cache_entry_t* new_entry = (cache_entry_t*)malloc(sizeof(cache_entry_t));
            if (new_entry) {
                new_entry->path = (char*)malloc(strlen(path) + 1);
                if (new_entry->path) strcpy(new_entry->path, path);
                new_entry->value = *out_val;  // NOTE: 简化实现，未做深拷贝
                new_entry->type = *out_type ? strdup(*out_type) : NULL;
                new_entry->next = cr->head;
                cr->head = new_entry;
            }
        }
        return ret;
    }
    
    return -1;
}

// 创建 CachedReader
config_reader_t* cached_reader_create(config_reader_vtable_t* inner_vtable) {
    cached_reader_t* cr = (cached_reader_t*)malloc(sizeof(cached_reader_t));
    if (!cr) return NULL;
    
    cr->vtable.get = cached_reader_get;
    cr->inner = inner_vtable;
    cr->head = NULL;
    
    config_reader_t* reader = (config_reader_t*)malloc(sizeof(config_reader_t));
    if (!reader) {
        free(cr);
        return NULL;
    }
    reader->vtable = &cr->vtable;
    
    // 注册到全局
    config_reader_set_impl(&cr->vtable);
    
    return reader;
}
