// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置依赖注入 — C 实现
 * 业务系统: 抖音商城 (douyin-mall)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */

#include "ports/config_reader.h"
#include "ports/product.h"
#include "ports/cors.h"
#include "ports/payment.h"
#include "ports/user.h"
#include "ports/order.h"
#include "ports/auth.h"
#include "ports/review.h"

/**
 * blessstar_provide_adapters 一行初始化所有域配置适配器。
 * 由业务方在启动时调用，传入 ConfigReader 实例。
 * reader 为 NULL 时仅加载硬编码默认值（极冷启动降级）。
 */
void douyin_mall_provide_adapters(config_reader_t* reader) {
    (void)reader;

    // 商品管理 域 — 创建适配器并注册
    static product_config_adapter_t product_adapter_inst;
    product_adapter_inst.reader = reader;
    product_adapter_inst.cache.status_values_valid = false;
    product_config_set_impl(&g_product_vtable_impl, &product_adapter_inst);

    // 安全策略 域 — 创建适配器并注册
    static cors_config_adapter_t cors_adapter_inst;
    cors_adapter_inst.reader = reader;
    cors_adapter_inst.cache.allowed_origins_valid = false;
    cors_config_set_impl(&g_cors_vtable_impl, &cors_adapter_inst);

    // 支付管理 域 — 创建适配器并注册
    static payment_config_adapter_t payment_adapter_inst;
    payment_adapter_inst.reader = reader;
    payment_adapter_inst.cache.type_values_valid = false;
    payment_adapter_inst.cache.record_status_values_valid = false;
    payment_config_set_impl(&g_payment_vtable_impl, &payment_adapter_inst);

    // 用户管理 域 — 创建适配器并注册
    static user_config_adapter_t user_adapter_inst;
    user_adapter_inst.reader = reader;
    user_adapter_inst.cache.role_values_valid = false;
    user_adapter_inst.cache.status_values_valid = false;
    user_adapter_inst.cache.registration_default_role_valid = false;
    user_adapter_inst.cache.registration_default_status_valid = false;
    user_adapter_inst.cache.validation_username_min_length_valid = false;
    user_adapter_inst.cache.validation_username_max_length_valid = false;
    user_adapter_inst.cache.validation_password_min_length_valid = false;
    user_adapter_inst.cache.validation_password_max_length_valid = false;
    user_adapter_inst.cache.validation_email_required_valid = false;
    user_config_set_impl(&g_user_vtable_impl, &user_adapter_inst);

    // 订单管理 域 — 创建适配器并注册
    static order_config_adapter_t order_adapter_inst;
    order_adapter_inst.reader = reader;
    order_adapter_inst.cache.status_values_valid = false;
    order_config_set_impl(&g_order_vtable_impl, &order_adapter_inst);

    // 认证鉴权 域 — 创建适配器并注册
    static auth_config_adapter_t auth_adapter_inst;
    auth_adapter_inst.reader = reader;
    auth_adapter_inst.cache.jwt_token_expiry_seconds_valid = false;
    auth_adapter_inst.cache.password_bcrypt_cost_valid = false;
    auth_config_set_impl(&g_auth_vtable_impl, &auth_adapter_inst);

    // 评价管理 域 — 创建适配器并注册
    static review_config_adapter_t review_adapter_inst;
    review_adapter_inst.reader = reader;
    review_adapter_inst.cache.rating_min_valid = false;
    review_adapter_inst.cache.rating_max_valid = false;
    review_config_set_impl(&g_review_vtable_impl, &review_adapter_inst);
}
