// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

package com.douyinmall.provider;

import com.douyinmall.ports.ConfigReader;
import com.douyinmall.ports.ProductConfig;
import com.douyinmall.ports.CorsConfig;
import com.douyinmall.ports.PaymentConfig;
import com.douyinmall.ports.UserConfig;
import com.douyinmall.ports.OrderConfig;
import com.douyinmall.ports.AuthConfig;
import com.douyinmall.ports.ReviewConfig;

/**
 * BlessStar 配置依赖注入。
 * 业务系统: 抖音商城 (douyin-mall)
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class BlessstarProvider {

	/**
	 * 持有所有域的配置适配器。
	 */
	public static class Adapters {
		private final ProductConfig productConfig;
		private final CorsConfig corsConfig;
		private final PaymentConfig paymentConfig;
		private final UserConfig userConfig;
		private final OrderConfig orderConfig;
		private final AuthConfig authConfig;
		private final ReviewConfig reviewConfig;

		public Adapters(
			ProductConfig productConfig
			CorsConfig corsConfig
			PaymentConfig paymentConfig
			UserConfig userConfig
			OrderConfig orderConfig
			AuthConfig authConfig
			ReviewConfig reviewConfig
		) {
			this.productConfig = productConfig;
			this.corsConfig = corsConfig;
			this.paymentConfig = paymentConfig;
			this.userConfig = userConfig;
			this.orderConfig = orderConfig;
			this.authConfig = authConfig;
			this.reviewConfig = reviewConfig;
		}

		public ProductConfig getProductConfig() {
			return productConfig;
		}
		public CorsConfig getCorsConfig() {
			return corsConfig;
		}
		public PaymentConfig getPaymentConfig() {
			return paymentConfig;
		}
		public UserConfig getUserConfig() {
			return userConfig;
		}
		public OrderConfig getOrderConfig() {
			return orderConfig;
		}
		public AuthConfig getAuthConfig() {
			return authConfig;
		}
		public ReviewConfig getReviewConfig() {
			return reviewConfig;
		}
	}

	/**
	 * 一行实例化所有域配置适配器。
	 * @param reader ConfigReader 实现（如 CachedReader、HTTPReader）
	 * @return 包含所有域 Adapter 的 Adapters 实例
	 */
	public static Adapters provideAdapters(ConfigReader reader) {
		return new Adapters(
			new com.douyinmall.adapter.blessstar.ProductConfigAdapter(reader)
			, new com.douyinmall.adapter.blessstar.CorsConfigAdapter(reader)
			, new com.douyinmall.adapter.blessstar.PaymentConfigAdapter(reader)
			, new com.douyinmall.adapter.blessstar.UserConfigAdapter(reader)
			, new com.douyinmall.adapter.blessstar.OrderConfigAdapter(reader)
			, new com.douyinmall.adapter.blessstar.AuthConfigAdapter(reader)
			, new com.douyinmall.adapter.blessstar.ReviewConfigAdapter(reader)
		);
	}
}
