// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: config-schema.yaml
// Business System: livedesign (livedesign)

// Package ports 提供业务系统的配置读取接口。
// 所有 Port 接口定义在此包中，业务代码仅依赖此包。
// 请勿手动修改 — 由 blessstar-codegen 自动生成

/**
 * ConfigReader 是配置读取接口，业务方自行选择实现方式。
 * 内置实现包括：CachedReader（秒级轮询缓存）、EnvReader（环境变量）、FileReader（本地文件）等。
 *
 * 实现类通过环境变量 BLESSSTAR_ENDPOINT 获取 Electron 地址（HTTPReader 场景）。
 * 初始化失败时不得阻塞进程，由 adapter 的三阶段降级兜底。
 *
 * get 返回 unknown 以便 adapter 进行类型断言（与三阶段降级兼容）。
 * 常见返回类型：number, boolean, string, string[]。
 */
export interface ConfigReader {
  /**
   * 读取一个配置值。
   * @param path 配置的完整注册路径（如 "/config/livedesign/avatar/position_x"）
   * @returns 配置值（可直接类型断言）或 undefined
   */
  get(path: string): Promise<unknown>;
}
