// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.adapter.blessstar;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import com.musicwebsite.ports.ConfigReader;
import com.musicwebsite.ports.CorsConfig;

/**
 * 安全策略域配置的 BlessStar 适配器
 * 业务系统: 音乐网站 (music-website)
 * 内置三阶段降级: ConfigReader实时查询 -> LastKnownGood缓存 -> 硬编码默认值
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class CorsConfigAdapter implements CorsConfig {

	private final ConfigReader reader;
	private final Map<String, Object> lastKnownCache = new ConcurrentHashMap<>();
	private final Map<String, Object> hardcodedDefaults;

	/**
	 * 创建 CorsConfigAdapter 适配器实例
	 * @param reader 配置读取器，由业务方注入（可为 CachedReader、HTTPReader 等实现）
	 */
	public CorsConfigAdapter(ConfigReader reader) {
		this.reader = reader;
		this.hardcodedDefaults = new ConcurrentHashMap<>();
		this.hardcodedDefaults.put("getAllowed-origins", java.util.List.of("http://localhost:3000", "http://127.0.0.1:3000", "http://localhost:8080", "http://127.0.0.1:8080", "http://localhost:8081", "http://127.0.0.1:8081"));
	}

	@Override
	public java.util.List<String> getAllowed-origins() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/music-website/cors/allowed-origins");
			if (val != null) {
				lastKnownCache.put("getAllowed-origins", val);
				return (java.util.List<String>) val;
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getAllowed-origins");
		if (cached != null) {
			return (java.util.List<String>) cached;
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getAllowed-origins");
		return (java.util.List<String>) fallback;
	}

}
