// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.adapter.blessstar;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import com.musicwebsite.ports.ConfigReader;
import com.musicwebsite.ports.密码重置Config;

/**
 * 密码重置域配置的 BlessStar 适配器
 * 业务系统: 音乐网站 (music-website)
 * 内置三阶段降级: ConfigReader实时查询 -> LastKnownGood缓存 -> 硬编码默认值
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class 密码重置ConfigAdapter implements 密码重置Config {

	private final ConfigReader reader;
	private final Map<String, Object> lastKnownCache = new ConcurrentHashMap<>();
	private final Map<String, Object> hardcodedDefaults;

	/**
	 * 创建 密码重置ConfigAdapter 适配器实例
	 * @param reader 配置读取器，由业务方注入（可为 CachedReader、HTTPReader 等实现）
	 */
	public 密码重置ConfigAdapter(ConfigReader reader) {
		this.reader = reader;
		this.hardcodedDefaults = new ConcurrentHashMap<>();
		this.hardcodedDefaults.put("getCode-ttl-minutes", 10);
		this.hardcodedDefaults.put("getSend-cooldown-seconds", 15);
		this.hardcodedDefaults.put("getMock-without-mail", true);
	}

	@Override
	public int getCode-ttl-minutes() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/music-website/password-reset/code-ttl-minutes");
			if (val != null) {
				lastKnownCache.put("getCode-ttl-minutes", val);
				return ((Number) val).intValue();
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getCode-ttl-minutes");
		if (cached != null) {
			return ((Number) cached).intValue();
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getCode-ttl-minutes");
		return ((Number) fallback).intValue();
	}

	@Override
	public int getSend-cooldown-seconds() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/music-website/password-reset/send-cooldown-seconds");
			if (val != null) {
				lastKnownCache.put("getSend-cooldown-seconds", val);
				return ((Number) val).intValue();
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getSend-cooldown-seconds");
		if (cached != null) {
			return ((Number) cached).intValue();
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getSend-cooldown-seconds");
		return ((Number) fallback).intValue();
	}

	@Override
	public boolean getMock-without-mail() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/music-website/password-reset/mock-without-mail");
			if (val != null) {
				lastKnownCache.put("getMock-without-mail", val);
				return (Boolean) val;
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getMock-without-mail");
		if (cached != null) {
			return (Boolean) cached;
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getMock-without-mail");
		return (Boolean) fallback;
	}

}
