// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.adapter.blessstar;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import com.musicwebsite.ports.ConfigReader;
import com.musicwebsite.ports.登录安全Config;

/**
 * 登录安全域配置的 BlessStar 适配器
 * 业务系统: 音乐网站 (music-website)
 * 内置三阶段降级: ConfigReader实时查询 -> LastKnownGood缓存 -> 硬编码默认值
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class 登录安全ConfigAdapter implements 登录安全Config {

	private final ConfigReader reader;
	private final Map<String, Object> lastKnownCache = new ConcurrentHashMap<>();
	private final Map<String, Object> hardcodedDefaults;

	/**
	 * 创建 登录安全ConfigAdapter 适配器实例
	 * @param reader 配置读取器，由业务方注入（可为 CachedReader、HTTPReader 等实现）
	 */
	public 登录安全ConfigAdapter(ConfigReader reader) {
		this.reader = reader;
		this.hardcodedDefaults = new ConcurrentHashMap<>();
		this.hardcodedDefaults.put("getMax-failed-attempts", 5);
		this.hardcodedDefaults.put("getLock-minutes", 10);
	}

	@Override
	public int getMax-failed-attempts() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/music-website/login/max-failed-attempts");
			if (val != null) {
				lastKnownCache.put("getMax-failed-attempts", val);
				return ((Number) val).intValue();
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getMax-failed-attempts");
		if (cached != null) {
			return ((Number) cached).intValue();
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getMax-failed-attempts");
		return ((Number) fallback).intValue();
	}

	@Override
	public int getLock-minutes() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/music-website/login/lock-minutes");
			if (val != null) {
				lastKnownCache.put("getLock-minutes", val);
				return ((Number) val).intValue();
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getLock-minutes");
		if (cached != null) {
			return ((Number) cached).intValue();
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getLock-minutes");
		return ((Number) fallback).intValue();
	}

}
