// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 音乐网站 (music-website)

package com.musicwebsite.adapter.blessstar;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import com.musicwebsite.ports.ConfigReader;
import com.musicwebsite.ports.缓存配置Config;

/**
 * 缓存配置域配置的 BlessStar 适配器
 * 业务系统: 音乐网站 (music-website)
 * 内置三阶段降级: ConfigReader实时查询 -> LastKnownGood缓存 -> 硬编码默认值
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */
public class 缓存配置ConfigAdapter implements 缓存配置Config {

	private final ConfigReader reader;
	private final Map<String, Object> lastKnownCache = new ConcurrentHashMap<>();
	private final Map<String, Object> hardcodedDefaults;

	/**
	 * 创建 缓存配置ConfigAdapter 适配器实例
	 * @param reader 配置读取器，由业务方注入（可为 CachedReader、HTTPReader 等实现）
	 */
	public 缓存配置ConfigAdapter(ConfigReader reader) {
		this.reader = reader;
		this.hardcodedDefaults = new ConcurrentHashMap<>();
		this.hardcodedDefaults.put("getRedisHost", "127.0.0.1");
		this.hardcodedDefaults.put("getRedisPort", 6379);
		this.hardcodedDefaults.put("getRedisTimeout", 1800000L);
	}

	@Override
	public String getRedisHost() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/music-website/redis/host");
			if (val != null) {
				lastKnownCache.put("getRedisHost", val);
				return (String) val;
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getRedisHost");
		if (cached != null) {
			return (String) cached;
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getRedisHost");
		return (String) fallback;
	}

	@Override
	public int getRedisPort() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/music-website/redis/port");
			if (val != null) {
				lastKnownCache.put("getRedisPort", val);
				return ((Number) val).intValue();
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getRedisPort");
		if (cached != null) {
			return ((Number) cached).intValue();
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getRedisPort");
		return ((Number) fallback).intValue();
	}

	@Override
	public long getRedisTimeout() throws Exception {
		// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
		try {
			Object val = reader.get("/config/music-website/redis/timeout");
			if (val != null) {
				lastKnownCache.put("getRedisTimeout", val);
				return ((Number) val).longValue();
			}
		} catch (Exception e) {
			// 读取失败，继续降级
		}

		// 第2阶段: 降级到 Last Known Good 缓存
		Object cached = lastKnownCache.get("getRedisTimeout");
		if (cached != null) {
			return ((Number) cached).longValue();
		}

		// 第3阶段: 极冷启动 — 返回硬编码默认值
		Object fallback = hardcodedDefaults.get("getRedisTimeout");
		return ((Number) fallback).longValue();
	}

}
