# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package adapter_blessstar — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: API 配置
# 请勿手动修改 — 由 blessstar-codegen 自动生成

from typing import Any, Dict
from contextlib import AbstractContextManager
from ports.config_reader import ConfigReader
from ports.api配置 import API配置Config


class API配置ConfigAdapter(API配置Config):
    """API 配置域配置的 BlessStar 适配器
    内置三阶段降级: ConfigReader实时查询 → 缓存 → 硬编码默认值
    """

    def __init__(self, reader: ConfigReader) -> None:
        self._reader = reader
        self._cache: Dict[str, Any] = {}
        self._defaults: Dict[str, Any] = {
            "API_V1_STR": "/api/v1",
        }

    def API_V1_STR(self, ctx: AbstractContextManager) -> str:
        path = "/config/full-stack-fastapi/api/v1_str"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["API_V1_STR"] = val
            return str(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "API_V1_STR" in self._cache:
            return str(self._cache["API_V1_STR"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return str(self._defaults["API_V1_STR"])

