# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package adapter_blessstar — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 认证鉴权
# 请勿手动修改 — 由 blessstar-codegen 自动生成

from typing import Any, Dict
from contextlib import AbstractContextManager
from ports.config_reader import ConfigReader
from ports.auth import AuthConfig


class AuthConfigAdapter(AuthConfig):
    """认证鉴权域配置的 BlessStar 适配器
    内置三阶段降级: ConfigReader实时查询 → 缓存 → 硬编码默认值
    """

    def __init__(self, reader: ConfigReader) -> None:
        self._reader = reader
        self._cache: Dict[str, Any] = {}
        self._defaults: Dict[str, Any] = {
            "ACCESS_TOKEN_EXPIRE_MINUTES": 11520,
        }

    def ACCESS_TOKEN_EXPIRE_MINUTES(self, ctx: AbstractContextManager) -> int:
        path = "/config/full-stack-fastapi/auth/access_token_expire_minutes"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["ACCESS_TOKEN_EXPIRE_MINUTES"] = val
            return int(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "ACCESS_TOKEN_EXPIRE_MINUTES" in self._cache:
            return int(self._cache["ACCESS_TOKEN_EXPIRE_MINUTES"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return int(self._defaults["ACCESS_TOKEN_EXPIRE_MINUTES"])

