# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package adapter_blessstar — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 安全策略
# 请勿手动修改 — 由 blessstar-codegen 自动生成

from typing import Any, Dict
from contextlib import AbstractContextManager
from ports.config_reader import ConfigReader
from ports.cors import CorsConfig


class CorsConfigAdapter(CorsConfig):
    """安全策略域配置的 BlessStar 适配器
    内置三阶段降级: ConfigReader实时查询 → 缓存 → 硬编码默认值
    """

    def __init__(self, reader: ConfigReader) -> None:
        self._reader = reader
        self._cache: Dict[str, Any] = {}
        self._defaults: Dict[str, Any] = {
            "BACKEND_CORS_ORIGINS": ["http://localhost", "http://localhost:5173", "https://localhost", "https://localhost:5173", "http://localhost.tiangolo.com"],
            "FRONTEND_HOST": "http://localhost:5173",
        }

    def BACKEND_CORS_ORIGINS(self, ctx: AbstractContextManager) -> list[str]:
        path = "/config/full-stack-fastapi/cors/allowed_origins"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["BACKEND_CORS_ORIGINS"] = val
            return list[str](val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "BACKEND_CORS_ORIGINS" in self._cache:
            return list[str](self._cache["BACKEND_CORS_ORIGINS"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return list[str](self._defaults["BACKEND_CORS_ORIGINS"])

    def FRONTEND_HOST(self, ctx: AbstractContextManager) -> str:
        path = "/config/full-stack-fastapi/cors/frontend_host"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["FRONTEND_HOST"] = val
            return str(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "FRONTEND_HOST" in self._cache:
            return str(self._cache["FRONTEND_HOST"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return str(self._defaults["FRONTEND_HOST"])

