# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package adapter_blessstar — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 数据库配置
# 请勿手动修改 — 由 blessstar-codegen 自动生成

from typing import Any, Dict
from contextlib import AbstractContextManager
from ports.config_reader import ConfigReader
from ports.数据库配置 import 数据库配置Config


class 数据库配置ConfigAdapter(数据库配置Config):
    """数据库配置域配置的 BlessStar 适配器
    内置三阶段降级: ConfigReader实时查询 → 缓存 → 硬编码默认值
    """

    def __init__(self, reader: ConfigReader) -> None:
        self._reader = reader
        self._cache: Dict[str, Any] = {}
        self._defaults: Dict[str, Any] = {
            "POSTGRES_SERVER": "localhost",
            "POSTGRES_PORT": 5432,
            "POSTGRES_DB": "app",
            "POSTGRES_USER": "postgres",
        }

    def POSTGRES_SERVER(self, ctx: AbstractContextManager) -> str:
        path = "/config/full-stack-fastapi/database/server"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["POSTGRES_SERVER"] = val
            return str(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "POSTGRES_SERVER" in self._cache:
            return str(self._cache["POSTGRES_SERVER"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return str(self._defaults["POSTGRES_SERVER"])

    def POSTGRES_PORT(self, ctx: AbstractContextManager) -> int:
        path = "/config/full-stack-fastapi/database/port"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["POSTGRES_PORT"] = val
            return int(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "POSTGRES_PORT" in self._cache:
            return int(self._cache["POSTGRES_PORT"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return int(self._defaults["POSTGRES_PORT"])

    def POSTGRES_DB(self, ctx: AbstractContextManager) -> str:
        path = "/config/full-stack-fastapi/database/dbname"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["POSTGRES_DB"] = val
            return str(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "POSTGRES_DB" in self._cache:
            return str(self._cache["POSTGRES_DB"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return str(self._defaults["POSTGRES_DB"])

    def POSTGRES_USER(self, ctx: AbstractContextManager) -> str:
        path = "/config/full-stack-fastapi/database/user"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["POSTGRES_USER"] = val
            return str(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "POSTGRES_USER" in self._cache:
            return str(self._cache["POSTGRES_USER"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return str(self._defaults["POSTGRES_USER"])

