# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: Full Stack FastAPI (full-stack-fastapi)

# Package adapter_blessstar — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: Full Stack FastAPI (full-stack-fastapi)
# 领域: 邮件服务
# 请勿手动修改 — 由 blessstar-codegen 自动生成

from typing import Any, Dict
from contextlib import AbstractContextManager
from ports.config_reader import ConfigReader
from ports.邮件服务 import 邮件服务Config


class 邮件服务ConfigAdapter(邮件服务Config):
    """邮件服务域配置的 BlessStar 适配器
    内置三阶段降级: ConfigReader实时查询 → 缓存 → 硬编码默认值
    """

    def __init__(self, reader: ConfigReader) -> None:
        self._reader = reader
        self._cache: Dict[str, Any] = {}
        self._defaults: Dict[str, Any] = {
            "SMTP_HOST": "\"\"",
            "SMTP_PORT": 587,
            "SMTP_TLS": True,
            "EMAILS_FROM_EMAIL": "info@example.com",
            "EMAIL_RESET_TOKEN_EXPIRE_HOURS": 48,
        }

    def SMTP_HOST(self, ctx: AbstractContextManager) -> str:
        path = "/config/full-stack-fastapi/email/smtp_host"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["SMTP_HOST"] = val
            return str(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "SMTP_HOST" in self._cache:
            return str(self._cache["SMTP_HOST"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return str(self._defaults["SMTP_HOST"])

    def SMTP_PORT(self, ctx: AbstractContextManager) -> int:
        path = "/config/full-stack-fastapi/email/smtp_port"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["SMTP_PORT"] = val
            return int(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "SMTP_PORT" in self._cache:
            return int(self._cache["SMTP_PORT"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return int(self._defaults["SMTP_PORT"])

    def SMTP_TLS(self, ctx: AbstractContextManager) -> bool:
        path = "/config/full-stack-fastapi/email/smtp_tls"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["SMTP_TLS"] = val
            return bool(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "SMTP_TLS" in self._cache:
            return bool(self._cache["SMTP_TLS"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return bool(self._defaults["SMTP_TLS"])

    def EMAILS_FROM_EMAIL(self, ctx: AbstractContextManager) -> str:
        path = "/config/full-stack-fastapi/email/from_email"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["EMAILS_FROM_EMAIL"] = val
            return str(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "EMAILS_FROM_EMAIL" in self._cache:
            return str(self._cache["EMAILS_FROM_EMAIL"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return str(self._defaults["EMAILS_FROM_EMAIL"])

    def EMAIL_RESET_TOKEN_EXPIRE_HOURS(self, ctx: AbstractContextManager) -> int:
        path = "/config/full-stack-fastapi/email/reset_token_expire_hours"
        # Stage 1: ConfigReader 实时查询
        try:
            val = self._reader.get(ctx, path)
            self._cache["EMAIL_RESET_TOKEN_EXPIRE_HOURS"] = val
            return int(val)
        except Exception:
            pass
        # Stage 2: 降级到 Last Known Good 缓存
        if "EMAIL_RESET_TOKEN_EXPIRE_HOURS" in self._cache:
            return int(self._cache["EMAIL_RESET_TOKEN_EXPIRE_HOURS"])
        # Stage 3: 极冷启动 — 返回硬编码默认值
        return int(self._defaults["EMAIL_RESET_TOKEN_EXPIRE_HOURS"])

