#!/usr/bin/env python3
"""
Purity gate verification tool for BlessStar kernel.
Verifies that kernel directory matches expected hash manifest.
"""

import argparse
import hashlib
import os
import sys
from pathlib import Path


def compute_file_hash(filepath: Path, hash_algo: str = "sha256") -> str:
    h = hashlib.new(hash_algo)
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def scan_directory(root: Path, exclude_patterns=None) -> dict:
    if exclude_patterns is None:
        exclude_patterns = []
    hashes = {}
    for filepath in sorted(root.rglob("*")):
        if filepath.is_file():
            excluded = False
            rel_path = filepath.relative_to(root)
            for pattern in exclude_patterns:
                if rel_path.match(pattern) or pattern in str(rel_path):
                    excluded = True
                    break
            if excluded:
                continue
            file_hash = compute_file_hash(filepath)
            # Always POSIX-style keys so manifest lines match on Windows vs Linux.
            hashes[rel_path.as_posix()] = file_hash
    return hashes


def load_manifest(manifest_path: Path) -> dict:
    hashes = {}
    with open(manifest_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split(None, 1)
            if len(parts) == 2:
                file_hash, filepath = parts
                hashes[Path(filepath).as_posix()] = file_hash
    return hashes


def verify_purity(kernel_root: Path, manifest_path: Path) -> bool:
    kernel_root = kernel_root.resolve()
    manifest_path = manifest_path.resolve()
    print(f"Verifying purity of: {kernel_root}")
    print(f"Using manifest: {manifest_path}")
    expected_hashes = load_manifest(manifest_path)
    actual_hashes = scan_directory(kernel_root)
    # Manifest file usually lives under the verified tree but is not self-listed.
    try:
        manifest_rel = manifest_path.relative_to(kernel_root).as_posix()
        actual_hashes.pop(manifest_rel, None)
    except ValueError:
        pass
    errors = []
    for filepath, expected_hash in expected_hashes.items():
        if filepath not in actual_hashes:
            errors.append(f"Missing file: {filepath}")
        elif actual_hashes[filepath] != expected_hash:
            errors.append(f"Hash mismatch: {filepath}")
    for filepath in actual_hashes:
        if filepath not in expected_hashes:
            errors.append(f"Extra file: {filepath}")
    if errors:
        print("\nPurity check FAILED:")
        for error in errors:
            print(f"  {error}")
        return False
    else:
        print("\nPurity check PASSED")
        print(f"   Verified {len(expected_hashes)} files")
        return True


def generate_manifest(kernel_root: Path, output_path: Path):
    print(f"Generating manifest for: {kernel_root}")
    hashes = scan_directory(kernel_root)
    with open(output_path, "w") as f:
        f.write("# BlessStar Kernel Manifest\n")
        f.write("# Generated by tools/purity/verify_manifest.py\n\n")
        for filepath, file_hash in sorted(hashes.items()):
            f.write(f"{file_hash}  {filepath}\n")
    print(f"Manifest written to: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="BlessStar Purity Gate")
    subparsers = parser.add_subparsers(dest="command", required=True)
    verify_parser = subparsers.add_parser("verify", help="Verify kernel purity")
    verify_parser.add_argument("--kernel", required=True, help="Kernel directory")
    verify_parser.add_argument("--manifest", required=True, help="Manifest file")
    gen_parser = subparsers.add_parser("generate", help="Generate manifest")
    gen_parser.add_argument("--kernel", required=True, help="Kernel directory")
    gen_parser.add_argument("--output", required=True, help="Output manifest file")
    args = parser.parse_args()
    if args.command == "verify":
        kernel_root = Path(args.kernel)
        manifest_path = Path(args.manifest)
        if not kernel_root.exists():
            print(f"Error: Kernel directory not found: {kernel_root}", file=sys.stderr)
            sys.exit(1)
        if not manifest_path.exists():
            print(f"Error: Manifest not found: {manifest_path}", file=sys.stderr)
            sys.exit(1)
        success = verify_purity(kernel_root, manifest_path)
        sys.exit(0 if success else 1)
    elif args.command == "generate":
        kernel_root = Path(args.kernel)
        output_path = Path(args.output)
        if not kernel_root.exists():
            print(f"Error: Kernel directory not found: {kernel_root}", file=sys.stderr)
            sys.exit(1)
        generate_manifest(kernel_root, output_path)


if __name__ == "__main__":
    main()
