# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: 抖音商城 (douyin-mall)

# Package ports — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: 抖音商城 (douyin-mall)
# 领域: 商品管理
# 请勿手动修改 — 由 blessstar-codegen 自动生成
# Source: manifest.json

from typing import Protocol
from contextlib import AbstractContextManager


class ProductConfig(Protocol):
    """商品管理域配置接口"""

    def status_values(self, ctx: AbstractContextManager) -> str:
        """商品状态 (product.status.values)
        描述: 商品生命周期状态枚举。
        建议值: 当前支持：1=在售，0=下架，-1=已删除。可扩展预售等状态但需配套逻辑
        类型: ENUM
        """
        ...

