// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: config-schema.yaml
// Business System: douyin-mall (douyin-mall)

// Package douyin_mall 自动生成于 BlessStar 配置依赖注入
// 业务系统: douyin-mall (douyin-mall)
// 请勿手动修改 — 由 blessstar-codegen 自动生成

package douyin_mall

import (
	"douyin-mall/ports"
	"douyin-mall/adapters/blessstar"
)

// Adapters 持有所有域的配置适配器
type Adapters struct {
}

// ProvideBlessStarAdapters 一行实例化所有域配置适配器
// 注入 ConfigReader 后返回所有域的 Port 实现
// reader 由业务方提供（可为 CachedReader、HTTPReader、EnvReader 等实现）
func ProvideBlessStarAdapters(reader ports.ConfigReader) *Adapters {
	return &Adapters{
	}
}

