// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

// Package adapter_blessstar 自动生成于 BlessStar 配置端口-适配器
// 业务系统: 抖音商城 (douyin-mall)
// 领域: 用户管理
// 请勿手动修改 — 由 blessstar-codegen 自动生成

package adapter_blessstar

import (
	"context"
	"sync"

	"douyin-mall/ports"
)

// UserConfigAdapter 用户管理 域配置的 BlessStar 适配器
// 内置三阶段降级: ConfigReader实时查询 → LastKnownGood缓存 → 硬编码默认值
type UserConfigAdapter struct {
	reader          ports.ConfigReader
	lastKnownCache  sync.Map
	hardcodedDefaults  map[string]interface{}
}

// NewUserConfigAdapter 创建 UserConfigAdapter 适配器实例
// reader 参数是配置读取器，由业务方注入（可为 CachedReader、HTTPReader 等实现）
func NewUserConfigAdapter(reader ports.ConfigReader) ports.UserConfig {
	return &UserConfigAdapter{
		reader: reader,
		hardcodedDefaults: map[string]interface{}{
			"RoleValues": "[\"user\",\"admin\"]",
			"StatusValues": "{\"1\":\"active\",\"0\":\"inactive\",\"-1\":\"deleted\"}",
			"RegistrationDefaultRole": "user",
			"RegistrationDefaultStatus": int32(1),
			"ValidationUsernameMinLength": int32(3),
			"ValidationUsernameMaxLength": int32(50),
			"ValidationPasswordMinLength": int32(6),
			"ValidationPasswordMaxLength": int32(50),
			"ValidationEmailRequired": true,
		},
	}
}

func (a *UserConfigAdapter) RoleValues(ctx context.Context) (string, error) {
	// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
	val, err := a.reader.Get(ctx, "/config/douyin-mall/user/role/values")
	if err == nil {
		a.lastKnownCache.Store("RoleValues", val)
		return val.(string), nil
	}

	// 第2阶段: 降级到 Last Known Good 缓存
	if cached, ok := a.lastKnownCache.Load("RoleValues"); ok {
		return cached.(string), nil
	}

	// 第3阶段: 极冷启动 — 返回硬编码默认值
	return a.hardcodedDefaults["RoleValues"].(string), nil
}

func (a *UserConfigAdapter) StatusValues(ctx context.Context) (string, error) {
	// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
	val, err := a.reader.Get(ctx, "/config/douyin-mall/user/status/values")
	if err == nil {
		a.lastKnownCache.Store("StatusValues", val)
		return val.(string), nil
	}

	// 第2阶段: 降级到 Last Known Good 缓存
	if cached, ok := a.lastKnownCache.Load("StatusValues"); ok {
		return cached.(string), nil
	}

	// 第3阶段: 极冷启动 — 返回硬编码默认值
	return a.hardcodedDefaults["StatusValues"].(string), nil
}

func (a *UserConfigAdapter) RegistrationDefaultRole(ctx context.Context) (string, error) {
	// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
	val, err := a.reader.Get(ctx, "/config/douyin-mall/user/registration/default_role")
	if err == nil {
		a.lastKnownCache.Store("RegistrationDefaultRole", val)
		return val.(string), nil
	}

	// 第2阶段: 降级到 Last Known Good 缓存
	if cached, ok := a.lastKnownCache.Load("RegistrationDefaultRole"); ok {
		return cached.(string), nil
	}

	// 第3阶段: 极冷启动 — 返回硬编码默认值
	return a.hardcodedDefaults["RegistrationDefaultRole"].(string), nil
}

func (a *UserConfigAdapter) RegistrationDefaultStatus(ctx context.Context) (int32, error) {
	// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
	val, err := a.reader.Get(ctx, "/config/douyin-mall/user/registration/default_status")
	if err == nil {
		a.lastKnownCache.Store("RegistrationDefaultStatus", val)
		return val.(int32), nil
	}

	// 第2阶段: 降级到 Last Known Good 缓存
	if cached, ok := a.lastKnownCache.Load("RegistrationDefaultStatus"); ok {
		return cached.(int32), nil
	}

	// 第3阶段: 极冷启动 — 返回硬编码默认值
	return a.hardcodedDefaults["RegistrationDefaultStatus"].(int32), nil
}

func (a *UserConfigAdapter) ValidationUsernameMinLength(ctx context.Context) (int32, error) {
	// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
	val, err := a.reader.Get(ctx, "/config/douyin-mall/user/validation/username_min_length")
	if err == nil {
		a.lastKnownCache.Store("ValidationUsernameMinLength", val)
		return val.(int32), nil
	}

	// 第2阶段: 降级到 Last Known Good 缓存
	if cached, ok := a.lastKnownCache.Load("ValidationUsernameMinLength"); ok {
		return cached.(int32), nil
	}

	// 第3阶段: 极冷启动 — 返回硬编码默认值
	return a.hardcodedDefaults["ValidationUsernameMinLength"].(int32), nil
}

func (a *UserConfigAdapter) ValidationUsernameMaxLength(ctx context.Context) (int32, error) {
	// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
	val, err := a.reader.Get(ctx, "/config/douyin-mall/user/validation/username_max_length")
	if err == nil {
		a.lastKnownCache.Store("ValidationUsernameMaxLength", val)
		return val.(int32), nil
	}

	// 第2阶段: 降级到 Last Known Good 缓存
	if cached, ok := a.lastKnownCache.Load("ValidationUsernameMaxLength"); ok {
		return cached.(int32), nil
	}

	// 第3阶段: 极冷启动 — 返回硬编码默认值
	return a.hardcodedDefaults["ValidationUsernameMaxLength"].(int32), nil
}

func (a *UserConfigAdapter) ValidationPasswordMinLength(ctx context.Context) (int32, error) {
	// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
	val, err := a.reader.Get(ctx, "/config/douyin-mall/user/validation/password_min_length")
	if err == nil {
		a.lastKnownCache.Store("ValidationPasswordMinLength", val)
		return val.(int32), nil
	}

	// 第2阶段: 降级到 Last Known Good 缓存
	if cached, ok := a.lastKnownCache.Load("ValidationPasswordMinLength"); ok {
		return cached.(int32), nil
	}

	// 第3阶段: 极冷启动 — 返回硬编码默认值
	return a.hardcodedDefaults["ValidationPasswordMinLength"].(int32), nil
}

func (a *UserConfigAdapter) ValidationPasswordMaxLength(ctx context.Context) (int32, error) {
	// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
	val, err := a.reader.Get(ctx, "/config/douyin-mall/user/validation/password_max_length")
	if err == nil {
		a.lastKnownCache.Store("ValidationPasswordMaxLength", val)
		return val.(int32), nil
	}

	// 第2阶段: 降级到 Last Known Good 缓存
	if cached, ok := a.lastKnownCache.Load("ValidationPasswordMaxLength"); ok {
		return cached.(int32), nil
	}

	// 第3阶段: 极冷启动 — 返回硬编码默认值
	return a.hardcodedDefaults["ValidationPasswordMaxLength"].(int32), nil
}

func (a *UserConfigAdapter) ValidationEmailRequired(ctx context.Context) (bool, error) {
	// 第1阶段: ConfigReader 实时查询（SHM / HTTP / 环境变量等）
	val, err := a.reader.Get(ctx, "/config/douyin-mall/user/validation/email_required")
	if err == nil {
		a.lastKnownCache.Store("ValidationEmailRequired", val)
		return val.(bool), nil
	}

	// 第2阶段: 降级到 Last Known Good 缓存
	if cached, ok := a.lastKnownCache.Load("ValidationEmailRequired"); ok {
		return cached.(bool), nil
	}

	// 第3阶段: 极冷启动 — 返回硬编码默认值
	return a.hardcodedDefaults["ValidationEmailRequired"].(bool), nil
}

