# Code generated by blessstar-codegen. DO NOT EDIT.
# Source: manifest.json
# Business System: 抖音商城 (douyin-mall)

# Package ports — 自动生成于 BlessStar 配置端口-适配器
# 业务系统: 抖音商城 (douyin-mall)
# 领域: 安全策略
# 请勿手动修改 — 由 blessstar-codegen 自动生成
# Source: manifest.json

from typing import Protocol
from contextlib import AbstractContextManager


class CorsConfig(Protocol):
    """安全策略域配置接口"""

    def allowed_origins(self, ctx: AbstractContextManager) -> list[str]:
        """跨域白名单 (cors.allowed_origins)
        描述: 允许跨域访问的域名来源列表。
        建议值: 生产环境禁止使用*。推荐格式：["https://mall.douyin.com","https://admin.douyin.com"]
        类型: ARR
        """
        ...

