// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置端口 — C 头文件
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 支付管理
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */

#ifndef DOUYIN_MALL_PORTS_PAYMENT_H
#define DOUYIN_MALL_PORTS_PAYMENT_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * 支付管理 域配置接口
 * 通过 vtable + setter 模式注入具体实现
 * 业务代码通过外观函数访问配置，无需关心底层实现
 */

// PaymentConfig — 函数指针表
typedef struct {
    const char* (*type_values)(void* impl_ctx);
    const char* (*record_status_values)(void* impl_ctx);
} payment_config_vtable_t;

// 全局 setter — 由 adapter 层在初始化时调用
void payment_config_set_impl(const payment_config_vtable_t* vtable, void* impl_ctx);

// 业务代码调用的外观函数
/**
 * 支付方式 (payment.type.values)
 * 描述: 平台支持的支付方式枚举。
 * 建议值: 当前支持：1=支付宝，2=微信支付，3=信用卡。新增需评估支付通道成本和技术对接周期
 * 类型: ENUM
 */
const char* payment_config_type_values();
/**
 * 支付记录状态 (payment.record_status.values)
 * 描述: 支付记录处理状态枚举。
 * 建议值: 当前支持：0=待处理→1=成功/2=失败，3=已退款（从成功状态转入）
 * 类型: ENUM
 */
const char* payment_config_record_status_values();

#ifdef __cplusplus
}
#endif

#endif /* DOUYIN_MALL_PORTS_PAYMENT_H */
