// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置端口 — C 头文件
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 评价管理
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */

#ifndef DOUYIN_MALL_PORTS_REVIEW_H
#define DOUYIN_MALL_PORTS_REVIEW_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * 评价管理 域配置接口
 * 通过 vtable + setter 模式注入具体实现
 * 业务代码通过外观函数访问配置，无需关心底层实现
 */

// ReviewConfig — 函数指针表
typedef struct {
    int32_t (*rating_min)(void* impl_ctx);
    int32_t (*rating_max)(void* impl_ctx);
} review_config_vtable_t;

// 全局 setter — 由 adapter 层在初始化时调用
void review_config_set_impl(const review_config_vtable_t* vtable, void* impl_ctx);

// 业务代码调用的外观函数
/**
 * 评分下限 (review.rating.min)
 * 描述: 商品评论评分的最低分值。
 * 建议值: 1~5，推荐与max配合使用确保min<max
 * 类型: I32
 */
int32_t review_config_rating_min();
/**
 * 评分上限 (review.rating.max)
 * 描述: 商品评论评分的最高分值。
 * 建议值: 1~10，推荐与min配合使用。当前为五星制(5)，如需更多粒度可改为10分制
 * 类型: I32
 */
int32_t review_config_rating_max();

#ifdef __cplusplus
}
#endif

#endif /* DOUYIN_MALL_PORTS_REVIEW_H */
