// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置端口 — C 头文件
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 用户管理
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */

#ifndef DOUYIN_MALL_PORTS_USER_H
#define DOUYIN_MALL_PORTS_USER_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * 用户管理 域配置接口
 * 通过 vtable + setter 模式注入具体实现
 * 业务代码通过外观函数访问配置，无需关心底层实现
 */

// UserConfig — 函数指针表
typedef struct {
    const char* (*role_values)(void* impl_ctx);
    const char* (*status_values)(void* impl_ctx);
    const char* (*registration_default_role)(void* impl_ctx);
    int32_t (*registration_default_status)(void* impl_ctx);
    int32_t (*validation_username_min_length)(void* impl_ctx);
    int32_t (*validation_username_max_length)(void* impl_ctx);
    int32_t (*validation_password_min_length)(void* impl_ctx);
    int32_t (*validation_password_max_length)(void* impl_ctx);
    bool (*validation_email_required)(void* impl_ctx);
} user_config_vtable_t;

// 全局 setter — 由 adapter 层在初始化时调用
void user_config_set_impl(const user_config_vtable_t* vtable, void* impl_ctx);

// 业务代码调用的外观函数
/**
 * 用户角色 (user.role.values)
 * 描述: 平台用户角色枚举定义，决定用户在系统中的权限等级。
 * 建议值: 当前支持 user, admin。如需扩展可新增如 merchant,客服等角色
 * 类型: ENUM
 */
const char* user_config_role_values();
/**
 * 用户状态 (user.status.values)
 * 描述: 用户账号状态枚举定义。1=正常，0=停用，-1=已删除。
 * 建议值: 当前支持 active(1)/inactive(0)/deleted(-1)。建议保留-1作为删除标记
 * 类型: ENUM
 */
const char* user_config_status_values();
/**
 * 默认角色 (user.registration.default_role)
 * 描述: 新用户注册时默认分配的角色。
 * 建议值: 必须为 user.role.values 中定义的值，当前有效值：user, admin
 * 类型: STR
 */
const char* user_config_registration_default_role();
/**
 * 默认状态 (user.registration.default_status)
 * 描述: 新用户注册成功后的默认账号状态。1=正常激活。
 * 建议值: 必须为 user.status.values 中定义的值。1=正常激活，0=停用（需额外激活）
 * 类型: I32
 */
int32_t user_config_registration_default_status();
/**
 * 用户名最小长度 (user.validation.username_min_length)
 * 描述: 用户名允许的最小字符数。
 * 建议值: 1~20，推荐步长1。建议不低于2
 * 类型: I32
 */
int32_t user_config_validation_username_min_length();
/**
 * 用户名最大长度 (user.validation.username_max_length)
 * 描述: 用户名允许的最大字符数，与数据库varchar(50)一致。
 * 建议值: 10~50，推荐步长5。建议不超过数据库字段长度（当前50）
 * 类型: I32
 */
int32_t user_config_validation_username_max_length();
/**
 * 密码最小长度 (user.validation.password_min_length)
 * 描述: 密码允许的最小字符数。
 * 建议值: 6~20，推荐步长1。建议不低于6
 * 类型: I32
 */
int32_t user_config_validation_password_min_length();
/**
 * 密码最大长度 (user.validation.password_max_length)
 * 描述: 密码允许的最大字符数。
 * 建议值: 20~72，推荐步长5。建议不超过72（bcrypt算法输入上限）
 * 类型: I32
 */
int32_t user_config_validation_password_max_length();
/**
 * 邮箱必填 (user.validation.email_required)
 * 描述: 注册时是否强制要求填写邮箱地址。
 * 建议值: true/false。true=必填，false=选填
 * 类型: BOOL
 */
bool user_config_validation_email_required();

#ifdef __cplusplus
}
#endif

#endif /* DOUYIN_MALL_PORTS_USER_H */
