// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置端口 — C 头文件
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 认证鉴权
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */

#ifndef DOUYIN_MALL_PORTS_AUTH_H
#define DOUYIN_MALL_PORTS_AUTH_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * 认证鉴权 域配置接口
 * 通过 vtable + setter 模式注入具体实现
 * 业务代码通过外观函数访问配置，无需关心底层实现
 */

// AuthConfig — 函数指针表
typedef struct {
    int64_t (*jwt_token_expiry_seconds)(void* impl_ctx);
    int32_t (*password_bcrypt_cost)(void* impl_ctx);
} auth_config_vtable_t;

// 全局 setter — 由 adapter 层在初始化时调用
void auth_config_set_impl(const auth_config_vtable_t* vtable, void* impl_ctx);

// 业务代码调用的外观函数
/**
 * JWT过期时间 (auth.jwt.token_expiry_seconds)
 * 描述: JWT登录令牌的有效期时长（秒），过期后用户需重新登录。
 * 建议值: 3600~604800（1小时~7天），推荐步长3600秒
 * 类型: I64
 */
int64_t auth_config_jwt_token_expiry_seconds();
/**
 * 密码加密强度 (auth.password.bcrypt_cost)
 * 描述: 密码哈希计算成本因子，控制密码加密强度。
 * 建议值: 4~14，推荐步长1。生产建议10~12
 * 类型: I32
 */
int32_t auth_config_password_bcrypt_cost();

#ifdef __cplusplus
}
#endif

#endif /* DOUYIN_MALL_PORTS_AUTH_H */
