// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置端口 — C 头文件
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 安全策略
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */

#ifndef DOUYIN_MALL_PORTS_CORS_H
#define DOUYIN_MALL_PORTS_CORS_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * 安全策略 域配置接口
 * 通过 vtable + setter 模式注入具体实现
 * 业务代码通过外观函数访问配置，无需关心底层实现
 */

// CorsConfig — 函数指针表
typedef struct {
    const char** (*allowed_origins)(void* impl_ctx, size_t* out_len);
} cors_config_vtable_t;

// 全局 setter — 由 adapter 层在初始化时调用
void cors_config_set_impl(const cors_config_vtable_t* vtable, void* impl_ctx);

// 业务代码调用的外观函数
/**
 * 跨域白名单 (cors.allowed_origins)
 * 描述: 允许跨域访问的域名来源列表。
 * 建议值: 生产环境禁止使用*。推荐格式：["https://mall.douyin.com","https://admin.douyin.com"]
 * 类型: ARR
 */
const char** cors_config_allowed_origins(size_t* out_len);

#ifdef __cplusplus
}
#endif

#endif /* DOUYIN_MALL_PORTS_CORS_H */
