// Code generated by blessstar-codegen. DO NOT EDIT.
// Source: manifest.json
// Business System: 抖音商城 (douyin-mall)

/**
 * 自动生成于 BlessStar 配置端口 — C 头文件
 * 业务系统: 抖音商城 (douyin-mall)
 * 领域: 商品管理
 * 请勿手动修改 — 由 blessstar-codegen 自动生成
 */

#ifndef DOUYIN_MALL_PORTS_PRODUCT_H
#define DOUYIN_MALL_PORTS_PRODUCT_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * 商品管理 域配置接口
 * 通过 vtable + setter 模式注入具体实现
 * 业务代码通过外观函数访问配置，无需关心底层实现
 */

// ProductConfig — 函数指针表
typedef struct {
    const char* (*status_values)(void* impl_ctx);
} product_config_vtable_t;

// 全局 setter — 由 adapter 层在初始化时调用
void product_config_set_impl(const product_config_vtable_t* vtable, void* impl_ctx);

// 业务代码调用的外观函数
/**
 * 商品状态 (product.status.values)
 * 描述: 商品生命周期状态枚举。
 * 建议值: 当前支持：1=在售，0=下架，-1=已删除。可扩展预售等状态但需配套逻辑
 * 类型: ENUM
 */
const char* product_config_status_values();

#ifdef __cplusplus
}
#endif

#endif /* DOUYIN_MALL_PORTS_PRODUCT_H */
